import type { DeployedMiroirTestExport } from "./runDeployedMiroirTestSuite";

export type MiroirTestSuiteLoader = () => Promise<{ default: DeployedMiroirTestExport }>;

/**
 * Maps CLI suite keys to dynamic import loaders.
 * AUTO-GENERATED by scripts/generate-miroir-test-instances.ts — do not edit by hand.
 */
export const MIROIR_TEST_SUITE_REGISTRY: Record<string, MiroirTestSuiteLoader> = {
  adminTransformers: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_adminTransformers as DeployedMiroirTestExport };
  },
  alterObject: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_alterObject as DeployedMiroirTestExport };
  },
  ansiColumnsToJzodSchema: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_ansiColumnsToJzodSchema as DeployedMiroirTestExport };
  },
  buildAnyKeyMap: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_buildAnyKeyMap as DeployedMiroirTestExport };
  },
  defaultValueForMLSchema: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_defaultValueForMLSchema as DeployedMiroirTestExport };
  },
  EntityPrimaryKey: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_EntityPrimaryKey as DeployedMiroirTestExport };
  },
  getAttributeTypesFromJzodSchema: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_getAttributeTypesFromJzodSchema as DeployedMiroirTestExport };
  },
  jzodObjectFlatten: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_jzodObjectFlatten as DeployedMiroirTestExport };
  },
  jzodReferencesGraphConnectedComponents: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_jzodReferencesGraphConnectedComponents as DeployedMiroirTestExport };
  },
  JzodSchemaReferencesList: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_JzodSchemaReferencesList as DeployedMiroirTestExport };
  },
  JzodSchemaReferencesSet: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_JzodSchemaReferencesSet as DeployedMiroirTestExport };
  },
  jzodToCopilotKitParameter: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_jzodToCopilotKitParameter as DeployedMiroirTestExport };
  },
  jzodToJsonSchema: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_jzodToJsonSchema as DeployedMiroirTestExport };
  },
  jzodToJzod_Summary: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_jzodToJzod_Summary as DeployedMiroirTestExport };
  },
  jzodTransitiveDependencySet: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_jzodTransitiveDependencySet as DeployedMiroirTestExport };
  },
  jzodTypeCheck: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_jzodTypeCheck as DeployedMiroirTestExport };
  },
  jzodUnion_RecursiveUnfold: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_jzodUnion_RecursiveUnfold as DeployedMiroirTestExport };
  },
  jzodUnionResolvedTypeForArray: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_jzodUnionResolvedTypeForArray as DeployedMiroirTestExport };
  },
  jzodUnionResolvedTypeForObject: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_jzodUnionResolvedTypeForObject as DeployedMiroirTestExport };
  },
  localizeJzodSchemaReferenceContext: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_localizeJzodSchemaReferenceContext as DeployedMiroirTestExport };
  },
  menu: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_menu as DeployedMiroirTestExport };
  },
  mergePositionBased: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_mergePositionBased as DeployedMiroirTestExport };
  },
  metaModelTransformers: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_metaModelTransformers as DeployedMiroirTestExport };
  },
  miroirCoreTransformers: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_miroirCoreTransformers as DeployedMiroirTestExport };
  },
  modelUpdates: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_modelUpdates as DeployedMiroirTestExport };
  },
  mustache: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_mustache as DeployedMiroirTestExport };
  },
  pilot_transformer_plus: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_pilot_transformer_plus as DeployedMiroirTestExport };
  },
  queries_library: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_queries_library as DeployedMiroirTestExport };
  },
  resolveConditionalSchema: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_resolveConditionalSchema as DeployedMiroirTestExport };
  },
  resolveQueryTemplates: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_resolveQueryTemplates as DeployedMiroirTestExport };
  },
  resolveSchemaReferenceInContext: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_resolveSchemaReferenceInContext as DeployedMiroirTestExport };
  },
  schema_pilot_empty: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_schema_pilot_empty as DeployedMiroirTestExport };
  },
  selectUnionBranchFromDiscriminator: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_selectUnionBranchFromDiscriminator as DeployedMiroirTestExport };
  },
  tools: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_tools as DeployedMiroirTestExport };
  },
  unfoldSchemaOnce: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_unfoldSchemaOnce as DeployedMiroirTestExport };
  },
  unionArrayChoices: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_unionArrayChoices as DeployedMiroirTestExport };
  },
  unionObjectChoices: async () => {
    const deployment = await import("miroir-test-app_deployment-miroir");
    return { default: deployment.miroirTest_unionObjectChoices as DeployedMiroirTestExport };
  },
};

export function listMiroirTestSuiteKeys(): string[] {
  return Object.keys(MIROIR_TEST_SUITE_REGISTRY).sort();
}

export async function loadMiroirTestSuiteExport(
  suiteKey: string,
): Promise<DeployedMiroirTestExport> {
  const loader = MIROIR_TEST_SUITE_REGISTRY[suiteKey];
  if (!loader) {
    throw new Error(
      `Unknown MiroirTest suite key "${suiteKey}". Available: ${listMiroirTestSuiteKeys().join(", ")}`,
    );
  }
  const loaded = await loader();
  return loaded.default;
}
