/**
 * TDD unit tests for AiProposalForm components.
 *
 * These components are pure React form UIs, decoupled from CopilotKit context.
 * They receive proposed data as props and call onAccept / onReject callbacks.
 */
import { render, screen, fireEvent } from "@testing-library/react";
import { describe, it, expect, vi } from "vitest";
import React from "react";
import { AiEntityProposalForm } from "../../src/miroir-fwk/4_view/routes/ai/AiEntityProposalForm.js";

// ──────────────────────────────────────────────────────────────────────────────
// Minimal MUI theme wrapper so MUI components render without errors
// ──────────────────────────────────────────────────────────────────────────────
import { ThemeProvider, createTheme } from "@mui/material";
const theme = createTheme();
function Wrapper({ children }: { children: React.ReactNode }) {
  return <ThemeProvider theme={theme}>{children}</ThemeProvider>;
}

// ──────────────────────────────────────────────────────────────────────────────
// Sample proposed entity data (mirrors the shape generated by miroirTools.ts)
// ──────────────────────────────────────────────────────────────────────────────
const sampleEntityProposal = {
  entity: {
    uuid: "aaaaaaaa-0001-0000-0000-000000000001",
    parentName: "Entity",
    parentUuid: "16dbfe28-e1d7-4f20-9ba4-c1a9873202ad",
    parentDefinitionVersionUuid: "bdd7ad43-f0fc-4716-90c1-87454c40dd95",
    conceptLevel: "Model",
    name: "Product",
    description: "A sellable product",
  },
  entityDefinition: {
    uuid: "aaaaaaaa-0001-0000-0000-000000000002",
    parentName: "EntityDefinition",
    parentUuid: "54b9c72f-d4f3-4db9-9e0e-0dc840b530bd",
    parentDefinitionVersionUuid: "bdd7ad43-f0fc-4716-90c1-87454c40dd95",
    name: "ProductDefinition",
    entityUuid: "aaaaaaaa-0001-0000-0000-000000000001",
    conceptLevel: "Model",
    jzodSchema: {
      type: "object",
      definition: {
        uuid: { type: "uuid", tag: { value: { id: 1, defaultLabel: "UUID" } } },
        parentUuid: { type: "uuid", tag: { value: { id: 2, defaultLabel: "Entity UUID" } } },
        conceptLevel: { type: "string", tag: { value: { id: 3, defaultLabel: "Concept Level" } } },
        parentDefinitionVersionUuid: {
          type: "uuid",
          tag: { value: { id: 4, defaultLabel: "Parent Definition Version UUID" } },
        },
        name: { type: "string", tag: { value: { id: 5, defaultLabel: "Name" } } },
        description: {
          type: "string",
          optional: true,
          tag: { value: { id: 6, defaultLabel: "Description" } },
        },
      },
    },
  },
  deploymentUuid: "11111111-1111-1111-1111-111111111111",
  summary: "Created entity Product with description 'A sellable product'",
};

// ──────────────────────────────────────────────────────────────────────────────
// AiEntityProposalForm tests
// ──────────────────────────────────────────────────────────────────────────────
describe("AiEntityProposalForm", () => {
  it("renders entity name from proposal", () => {
    render(
      <Wrapper>
        <AiEntityProposalForm
          proposal={sampleEntityProposal}
          onAccept={vi.fn()}
          onReject={vi.fn()}
        />
      </Wrapper>,
    );
    expect(screen.getByDisplayValue("Product")).toBeTruthy();
  });

  it("renders entity description from proposal", () => {
    render(
      <Wrapper>
        <AiEntityProposalForm
          proposal={sampleEntityProposal}
          onAccept={vi.fn()}
          onReject={vi.fn()}
        />
      </Wrapper>,
    );
    expect(screen.getByDisplayValue("A sellable product")).toBeTruthy();
  });

  it("shows Accept and Reject buttons", () => {
    render(
      <Wrapper>
        <AiEntityProposalForm
          proposal={sampleEntityProposal}
          onAccept={vi.fn()}
          onReject={vi.fn()}
        />
      </Wrapper>,
    );
    expect(screen.getByRole("button", { name: /accept/i })).toBeTruthy();
    expect(screen.getByRole("button", { name: /reject/i })).toBeTruthy();
  });

  it("calls onAccept with current form values when Accept is clicked", () => {
    const onAccept = vi.fn();
    render(
      <Wrapper>
        <AiEntityProposalForm
          proposal={sampleEntityProposal}
          onAccept={onAccept}
          onReject={vi.fn()}
        />
      </Wrapper>,
    );
    fireEvent.click(screen.getByRole("button", { name: /accept/i }));
    expect(onAccept).toHaveBeenCalledTimes(1);
    // The accepted value should contain the entity and entityDefinition
    const accepted = onAccept.mock.calls[0][0];
    expect(accepted).toHaveProperty("entity");
    expect(accepted).toHaveProperty("entityDefinition");
    expect(accepted.entity.name).toBe("Product");
  });

  it("calls onReject when Reject is clicked", () => {
    const onReject = vi.fn();
    render(
      <Wrapper>
        <AiEntityProposalForm
          proposal={sampleEntityProposal}
          onAccept={vi.fn()}
          onReject={onReject}
        />
      </Wrapper>,
    );
    fireEvent.click(screen.getByRole("button", { name: /reject/i }));
    expect(onReject).toHaveBeenCalledTimes(1);
  });

  it("allows editing the entity name before accepting", () => {
    const onAccept = vi.fn();
    render(
      <Wrapper>
        <AiEntityProposalForm
          proposal={sampleEntityProposal}
          onAccept={onAccept}
          onReject={vi.fn()}
        />
      </Wrapper>,
    );
    const nameInput = screen.getByDisplayValue("Product");
    fireEvent.change(nameInput, { target: { value: "ProductEdited" } });
    fireEvent.click(screen.getByRole("button", { name: /accept/i }));
    const accepted = onAccept.mock.calls[0][0];
    expect(accepted.entity.name).toBe("ProductEdited");
  });

  it("lists the entity attributes in the form", () => {
    render(
      <Wrapper>
        <AiEntityProposalForm
          proposal={sampleEntityProposal}
          onAccept={vi.fn()}
          onReject={vi.fn()}
        />
      </Wrapper>,
    );
    // The Description label should appear in the form (TextField label)
    expect(screen.getAllByText(/description/i).length).toBeGreaterThan(0);
  });

  it("shows a summary text from the proposal", () => {
    render(
      <Wrapper>
        <AiEntityProposalForm
          proposal={sampleEntityProposal}
          onAccept={vi.fn()}
          onReject={vi.fn()}
        />
      </Wrapper>,
    );
    expect(screen.getByText(/created entity product/i)).toBeTruthy();
  });
});
