import { useCallback, useMemo, useState } from "react";
// import { SubmitHandler } from 'react-hook-form';
import { v4 as uuidv4 } from 'uuid';
import { z } from "zod";

import {
  Action2Error,
  Action2VoidReturnType,
  ApplicationSection,
  applicationSection,
  Deployment,
  domain2ElementObjectZodSchema,
  Domain2QueryReturnType,
  DomainControllerInterface,
  DomainElementSuccess,
  Entity,
  EntityInstancesUuidIndex,
  entityMLSchema,
  ExtractorOrCombinerRecord,
  getApplicationSection,
  getDefaultValueForJzodSchemaWithResolutionNonHook,
  getQueryRunnerParamsForReduxDeploymentsState,
  InstanceAction,
  interpolateExpression,
  JzodElement,
  JzodObject,
  LoggerInterface,
  MetaModel,
  MiroirLoggerFactory,
  noValue,
  ReduxDeploymentsState,
  resolvePathOnObject,
  SyncBoxedExtractorOrQueryRunnerMap,
  SyncQueryRunner,
  SyncQueryRunnerExtractorAndParams,
  type CoreTransformerForBuildPlusRuntime,
  type MiroirModelEnvironment,
  type ReportSection
} from "miroir-core";

import { useFormikContext } from "formik";
import {
  getMemoizedReduxDeploymentsStateSelectorMap,
  JsonDisplayHelper,
  ReduxStateWithUndoRedo,
  useDomainControllerService,
  useMiroirContextInnerFormOutput,
  useMiroirContextService,
  useSelector,
  useSnackbar,
} from "miroir-react";
import { packageName } from "../../../../constants.js";
import {
  useCurrentModel,
  useCurrentModelEnvironment,
  useDefaultValueParams,
  useReduxDeploymentsStateQuerySelectorForCleanedResult,
} from "../../ReduxHooks.js";
import { cleanLevel } from "../../constants.js";
import { getMDataGridColumnDefinitionsFromEntity } from "../../getColumnDefinitionsFromEntityAttributes.js";
import { deleteCascade } from "../../scripts.js";
import { useRenderTracker } from "../../tools/renderCountTracker.js";
import { analyzeForeignKeyAttributes, convertToLegacyFormat } from "../../utils/foreignKeyAttributeAnalyzer.js";
import { EntityInstanceGrid } from "../Grids/EntityInstanceGrid.js";
import { TableComponentType, TableComponentTypeSchema } from "../Grids/EntityInstanceGridInterface.js";
import type { AutoGeneratedColumnDef } from "../Grids/ValueObjectGridInterface.js";
import { JsonObjectEditFormDialog, JsonObjectEditFormDialogInputs } from "../JsonObjectEditFormDialog.js";
import { RenderInsightHeader } from "../RenderInsightHeader.js";
import { AddBox } from "../Themes/MaterialSymbolWrappers";
import { ThemedBox, ThemedButton, ThemedSpan } from "../Themes/index.js";
import { ListTransformerPanel } from "./ListTransformerPanel.js";
import { ListTransformerToggle } from "./ListSectionTransformerControls.js";

import { selfApplicationMiroir } from "miroir-test-app_deployment-miroir";
const _miroirLoggerName = MiroirLoggerFactory.getLoggerName(packageName, cleanLevel, "ReportSectionListDisplay");
let log: LoggerInterface = MiroirLoggerFactory.getPreStartLogger(_miroirLoggerName);
MiroirLoggerFactory.registerLoggerToStart(_miroirLoggerName, "UI",
).then((logger: LoggerInterface) => {log = logger});

// ################################################################################################
export const ReportSectionDisplayCorePropsSchema = z.object({
  styles: z.any().optional(),
  label: z.string(),
  paramsAsdomainElements: domain2ElementObjectZodSchema,
  applicationDeploymentMap: z.record(z.string(), z.string().uuid()),

  // 
  formikValuePath: z.array(z.union([z.string(), z.number()])).optional(), // the path to the section inside the report definition
  // 
  formikReportDefinitionPathString: z.string(), // the path inside formik values to the report definition for the current Section
  reportSectionPath: z.array(z.union([z.string(), z.number()])).optional(), // the path to the section inside the report definition
  chosenApplicationSection: applicationSection.optional(), // ugly, this is due to the need of calling hooks in the same order, irrelevant of tableComponentReportType. Should be in ReportSectionDisplayEntityInstancePropsSchema.
});

export const ReportSectionDisplayEntityInstancePropsSchema = ReportSectionDisplayCorePropsSchema.extend({
  tableComponentReportType: z.literal(TableComponentTypeSchema.enum.EntityInstance),
  chosenApplicationSection: applicationSection,
  application: z.string().uuid(),
  deploymentUuid: z.string().uuid(),
});

export const ReportSectionDisplayJsonArrayPropsSchema = ReportSectionDisplayCorePropsSchema.extend({
  tableComponentReportType: z.literal(TableComponentTypeSchema.enum.JSON_ARRAY),
  columnDefs: z.array(z.any()),
  rowData: z.array(z.any()),
});

// ##########################################################################################
export const ReportSectionDisplayPropsSchema = ReportSectionDisplayEntityInstancePropsSchema;
export type ReportComponentProps = z.infer<typeof ReportSectionDisplayPropsSchema>;

// ##########################################################################################
// ##########################################################################################
// ##########################################################################################
// ##########################################################################################
export const ReportSectionListDisplay: React.FC<ReportComponentProps> = (
  props: ReportComponentProps
) => {
  // Track render counts with centralized tracker
  const currentNavigationKey = `${props.deploymentUuid}-${props.chosenApplicationSection}`;
  const { navigationCount, totalCount } = useRenderTracker("ReportSectionListDisplay", currentNavigationKey);

  const formikContext = useFormikContext<Record<string, any>>();
  const formikValuePathAsString = props.formikValuePath?.join("_") || "";

  const reportDefinitionFromFormik: Report | undefined =
    formikContext.values &&
    props.formikReportDefinitionPathString &&
    formikContext.values[props.formikReportDefinitionPathString]
      ? formikContext.values[props.formikReportDefinitionPathString]
      : undefined;

  const reportSectionDefinitionFromFormik: ReportSection | undefined =
    reportDefinitionFromFormik &&
    props.reportSectionPath
      ? resolvePathOnObject(
          reportDefinitionFromFormik,
          props.reportSectionPath ?? []
        )
      : undefined;

  // Do not early-return before hooks below — section type can resolve after Formik init
  // (Rules of Hooks: same number of hooks every render).
  const objectListReportSection =
    reportSectionDefinitionFromFormik?.type === "objectListReportSection"
      ? reportSectionDefinitionFromFormik
      : undefined;
  const unsupportedListSectionType =
    reportSectionDefinitionFromFormik && !objectListReportSection
      ? reportSectionDefinitionFromFormik.type
      : undefined;

  // ##############################################################################################
  const instancesToDisplay: EntityInstancesUuidIndex = useMemo(
    () =>
      formikContext.values && objectListReportSection?.definition.fetchedDataReference
        ? formikContext.values[objectListReportSection.definition.fetchedDataReference]
        : formikValuePathAsString && formikContext.values[formikValuePathAsString]
          ? formikContext.values[formikValuePathAsString]
          : {},
    [
      formikValuePathAsString,
      formikContext.values,
      // props.domainElementObjectDEFUNCT,
      objectListReportSection?.definition.fetchedDataReference,
    ],
  );

  const defaultLabel:string = interpolateExpression(
    objectListReportSection?.definition?.label ?? props.label,
    formikContext.values,
    "report label",
  );

  // log.info(
  //   "@@@@@@@@@@@@@@@@@@@@@@@ ReportSectionListDisplay",
  //   "navigationCount",
  //   navigationCount,
  //   "totalCount",
  //   totalCount,
  //   "instancesToDisplay",
  //   instancesToDisplay,
  //   "localReportDefinition",
  //   reportDefinitionFromFormik,
  //   "localReportSectionDefinition",
  //   reportSectionDefinitionFromFormik,
  //   "formikContext.values",
  //   formikContext.values,
  //   // "props === prevProps",
  //   // props === prevProps
  // );
  
  // ##############################################################################################
  const [addObjectdialogFormIsOpen, setAddObjectdialogFormIsOpen] = useState(false);
  const [transformerPanelEnabled, setTransformerPanelEnabled] = useState(false);
  const setAddObjectdialogFormIsOpenCallback = useCallback((a:boolean) => {
    // log.info("ReportSectionListDisplay setAddObjectdialogFormIsOpen called with",a);
    setAddObjectdialogFormIsOpen(a);
  },[setAddObjectdialogFormIsOpen]);
  const [dialogOuterFormObject, setdialogOuterFormObject] = useMiroirContextInnerFormOutput();

  const miroirMetaModel: MetaModel = useCurrentModel(
    selfApplicationMiroir.uuid,
    props.applicationDeploymentMap
  );
  const currentModel: MetaModel = useCurrentModel(props.application, props.applicationDeploymentMap);
  const context = useMiroirContextService();
  
  const currentMiroirModelEnvironment: MiroirModelEnvironment = useCurrentModelEnvironment(
    props.application,
    props.applicationDeploymentMap
  );
  // Get snackbar functionality from context
  const { handleAsyncAction } = useSnackbar();
  const domainController: DomainControllerInterface = useDomainControllerService();

  const deploymentEntityStateSelectorMap: SyncBoxedExtractorOrQueryRunnerMap<ReduxDeploymentsState> =
      getMemoizedReduxDeploymentsStateSelectorMap();

  const deploymentEntityState: ReduxDeploymentsState = useSelector(
    (state: ReduxStateWithUndoRedo) =>
      deploymentEntityStateSelectorMap.extractState(
        state.presentModelSnapshot.current,
        props.applicationDeploymentMap,
        () => ({}),
        currentMiroirModelEnvironment
      )
  );

  const entities  = useMemo(() => {
    const result = props.deploymentUuid &&
      context.deploymentUuidToReportsEntitiesMapping &&
      context.deploymentUuidToReportsEntitiesMapping[props.deploymentUuid]
      ? context.deploymentUuidToReportsEntitiesMapping[props.deploymentUuid][
        props.chosenApplicationSection
        ]
      : undefined;
      return result?.entities ?? [];
  }, [
    props.deploymentUuid,
    context.deploymentUuidToReportsEntitiesMapping,
    props.chosenApplicationSection,
  ]);
    
  const currentReportTargetEntity: Entity | undefined = entities.find((e) => e.uuid === objectListReportSection?.definition.parentUuid);
    // objectListReportSection
    //   ? findEntityFromUuid(
    //       { entities, entityVersions },
    //       objectListReportSection.definition.parentUuid,
    //     )
    //   : undefined;

  // TODO: AMBIGUOUS!! APPEARS ALSO IN THE Report DEFINITION. PROVIDE A DIRECT WAY TO DETERMINE THIS?
  const currentApplicationSection = props.chosenApplicationSection??"data";

  // ##############################################################################################
  const instancesToDisplayJzodSchema: JzodObject | undefined = useMemo(
    () =>
        currentReportTargetEntity
          ? entityMLSchema(currentReportTargetEntity)
          : undefined,
    [
      currentReportTargetEntity,
      currentReportTargetEntity?.mlSchema,
    ],
  );

  // log.info(
  //   "ReportSectionListDisplay currentReportTargetEntity",
  //   currentReportTargetEntity,
  //   "currentReportTargetEntity",
  //   currentReportTargetEntity,
  // );

  // ##############################################################################################
  // FOREIGN KEY OBJECTS FETCHING
  const foreignKeyObjectsAttributeDefinition:[string, JzodElement][] = useMemo(
    ()=> {
      if (props.tableComponentReportType !== TableComponentTypeSchema.enum.EntityInstance) {
        return [];
      }

      const foreignKeyAttributes = analyzeForeignKeyAttributes(
        currentReportTargetEntity,
        entities ?? [],
        { includeTransitive: true, maxDepth: 5 }
      );

      return convertToLegacyFormat(foreignKeyAttributes);
    },
    [
      currentReportTargetEntity?.mlSchema?.definition,
      currentReportTargetEntity?.uuid,
      props.tableComponentReportType,
      entities,
    ]
  );

  const foreignKeyObjectsFetchQueryParams: SyncQueryRunnerExtractorAndParams<
    ReduxDeploymentsState
  > = useMemo(
    () => {
      const extractors: ExtractorOrCombinerRecord = Object.fromEntries(
        foreignKeyObjectsAttributeDefinition.map((e) => [
          e[1].tag?.value?.foreignKeyParams?.targetEntity + "_extractor",
          {
            extractorOrCombinerType: "extractorInstancesByEntity",
            label: "extractorForForeignKey_" + e[0],
            applicationSection: getApplicationSection(
              props.application,
              e[1].tag?.value?.foreignKeyParams?.targetEntity ?? "undefined"
            ),
            parentName: "",
            parentUuid: e[1].tag?.value?.foreignKeyParams?.targetEntity??"ERROR NO TARGET ENTITY FOR ATTRIBUTE " + e[0], // does not happen because of filter in foreignKeyObjectsAttributeDefinition
          },
        ])
      );
      const runtimeTransformers: {
        [x: string]: CoreTransformerForBuildPlusRuntime
      } = {
        ...Object.fromEntries(
          foreignKeyObjectsAttributeDefinition.map((e) => [
            e[1].tag?.value?.foreignKeyParams?.targetEntity,
            {
              transformerType: "indexListBy",
              interpolation: "runtime",
              applyTo: {
                transformerType: "getFromContext",
                interpolation: "runtime",
                referenceName: e[1].tag?.value?.foreignKeyParams?.targetEntity + "_extractor",
              },
              indexAttribute: "uuid",
            },
          ])
        ),
      };
      return getQueryRunnerParamsForReduxDeploymentsState(
        {
          queryType: "boxedQueryWithExtractorCombinerTransformer",
          application: props.application,
          pageParams: props.paramsAsdomainElements,
          extractors,
          runtimeTransformers
        },
        deploymentEntityStateSelectorMap
      )
    },
    [
      foreignKeyObjectsAttributeDefinition,
      props.deploymentUuid,
      props.paramsAsdomainElements,
      deploymentEntityStateSelectorMap,
    ]
  );

  const foreignKeyObjects: Record<string, EntityInstancesUuidIndex> =
  useReduxDeploymentsStateQuerySelectorForCleanedResult(
    deploymentEntityStateSelectorMap.runQuery as SyncQueryRunner<
      ReduxDeploymentsState,
      Domain2QueryReturnType<DomainElementSuccess>
    >,
    foreignKeyObjectsFetchQueryParams,
    props.applicationDeploymentMap
  );

  const defaultValueParams = useDefaultValueParams(
    props.application,
    props.deploymentUuid
  );
  // // ##############################################################################################
  const onCreateFormObject = useCallback(
    async (data: any) => {
      // log.info("ReportComponent onEditFormObject called with new object value", data);

      if (props.application) {
        if (props.chosenApplicationSection == "model") {
          await domainController.handleActionFromUI(
            {
              actionType: "transactionalInstanceAction",
              endpoint: "1e2ef8e6-7fdf-4e3f-b291-2e6e599fb2b5",
              payload: {
                application: props.application,
                instanceAction: {
                  actionType: "createInstance",
                  endpoint: "ed520de4-55a9-4550-ac50-b1b713b72a89",
                  payload: {
                    application: props.application,
                    applicationSection: currentApplicationSection,
                    objects: [data],
                  },
                },
              },
            },
            props.applicationDeploymentMap,
            currentMiroirModelEnvironment, // TODO: use model environment for current deployment
          );
        } else {
          const createAction: InstanceAction = {
            actionType: "createInstance",
            endpoint: "ed520de4-55a9-4550-ac50-b1b713b72a89",
            payload: {
              application: props.application,
              applicationSection: currentApplicationSection,
              objects: [data],
            },
          };
          await domainController.handleActionFromUI(createAction, props.applicationDeploymentMap);
        }
      } else {
        throw new Error(
          "ReportComponent onSubmitOuterDialog props.displayedDeploymentDefinition is undefined.",
        );
      }
    },
    [
      domainController,
      props.application,
      props.chosenApplicationSection,
      props.tableComponentReportType,
      currentApplicationSection,
      currentModel,
    ],
  );

  // ##############################################################################################
  const onEditFormObject = useCallback(
    async (data: any): Promise<Action2VoidReturnType> => {
      // log.info("ReportComponent onEditFormObject called with new object value", data);

      if (props.application) {
        let result: Action2VoidReturnType;
        if (props.chosenApplicationSection == "model") {
          result = await domainController.handleActionFromUI(
            {
              actionType: "transactionalInstanceAction",
              endpoint: "1e2ef8e6-7fdf-4e3f-b291-2e6e599fb2b5",
              payload: {
                application: props.application,
                instanceAction: {
                  actionType: "updateInstance",
                  endpoint: "ed520de4-55a9-4550-ac50-b1b713b72a89",
                  payload: {
                    application: props.application,
                    applicationSection: "model",
                    objects: [data],
                  },
                },
              },
            },
            props.applicationDeploymentMap,
            currentMiroirModelEnvironment // TODO: use model environment for current deployment
          );
        } else {
          const updateAction: InstanceAction = {
            actionType: "updateInstance",
            endpoint: "ed520de4-55a9-4550-ac50-b1b713b72a89",
            payload: {
              application: props.application,
              applicationSection: props.chosenApplicationSection
                ? props.chosenApplicationSection
                : "data",
              objects: [data],
            },
          };
          result = await domainController.handleActionFromUI(updateAction, props.applicationDeploymentMap);
        }
        return result;
      } else {
        throw new Error(
          "ReportComponent onSubmitOuterDialog props.displayedDeploymentDefinition is undefined."
        );
      }
    },
    [
      domainController,
      props.deploymentUuid,
      props.chosenApplicationSection,
      props.tableComponentReportType,
      currentModel,
      props.applicationDeploymentMap,
    ]
  );

  // ##############################################################################################
  const onDeleteFormObject = useCallback(
    async (data:any) => {
      // log.info('onDeleteFormObject called with new object value',data);
      // log.info('onDeleteFormObject called with props',props);
      
      if (props.application) {
          if (!currentReportTargetEntity) {
           throw new Error(
             "ReportSectionListDisplay onDeleteFormObject no Entity found for object to delete! " +
               data,
           );
          }

          await deleteCascade(
            {
              application: props.application,
              applicationDeploymentMap: props.applicationDeploymentMap,
              applicationSection: props.chosenApplicationSection?props.chosenApplicationSection:"data" as ApplicationSection,
              deploymentUuid: props.deploymentUuid,
              domainController: domainController,
              entity: currentReportTargetEntity,
              entities: currentModel.entities,
              entityInstances: [data],
            }
          )
      }
    },
    [domainController, props.application, props.chosenApplicationSection, currentReportTargetEntity, currentModel]
  )

  
  // ##############################################################################################
  const onSubmitOuterDialog: (data: JsonObjectEditFormDialogInputs)=>void = useCallback(
    async (data) => {
      // log.info('ReportComponent onSubmitOuterDialog','data',data);
    
      // showSnackbar("Operation completed successfully!", "success");
      await handleAsyncAction(
        async () => { 
            const editResult = await onEditFormObject(data);

            // log.info('ReportComponent onSubmitOuterDialog done for','data',data, "editResult",editResult);

            if (editResult && editResult instanceof Action2Error) {
              log.error('ReportComponent onSubmitOuterDialog error',editResult);
            } else {
              // The form already calls onCreateFormObject, so we just need to close the dialog
              setAddObjectdialogFormIsOpen(false);
            }
         },
        "Operation completed successfully!",
        "onEditFormObject"
      );
    },
    [setAddObjectdialogFormIsOpen]
  )

  // ##############################################################################################
  // TODO: default value should be established in the main body with useMemo instead, get rid of the state / side effect
  const handleAddObjectDialogFormOpen = useCallback(
    // (label: string  | undefined, a: any) => {
      () => {
      // log.info(
      //   "handleAddObjectDialogFormOpen defined with currentReportTargetEntity",
      //   currentReportTargetEntity,
      //   "currentReportTargetEntity",
      //   currentReportTargetEntity,
      //   Object.keys(currentReportTargetEntity?.mlSchema?.definition ?? {}),
      //   Object.entries(currentReportTargetEntity?.mlSchema?.definition ?? {})
      // );
      const defaultFormValuesObject =
        currentReportTargetEntity &&
        currentReportTargetEntity &&
        currentReportTargetEntity?.mlSchema &&
          (context.schemasPerDeployment[props.deploymentUuid] ??
            currentMiroirModelEnvironment.miroirFundamentalJzodSchema)
          ? getDefaultValueForJzodSchemaWithResolutionNonHook(
              "build",
              currentReportTargetEntity?.mlSchema,
              undefined, // rootObject
              "", // rootLessListKey,
              undefined, // No need to pass currentDefaultValue here
              [], // currentPath on value is root
              false, // forceOptional
              props.application,
              props.applicationDeploymentMap,
              props.deploymentUuid,
              currentMiroirModelEnvironment,
              defaultValueParams, // transformerParams
              {}, // contextResults
              deploymentEntityState,
            )
          : undefined;

      // log.info(
      //   "handleAddObjectDialogFormOpen",
      //   "called, formObject",
      //   defaultFormValuesObject,
      //   "currentReportTargetEntity",
      //   currentReportTargetEntity
      // );

      defaultFormValuesObject.parentUuid = currentReportTargetEntity?.uuid;
      defaultFormValuesObject.parentName = currentReportTargetEntity?.name;
      setdialogOuterFormObject(
        defaultFormValuesObject,
      );
      setAddObjectdialogFormIsOpen(true);
    },
    [
      setAddObjectdialogFormIsOpen,
      setdialogOuterFormObject,
      currentReportTargetEntity,
    ]
  );

  // ##############################################################################################
  const handleAddObjectDialogTableRowFormClose = useCallback((value?: string, event?:any) => {
    event?.stopPropagation();
    // log.info('ReportSectionListDisplay handleDialogTableRowFormClose',value);
    
    setAddObjectdialogFormIsOpenCallback(false);
  },[setAddObjectdialogFormIsOpen]);

  const tableColumnDefs: { columnDefs: AutoGeneratedColumnDef[] } = useMemo(
    () =>
      (objectListReportSection
        ? {
            columnDefs: getMDataGridColumnDefinitionsFromEntity(
              props.deploymentUuid,
              instancesToDisplayJzodSchema ?? { type: "object", definition: {} },
              objectListReportSection,
              currentReportTargetEntity
            ),
          }
        : {}) as { columnDefs: AutoGeneratedColumnDef[] },
    [
      props.deploymentUuid,
      instancesToDisplayJzodSchema,
      objectListReportSection,
      currentReportTargetEntity,
    ]
  );
  return (
    <ThemedBox className="MiroirReport-global" display="block">
      {unsupportedListSectionType ? (
        <ThemedSpan>
          ReportSectionListDisplay: Unsupported report section type:{" "}
          {unsupportedListSectionType}
        </ThemedSpan>
      ) : (
        <>
      {context.showPerformanceDisplay && (
        <RenderInsightHeader
          componentName="ReportSectionListDisplay"
          navigationCount={navigationCount}
          totalCount={totalCount}
        />
      )}
      <JsonDisplayHelper
        debug={true}
        componentName="ReportSectionListDisplay"
        elements={[
          {
            label: "props",
            data: {
              props,
              formikValuePathAsString,
              val: formikContext.values[formikValuePathAsString],
              // domainElementObjectDEFUNCT: props.domainElementObjectDEFUNCT,
              fetchedDataReference: objectListReportSection?.definition.fetchedDataReference,
            },
            useCodeBlock: true,
          },
          {
            label: "formik values",
            data: { formik: formikContext.values },
            useCodeBlock: true,
          },
          {
            label: "instancesToDisplayJzodSchema",
            data: instancesToDisplayJzodSchema,
            useCodeBlock: true,
            copyButton: true,
          },
          {
            label: "instancesToDisplay",
            data: instancesToDisplay,
            useCodeBlock: true,
            copyButton: true,
          },
          {
            label: "reportSectionDefinitionFromFormik",
            data: reportSectionDefinitionFromFormik,
            useCodeBlock: true,
          },
        ]}
      />
      {objectListReportSection &&
      currentReportTargetEntity &&
      currentReportTargetEntity ? (
        !!tableColumnDefs ? (
          <div>
            <div
              style={{ display: "flex", alignItems: "baseline", gap: "10px", marginBottom: "10px" }}
            >
              <h3 style={{ margin: 0 }}>
                {defaultLabel??
                  currentReportTargetEntity?.name ??
                  "No Entity Found!"
                  }
                {/* {props.defaultlabel ??
                  currentReportTargetEntity?.name ??
                  "No Entity Found!"} */}
              </h3>
              <ThemedButton
                style={{
                  padding: "4px 8px",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                }}
                variant="secondary"
                onClick={() => {
                  handleAddObjectDialogFormOpen();
                }}
              >
                <AddBox style={{ fontSize: "1em", display: "block" }} />
              </ThemedButton>
              <ListTransformerToggle
                enabled={transformerPanelEnabled}
                onToggle={() => setTransformerPanelEnabled((on) => !on)}
              />
            </div>
            {addObjectdialogFormIsOpen ? (
              <JsonObjectEditFormDialog
                showButton={false}
                valueObjectEditMode="create"
                isOpen={addObjectdialogFormIsOpen}
                isAttributes={true}
                label={defaultLabel ?? currentReportTargetEntity?.name}
                defaultFormValuesObject={dialogOuterFormObject}
                entity={currentReportTargetEntity ?? {} as Entity}
                mlSchema={
                  currentReportTargetEntity?.mlSchema as JzodObject
                }
                foreignKeyObjects={foreignKeyObjects}
                currentApplication={props.application}
                applicationDeploymentMap={props.applicationDeploymentMap}
                currentDeploymentUuid={props.deploymentUuid}
                currentApplicationSection={props.chosenApplicationSection}
                currentAppModel={currentModel}
                currentMiroirModel={miroirMetaModel}
                addObjectdialogFormIsOpen={addObjectdialogFormIsOpen}
                onSubmit={onSubmitOuterDialog}
                onClose={handleAddObjectDialogTableRowFormClose}
                onCreateFormObject={onCreateFormObject}
                //
                // setAddObjectdialogFormIsOpen={setAddObjectdialogFormIsOpen}
                setAddObjectdialogFormIsOpen={setAddObjectdialogFormIsOpenCallback}
              />
            ) : (
              <></>
            )}
            {props.deploymentUuid ? (
              <div>
                <EntityInstanceGrid
                  type={props.tableComponentReportType}
                  styles={props.styles}
                  currentEntity={currentReportTargetEntity}
                  foreignKeyObjects={foreignKeyObjects}
                  currentModel={currentModel}
                  columnDefs={tableColumnDefs}
                  instancesToDisplay={instancesToDisplay}
                  application={props.application}
                  applicationDeploymentMap={props.applicationDeploymentMap}
                  deploymentUuid={props.deploymentUuid}
                  displayTools={true}
                  pageSize={50}
                  onRowEdit={onEditFormObject}
                  onRowDelete={onDeleteFormObject}
                  sortByAttribute={objectListReportSection.definition?.sortByAttribute}
                  paramsAsdomainElements={props.paramsAsdomainElements as any} // TODO: which is right? DomainElementObject or record<string, any>?
                  //
                  addObjectdialogFormIsOpen={addObjectdialogFormIsOpen}
                  setAddObjectdialogFormIsOpen={setAddObjectdialogFormIsOpenCallback}
                ></EntityInstanceGrid>
                {transformerPanelEnabled ? (
                  <ListTransformerPanel
                    instancesToDisplay={instancesToDisplay}
                    application={props.application}
                    applicationDeploymentMap={props.applicationDeploymentMap}
                    deploymentUuid={props.deploymentUuid}
                    sectionLabel={defaultLabel ?? currentReportTargetEntity?.name}
                  />
                ) : null}
              </div>
            ) : (
              <div></div>
            )}
          </div>
        ) : (
          <span>No elements in the report</span>
        )
      ) : (
        <ThemedSpan style={{ color: "red" }}>
          ReportSectionListDisplay, no report or incorrect report to display:{" "}
          {JSON.stringify(reportSectionDefinitionFromFormik)}
        </ThemedSpan>
      )}
        </>
      )}
    </ThemedBox>
  );
}