import { useCallback, useMemo, useState } from "react";
// import { SubmitHandler } from 'react-hook-form';
import { v4 as uuidv4 } from 'uuid';
import { z } from "zod";


import {
  Action2Error,
  Action2VoidReturnType,
  ApplicationSection,
  applicationSection,
  domain2ElementObjectZodSchema,
  Domain2QueryReturnType,
  DomainControllerInterface,
  DomainElementSuccess,
  Entity,
  EntityDefinition,
  EntityInstancesUuidIndex,
  ExtractorOrCombinerRecord,
  getApplicationSection,
  getDefaultValueForJzodSchemaWithResolutionNonHook,
  getQueryRunnerParamsForReduxDeploymentsState,
  InstanceAction,
  JzodElement,
  JzodObject,
  jzodObject,
  LoggerInterface,
  MetaModel,
  MiroirLoggerFactory,
  noValue,
  objectListReportSection,
  ReduxDeploymentsState,
  resolvePathOnObject,
  Deployment,
  deployment,
  selfApplicationMiroir,
  SyncBoxedExtractorOrQueryRunnerMap,
  SyncQueryRunner,
  SyncQueryRunnerExtractorAndParams,
  type MiroirModelEnvironment,
  type ReportSection,
  type TransformerForBuildPlusRuntime
} from "miroir-core";

import { useFormikContext } from "formik";
import {
  getMemoizedReduxDeploymentsStateSelectorMap,
  ReduxStateWithUndoRedo,
  useSelector,
} from "../../../miroir-localcache-imports.js";
import { packageName } from "../../../../constants.js";
import {
  useDomainControllerService,
  useMiroirContextInnerFormOutput,
  useMiroirContextService,
  useSnackbar,
} from "../../MiroirContextReactProvider.js";
import {
  useCurrentModel,
  useCurrentModelEnvironment,
  useReduxDeploymentsStateQuerySelectorForCleanedResult,
} from "../../ReduxHooks.js";
import { cleanLevel } from "../../constants.js";
import { getMDataGridColumnDefinitionsFromEntityDefinition } from "../../getColumnDefinitionsFromEntityAttributes.js";
import { deleteCascade } from "../../scripts.js";
import { useRenderTracker } from "../../tools/renderCountTracker.js";
import { analyzeForeignKeyAttributes, convertToLegacyFormat } from "../../utils/foreignKeyAttributeAnalyzer.js";
import { EntityInstanceGrid } from "../Grids/EntityInstanceGrid.js";
import { TableComponentType, TableComponentTypeSchema } from "../Grids/EntityInstanceGridInterface.js";
import type { AutoGeneratedColumnDef } from "../Grids/ValueObjectGridInterface.js";
import { JsonObjectEditFormDialog, JsonObjectEditFormDialogInputs } from "../JsonObjectEditFormDialog.js";
import { AddBox } from "../Themes/MaterialSymbolWrappers";
import { ThemedBox, ThemedButton, ThemedSpan } from "../Themes/index.js";
import { ThemedOnScreenDebug } from "../Themes/BasicComponents.js";


let log: LoggerInterface = console as any as LoggerInterface;
MiroirLoggerFactory.registerLoggerToStart(
  MiroirLoggerFactory.getLoggerName(packageName, cleanLevel, "ReportSectionListDisplay"), "UI",
).then((logger: LoggerInterface) => {log = logger});



// ################################################################################################
export const ReportSectionDisplayCorePropsSchema = z.object({
  styles: z.any().optional(),
  label: z.string(),
  defaultlabel: z.string().optional(),
  paramsAsdomainElements: domain2ElementObjectZodSchema,
  // displayedDeploymentDefinition: deployment.optional(),
  applicationDeploymentMap: z.record(z.string(), z.string().uuid()),

  // 
  // domainElementObject: domainElementObject, // ugly, this is due to the need of calling hooks in the same order, irrelevant of tableComponentReportType. Should be in ReportSectionDisplayEntityInstancePropsSchema.
  domainElementObjectDEFUNCT: domain2ElementObjectZodSchema, // DEFUNCT because formikContext.values shall be used instead
  fetchedDataJzodSchemaDEFUNCT: z.record(jzodObject.optional()).optional(), // the Jzod schemas of the domainElementObject, defunct because formikContext.values shall be used instead
  formikValuePath: z.array(z.union([z.string(), z.number()])).optional(), // the path to the section inside the report definition
  // 
  reportSectionDEFUNCT: objectListReportSection, // ugly, this is due to the need of calling hooks in the same order, irrelevant of tableComponentReportType. Should be in ReportSectionDisplayEntityInstancePropsSchema.
  formikReportDefinitionPathString: z.string(), // the path inside formik values to the report definition for the current Section
  reportSectionPath: z.array(z.union([z.string(), z.number()])).optional(), // the path to the section inside the report definition
  chosenApplicationSection: applicationSection.optional(), // ugly, this is due to the need of calling hooks in the same order, irrelevant of tableComponentReportType. Should be in ReportSectionDisplayEntityInstancePropsSchema.
});

export const ReportSectionDisplayEntityInstancePropsSchema = ReportSectionDisplayCorePropsSchema.extend({
  tableComponentReportType: z.literal(TableComponentTypeSchema.enum.EntityInstance),
  chosenApplicationSection: applicationSection,
  application: z.string().uuid(),
  deploymentUuid: z.string().uuid(),
});

export const ReportSectionDisplayJsonArrayPropsSchema = ReportSectionDisplayCorePropsSchema.extend({
  tableComponentReportType: z.literal(TableComponentTypeSchema.enum.JSON_ARRAY),
  columnDefs: z.array(z.any()),
  rowData: z.array(z.any()),
});

// ##########################################################################################
export const ReportSectionDisplayPropsSchema = ReportSectionDisplayEntityInstancePropsSchema;
export type ReportComponentProps = z.infer<typeof ReportSectionDisplayPropsSchema>;

// ##########################################################################################
// ##########################################################################################
// ##########################################################################################
// ##########################################################################################
// ##########################################################################################
export function defaultFormValues(
  tableComponentType: TableComponentType,
  currentEntityJzodSchema: JzodObject,
  idList?:{id:number}[],
  currentMiroirEntity?: Entity,
  application?: string,
  displayedDeploymentDefinition?: Deployment,
):any {
  // log.info(
  //   "defaultFormValues called TableComponentType",
  //   tableComponentType,
  //   "currentMiroirEntity",
  //   currentMiroirEntity,
  //   "currentEntityJzodSchema",
  //   currentEntityJzodSchema
  // );

  let subresult
  switch (tableComponentType) {
    case "EntityInstance": {
      const attributeDefaultValue:any = {
        'uuid': uuidv4(),
        // 'id': 1,
        'parentName':currentMiroirEntity?.name,
        'parentUuid':currentMiroirEntity?.uuid,
        'conceptLevel':'Model',
        // 'selfApplication': displayedDeploymentDefinition?.selfApplication,
        'selfApplication': application,
        'attributes': [],
      }
      
      const currentEditorAttributes = Object.entries(currentEntityJzodSchema?.definition??{}).reduce((acc,attributeJzodSchema)=>{
        let result
        if (attributeJzodSchema[1].tag?.value?.foreignKeyParams?.targetEntity) {
          result = Object.assign({},acc,{[attributeJzodSchema[0]]:noValue})
        } else {
          if (Object.keys(attributeDefaultValue).includes(attributeJzodSchema[0])) {
            result = Object.assign({},acc,{[attributeJzodSchema[0]]:attributeDefaultValue[attributeJzodSchema[0]]})
          } else {
            result = Object.assign({},acc,{[attributeJzodSchema[0]]:''})
          }
        }
        // log.info('ReportComponent defaultFormValues',tableComponentType,'EntityInstance setting default value for attribute',a.name,':',result);
        return result;
      },{});
      // log.info('defaultFormValues return',currentEditorAttributes);
      subresult = currentEditorAttributes;
      break;
    }
    case "JSON_ARRAY": {
      const newId = idList? idList?.reduce((acc:number,curr:{id:number}) => Math.max(curr?.id,acc),0) + 1 : 1;
      const attributeDefaultValue:any = {
        'uuid': uuidv4(),
        'id': newId,
        'conceptLevel':'Model',
        // 'attributes': [],
      }
      // TODO: CORRECT THIS IT DOES NOT WORK!!!
      const currentEditorAttributes = Object.entries(currentEntityJzodSchema).reduce((acc,currentAttribute)=>{
        const attributeName = (currentAttribute[1] as any).name
        let result
        if (Object.keys(attributeDefaultValue).includes((currentAttribute[1] as any).name)) {
          result = Object.assign({},acc,{[attributeName]:attributeDefaultValue[attributeName]})
        } else {
          result = Object.assign({},acc,{[attributeName]:''})
        }
        // log.info('ReportComponent defaultFormValues',tableComponentType,'setting default value for attribute',attributeName,':',result);
        return result;
      },{});
      // log.info('defaultFormValues return',currentEditorAttributes);
      subresult = currentEditorAttributes;
      break;
    }
    default: {
      throw new Error("defaultFormValues could not handle tableComponentType " + tableComponentType);
      break;
    }
  }
  // return {ROOT: subresult}
  return subresult;
}

// ##########################################################################################
// let prevProps = {};

// ##########################################################################################
// ##########################################################################################
// ##########################################################################################
// ##########################################################################################
export const ReportSectionListDisplay: React.FC<ReportComponentProps> = (
  props: ReportComponentProps
) => {
  // Track render counts with centralized tracker
  const currentNavigationKey = `${props.deploymentUuid}-${props.chosenApplicationSection}`;
  const { navigationCount, totalCount } = useRenderTracker("ReportSectionListDisplay", currentNavigationKey);

  const formikContext = useFormikContext<Record<string, any>>();
  const formikValuePathAsString = props.formikValuePath?.join("_") || "";

  const reportDefinitionFromFormik: Report | undefined =
    formikContext.values &&
    props.formikReportDefinitionPathString &&
    formikContext.values[props.formikReportDefinitionPathString]
      ? formikContext.values[props.formikReportDefinitionPathString]
      : undefined;

  const reportSectionDefinitionFromFormik: ReportSection | undefined =
    reportDefinitionFromFormik &&
    props.reportSectionPath
      ? resolvePathOnObject(
          // props.reportDefinitionDEFUNCT, props.reportSectionPath ?? []
          reportDefinitionFromFormik,
          props.reportSectionPath ?? []
        )
      : undefined;

  // ##############################################################################################
  const instancesToDisplay: EntityInstancesUuidIndex = useMemo(
    () =>
      formikContext.values && props.reportSectionDEFUNCT?.definition.fetchedDataReference
        ? formikContext.values[props.reportSectionDEFUNCT.definition.fetchedDataReference]
        : formikValuePathAsString && formikContext.values[formikValuePathAsString]
          ? formikContext.values[formikValuePathAsString]
          : {},
    [
      formikValuePathAsString,
      formikContext.values,
      props.domainElementObjectDEFUNCT,
      props.reportSectionDEFUNCT?.definition.fetchedDataReference,
    ],
  );


  // log.info(
  //   "@@@@@@@@@@@@@@@@@@@@@@@ ReportSectionListDisplay",
  //   "navigationCount",
  //   navigationCount,
  //   "totalCount",
  //   totalCount,
  //   "instancesToDisplay",
  //   instancesToDisplay,
  //   "localReportDefinition",
  //   reportDefinitionFromFormik,
  //   "localReportSectionDefinition",
  //   reportSectionDefinitionFromFormik,
  //   "formikContext.values",
  //   formikContext.values,
  //   // "props === prevProps",
  //   // props === prevProps
  // );
  
  // ##############################################################################################
  const [addObjectdialogFormIsOpen, setAddObjectdialogFormIsOpen] = useState(false);
  const setAddObjectdialogFormIsOpenCallback = useCallback((a:boolean) => {
    // log.info("ReportSectionListDisplay setAddObjectdialogFormIsOpen called with",a);
    setAddObjectdialogFormIsOpen(a);
  },[setAddObjectdialogFormIsOpen]);
  const [dialogOuterFormObject, setdialogOuterFormObject] = useMiroirContextInnerFormOutput();

  const miroirMetaModel: MetaModel = useCurrentModel(
    selfApplicationMiroir.uuid,
    props.applicationDeploymentMap
  );
  const currentModel: MetaModel = useCurrentModel(props.application, props.applicationDeploymentMap);
  const context = useMiroirContextService();
  
  const currentMiroirModelEnvironment: MiroirModelEnvironment = useCurrentModelEnvironment(
    props.application,
    props.applicationDeploymentMap
  );
  // Get snackbar functionality from context
  const { handleAsyncAction } = useSnackbar();
  const domainController: DomainControllerInterface = useDomainControllerService();

  const deploymentEntityStateSelectorMap: SyncBoxedExtractorOrQueryRunnerMap<ReduxDeploymentsState> =
      getMemoizedReduxDeploymentsStateSelectorMap();

  const deploymentEntityState: ReduxDeploymentsState = useSelector(
    (state: ReduxStateWithUndoRedo) =>
      deploymentEntityStateSelectorMap.extractState(
        state.presentModelSnapshot.current,
        props.applicationDeploymentMap,
        () => ({}),
        currentMiroirModelEnvironment
      )
  );

  const { availableReports, entities, entityDefinitions } = useMemo(() => {
    return props.deploymentUuid &&
      context.deploymentUuidToReportsEntitiesDefinitionsMapping &&
      context.deploymentUuidToReportsEntitiesDefinitionsMapping[props.deploymentUuid]
      ? context.deploymentUuidToReportsEntitiesDefinitionsMapping[props.deploymentUuid][
        props.chosenApplicationSection
        ]
      : { availableReports: [], entities: [], entityDefinitions: [] };
  }, [
    props.deploymentUuid,
    context.deploymentUuidToReportsEntitiesDefinitionsMapping,
    props.chosenApplicationSection,
  ]);
    
  const currentReportTargetEntity: Entity | undefined =
    reportSectionDefinitionFromFormik?.type === "objectListReportSection" 
      ? entities?.find(
          (e:Entity) =>
            e?.uuid === reportSectionDefinitionFromFormik?.definition.parentUuid
        )
      : undefined;
  const currentReportTargetEntityDefinition: EntityDefinition | undefined =
    entityDefinitions?.find((e:EntityDefinition) => e?.entityUuid === currentReportTargetEntity?.uuid);

  // TODO: AMBIGUOUS!! APPEARS ALSO IN THE Report DEFINITION. PROVIDE A DIRECT WAY TO DETERMINE THIS?
  const currentApplicationSection = props.chosenApplicationSection??"data";

  // ##############################################################################################
  const instancesToDisplayJzodSchema: JzodObject | undefined = useMemo(
    () =>
      props.fetchedDataJzodSchemaDEFUNCT &&
      props.reportSectionDEFUNCT.type == "objectListReportSection" &&
      props.reportSectionDEFUNCT.definition.fetchedDataReference &&
      props.fetchedDataJzodSchemaDEFUNCT[props.reportSectionDEFUNCT.definition.fetchedDataReference]
        ? props.fetchedDataJzodSchemaDEFUNCT[
            props.reportSectionDEFUNCT.definition.fetchedDataReference
          ]
        : currentReportTargetEntityDefinition?.mlSchema,
    [
      currentReportTargetEntityDefinition,
      currentReportTargetEntityDefinition?.mlSchema,
      props.fetchedDataJzodSchemaDEFUNCT,
      props.reportSectionDEFUNCT,
    ]
  );

  // log.info(
  //   "ReportSectionListDisplay currentReportTargetEntity",
  //   currentReportTargetEntity,
  //   "currentReportTargetEntityDefinition",
  //   currentReportTargetEntityDefinition,
  //   "instancesToDisplayJzodSchema",
  //   instancesToDisplayJzodSchema
  // );

  // ##############################################################################################
  // FOREIGN KEY OBJECTS FETCHING
  const foreignKeyObjectsAttributeDefinition:[string, JzodElement][] = useMemo(
    ()=> {
      if (props.tableComponentReportType !== TableComponentTypeSchema.enum.EntityInstance) {
        return [];
      }

      const foreignKeyAttributes = analyzeForeignKeyAttributes(
        currentReportTargetEntityDefinition,
        entityDefinitions,
        { includeTransitive: true, maxDepth: 5 }
      );

      return convertToLegacyFormat(foreignKeyAttributes);
    },
    [
      currentReportTargetEntityDefinition?.mlSchema.definition,
      currentReportTargetEntityDefinition?.entityUuid,
      props.tableComponentReportType,
      entityDefinitions,
    ]
  );

  const foreignKeyObjectsFetchQueryParams: SyncQueryRunnerExtractorAndParams<
    ReduxDeploymentsState
  > = useMemo(
    () => {
      const extractors: ExtractorOrCombinerRecord = Object.fromEntries(
        foreignKeyObjectsAttributeDefinition.map((e) => [
          e[1].tag?.value?.foreignKeyParams?.targetEntity + "_extractor",
          {
            extractorOrCombinerType: "extractorByEntityReturningObjectList",
            label: "extractorForForeignKey_" + e[0],
            applicationSection: getApplicationSection(
              props.application,
              e[1].tag?.value?.foreignKeyParams?.targetEntity ?? "undefined"
            ),
            parentName: "",
            parentUuid: e[1].tag?.value?.foreignKeyParams?.targetEntity??"ERROR NO TARGET ENTITY FOR ATTRIBUTE " + e[0], // does not happen because of filter in foreignKeyObjectsAttributeDefinition
          },
        ])
      );
      const runtimeTransformers: {
        [x: string]: TransformerForBuildPlusRuntime
      } = {
        ...Object.fromEntries(
          foreignKeyObjectsAttributeDefinition.map((e) => [
            e[1].tag?.value?.foreignKeyParams?.targetEntity,
            {
              transformerType: "indexListBy",
              interpolation: "runtime",
              applyTo: {
                transformerType: "getFromContext",
                interpolation: "runtime",
                referenceName: e[1].tag?.value?.foreignKeyParams?.targetEntity + "_extractor",
              },
              indexAttribute: "uuid",
            },
          ])
        ),
      };
      return getQueryRunnerParamsForReduxDeploymentsState(
        {
          queryType: "boxedQueryWithExtractorCombinerTransformer",
          application: props.application,
          pageParams: props.paramsAsdomainElements,
          queryParams: {},
          contextResults: {},
          extractors,
          runtimeTransformers
        },
        deploymentEntityStateSelectorMap
      )
    },
    [
      foreignKeyObjectsAttributeDefinition,
      props.deploymentUuid,
      props.paramsAsdomainElements,
      deploymentEntityStateSelectorMap,
    ]
  );

  const foreignKeyObjects: Record<string, EntityInstancesUuidIndex> =
  useReduxDeploymentsStateQuerySelectorForCleanedResult(
    deploymentEntityStateSelectorMap.runQuery as SyncQueryRunner<
      ReduxDeploymentsState,
      Domain2QueryReturnType<DomainElementSuccess>
    >,
    foreignKeyObjectsFetchQueryParams,
    props.applicationDeploymentMap
  );

  // // ##############################################################################################
  const onCreateFormObject = useCallback(
    async (data: any) => {
      // log.info("ReportComponent onEditFormObject called with new object value", data);

      if (props.application) {
        if (props.chosenApplicationSection == "model") {
          await domainController.handleActionFromUI(
            {
              actionType: "transactionalInstanceAction",
              application: "360fcf1f-f0d4-4f8a-9262-07886e70fa15", // miroir application
              endpoint: "1e2ef8e6-7fdf-4e3f-b291-2e6e599fb2b5",
              payload: {
                application: props.application,
                instanceAction: {
                  actionType: "createInstance",
                  application: "360fcf1f-f0d4-4f8a-9262-07886e70fa15",
                  endpoint: "ed520de4-55a9-4550-ac50-b1b713b72a89",
                  payload: {
                    application: props.application,
                    applicationSection: currentApplicationSection,
                    parentUuid: data.parentUuid,
                    objects: [
                      {
                        parentName: data.name,
                        parentUuid: data.parentUuid,
                        applicationSection: "model",
                        instances: [
                          data,
                        ],
                      },
                    ],
                  },
                },
              },
            },
            props.applicationDeploymentMap,
            currentMiroirModelEnvironment, // TODO: use model environment for current deployment
          );
        } else {
          const createAction: InstanceAction = {
            actionType: "createInstance",
            application: "360fcf1f-f0d4-4f8a-9262-07886e70fa15",
            endpoint: "ed520de4-55a9-4550-ac50-b1b713b72a89",
            payload: {
              application: props.application,
              // deploymentUuid: props.displayedDeploymentDefinition?.uuid,
              applicationSection: currentApplicationSection,
              parentUuid: data.parentUuid,
              objects: [
                {
                  parentName: data.name,
                  parentUuid: data.parentUuid,
                  applicationSection: currentApplicationSection,
                  instances: [data],
                },
              ],
            },
          };
          await domainController.handleActionFromUI(createAction, props.applicationDeploymentMap);
        }
      } else {
        throw new Error(
          "ReportComponent onSubmitOuterDialog props.displayedDeploymentDefinition is undefined.",
        );
      }
    },
    [
      domainController,
      props.application,
      props.chosenApplicationSection,
      props.tableComponentReportType,
      currentApplicationSection,
      currentModel,
    ],
  );

  // ##############################################################################################
  const onEditFormObject = useCallback(
    async (data: any): Promise<Action2VoidReturnType> => {
      // log.info("ReportComponent onEditFormObject called with new object value", data);

      if (props.application) {
        let result: Action2VoidReturnType;
        if (props.chosenApplicationSection == "model") {
          result = await domainController.handleActionFromUI(
            {
              actionType: "transactionalInstanceAction",
              application: "360fcf1f-f0d4-4f8a-9262-07886e70fa15",
              endpoint: "1e2ef8e6-7fdf-4e3f-b291-2e6e599fb2b5",
              payload: {
                application: props.application,
                instanceAction: {
                  actionType: "updateInstance",
                  application: "360fcf1f-f0d4-4f8a-9262-07886e70fa15",
                  endpoint: "ed520de4-55a9-4550-ac50-b1b713b72a89",
                  payload: {
                    application: props.application,
                    applicationSection: "model",
                    parentUuid: data.parentUuid,
                    objects: [
                      {
                        parentName: data.name,
                        parentUuid: data.parentUuid,
                        applicationSection: props.chosenApplicationSection,
                        instances: [data],
                      },
                    ],
                  },
                },
              },
            },
            props.applicationDeploymentMap,
            currentMiroirModelEnvironment // TODO: use model environment for current deployment
          );
        } else {
          const updateAction: InstanceAction = {
            actionType: "updateInstance",
            application: "360fcf1f-f0d4-4f8a-9262-07886e70fa15",
            endpoint: "ed520de4-55a9-4550-ac50-b1b713b72a89",
            payload: {
              application: props.application,
              applicationSection: props.chosenApplicationSection
                ? props.chosenApplicationSection
                : "data",
              parentUuid: data.parentUuid,
              objects: [
                {
                  parentName: data.name,
                  parentUuid: data.parentUuid,
                  applicationSection: props.chosenApplicationSection
                    ? props.chosenApplicationSection
                    : "data",
                  instances: [data],
                },
              ],
            },
          };
          result = await domainController.handleActionFromUI(updateAction, props.applicationDeploymentMap);
        }
        return result;
      } else {
        throw new Error(
          "ReportComponent onSubmitOuterDialog props.displayedDeploymentDefinition is undefined."
        );
      }
    },
    [
      domainController,
      props.deploymentUuid,
      props.chosenApplicationSection,
      props.tableComponentReportType,
      currentModel,
      props.applicationDeploymentMap,
    ]
  );


  // ##############################################################################################
  const onDeleteFormObject = useCallback(
    async (data:any) => {
      // log.info('onDeleteFormObject called with new object value',data);
      // log.info('onDeleteFormObject called with props',props);
      
      if (props.application) {
          if (!currentReportTargetEntityDefinition) {
           throw new Error(
             "ReportSectionListDisplay onDeleteFormObject no EntityDefinition found for object to delete! " +
               currentReportTargetEntity?.name,
           );
          }

          await deleteCascade(
            {
              application: props.application,
              applicationDeploymentMap: props.applicationDeploymentMap,
              applicationSection: props.chosenApplicationSection?props.chosenApplicationSection:"data" as ApplicationSection,
              deploymentUuid: props.deploymentUuid,
              domainController: domainController,
              entityDefinition: currentReportTargetEntityDefinition,
              entityDefinitions: currentModel.entityDefinitions,
              entityInstances: [data],
            }
          )
      }
    },
    [domainController, props.application, props.chosenApplicationSection, currentReportTargetEntityDefinition, currentModel]
  )

  
  // ##############################################################################################
  const onSubmitOuterDialog: (data: JsonObjectEditFormDialogInputs)=>void = useCallback(
    async (data) => {
      // log.info('ReportComponent onSubmitOuterDialog','data',data);
    
      // showSnackbar("Operation completed successfully!", "success");
      await handleAsyncAction(
        async () => { 
            const editResult = await onEditFormObject(data);

            // log.info('ReportComponent onSubmitOuterDialog done for','data',data, "editResult",editResult);

            if (editResult && editResult instanceof Action2Error) {
              log.error('ReportComponent onSubmitOuterDialog error',editResult);
            } else {
              // The form already calls onCreateFormObject, so we just need to close the dialog
              setAddObjectdialogFormIsOpen(false);
            }
         },
        "Operation completed successfully!",
        "onEditFormObject"
      );
    },
    [setAddObjectdialogFormIsOpen]
  )

  // ##############################################################################################
  // TODO: default value should be established in the main body with useMemo instead, get rid of the state / side effect
  const handleAddObjectDialogFormOpen = useCallback(
    // (label: string  | undefined, a: any) => {
      () => {
      // log.info(
      //   "handleAddObjectDialogFormOpen defined with currentReportTargetEntity",
      //   currentReportTargetEntity,
      //   "currentReportTargetEntityDefinition",
      //   currentReportTargetEntityDefinition,
      //   Object.keys(currentReportTargetEntityDefinition?.mlSchema?.definition ?? {}),
      //   Object.entries(currentReportTargetEntityDefinition?.mlSchema?.definition ?? {})
      // );
      const defaultFormValuesObject =
        currentReportTargetEntity &&
        currentReportTargetEntityDefinition &&
        currentReportTargetEntityDefinition?.mlSchema &&
        context.miroirFundamentalJzodSchema
          ? getDefaultValueForJzodSchemaWithResolutionNonHook(
              "build",
              currentReportTargetEntityDefinition?.mlSchema,
              undefined, // rootObject
              "", // rootLessListKey,
              undefined, // No need to pass currentDefaultValue here
              [], // currentPath on value is root
              false, // forceOptional
              props.application,
              props.applicationDeploymentMap,
              props.deploymentUuid,
              currentMiroirModelEnvironment,
              {}, // transformerParams
              {}, // contextResults
              deploymentEntityState,
            )
          : undefined;

      // log.info(
      //   "handleAddObjectDialogFormOpen",
      //   "called, formObject",
      //   defaultFormValuesObject,
      //   "currentReportTargetEntityDefinition",
      //   currentReportTargetEntityDefinition
      // );

      defaultFormValuesObject.parentUuid = currentReportTargetEntity?.uuid;
      defaultFormValuesObject.parentName = currentReportTargetEntity?.name;
      setdialogOuterFormObject(
        defaultFormValuesObject,
      );
      setAddObjectdialogFormIsOpen(true);
    },
    [
      setAddObjectdialogFormIsOpen,
      setdialogOuterFormObject,
      currentReportTargetEntity,
      currentReportTargetEntityDefinition,
    ]
  );

  // ##############################################################################################
  const handleAddObjectDialogTableRowFormClose = useCallback((value?: string, event?:any) => {
    event?.stopPropagation();
    // log.info('ReportSectionListDisplay handleDialogTableRowFormClose',value);
    
    setAddObjectdialogFormIsOpenCallback(false);
  },[setAddObjectdialogFormIsOpen]);


  const tableColumnDefs: { columnDefs: AutoGeneratedColumnDef[] } = useMemo(
    () =>
      (reportSectionDefinitionFromFormik?.type == "objectListReportSection"
        ? {
            columnDefs: getMDataGridColumnDefinitionsFromEntityDefinition(
              props.deploymentUuid,
              instancesToDisplayJzodSchema ?? { type: "object", definition: {} },
              reportSectionDefinitionFromFormik,
              currentReportTargetEntityDefinition
            ),
          }
        : {}) as { columnDefs: AutoGeneratedColumnDef[] },
    [
      props.deploymentUuid,
      instancesToDisplayJzodSchema,
      reportSectionDefinitionFromFormik,
      currentReportTargetEntityDefinition,
    ]
  );
  return (
    <ThemedBox className="MiroirReport-global" display="block">
      {context.showPerformanceDisplay && (
        <div>
          {" "}
          ReportSectionListDisplay renders: {navigationCount} (total: {totalCount}) times.
        </div>
      )}
      <ThemedOnScreenDebug
        label={`ReportSectionListDisplay props`}
        data={{
          props: props,
          formikValuePathAsString,
          val: formikContext.values[formikValuePathAsString],
          domainElementObjectDEFUNCT: props.domainElementObjectDEFUNCT,
          fetchedDataReference: props.reportSectionDEFUNCT?.definition.fetchedDataReference,
        }}
        initiallyUnfolded={false}
        useCodeBlock={true}
      />
      {reportSectionDefinitionFromFormik &&
      reportSectionDefinitionFromFormik.type == "objectListReportSection" &&
      currentReportTargetEntity &&
      currentReportTargetEntityDefinition ? (
        !!tableColumnDefs ? (
          <div>
            <div
              style={{ display: "flex", alignItems: "baseline", gap: "10px", marginBottom: "10px" }}
            >
              <h3 style={{ margin: 0 }}>
                {props.defaultlabel ??
                  currentReportTargetEntityDefinition?.name ??
                  "No Entity Found!"}
              </h3>
              <ThemedButton
                style={{
                  padding: "4px 8px",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                }}
                variant="secondary"
                onClick={() => {
                  handleAddObjectDialogFormOpen();
                }}
              >
                <AddBox style={{ fontSize: "1em", display: "block" }} />
              </ThemedButton>
            </div>
            {addObjectdialogFormIsOpen ? (
              <JsonObjectEditFormDialog
                showButton={false}
                valueObjectEditMode="create"
                isOpen={addObjectdialogFormIsOpen}
                isAttributes={true}
                label={props.defaultlabel ?? currentReportTargetEntityDefinition?.name}
                defaultFormValuesObject={dialogOuterFormObject}
                entityDefinition={currentReportTargetEntityDefinition}
                entityDefinitionJzodSchema={
                  currentReportTargetEntityDefinition?.mlSchema as JzodObject
                }
                foreignKeyObjects={foreignKeyObjects}
                currentApplication={props.application}
                applicationDeploymentMap={props.applicationDeploymentMap}
                currentDeploymentUuid={props.deploymentUuid}
                currentApplicationSection={props.chosenApplicationSection}
                currentAppModel={currentModel}
                currentMiroirModel={miroirMetaModel}
                addObjectdialogFormIsOpen={addObjectdialogFormIsOpen}
                onSubmit={onSubmitOuterDialog}
                onClose={handleAddObjectDialogTableRowFormClose}
                onCreateFormObject={onCreateFormObject}
                //
                // setAddObjectdialogFormIsOpen={setAddObjectdialogFormIsOpen}
                setAddObjectdialogFormIsOpen={setAddObjectdialogFormIsOpenCallback}
              />
            ) : (
              <></>
            )}
            {props.deploymentUuid ? (
              <div>
                <ThemedOnScreenDebug
                  label={`ReportSectionListDisplay formik values`}
                  data={{ formik: formikContext.values }}
                  initiallyUnfolded={false}
                  useCodeBlock={true}
                />
                <ThemedOnScreenDebug
                  label={`ReportSectionListDisplay reportSectionDefinitionFromFormik`}
                  data={reportSectionDefinitionFromFormik}
                  useCodeBlock={true}
                />
                <EntityInstanceGrid
                  type={props.tableComponentReportType}
                  styles={props.styles}
                  currentEntity={currentReportTargetEntity}
                  currentEntityDefinition={currentReportTargetEntityDefinition}
                  foreignKeyObjects={foreignKeyObjects}
                  currentModel={currentModel}
                  columnDefs={tableColumnDefs}
                  instancesToDisplay={instancesToDisplay}
                  application={props.application}
                  applicationDeploymentMap={props.applicationDeploymentMap}
                  deploymentUuid={props.deploymentUuid}
                  displayTools={true}
                  maxRows={50}
                  onRowEdit={onEditFormObject}
                  onRowDelete={onDeleteFormObject}
                  sortByAttribute={reportSectionDefinitionFromFormik.definition?.sortByAttribute}
                  paramsAsdomainElements={props.paramsAsdomainElements as any} // TODO: which is right? DomainElementObject or record<string, any>?
                  //
                  addObjectdialogFormIsOpen={addObjectdialogFormIsOpen}
                  setAddObjectdialogFormIsOpen={setAddObjectdialogFormIsOpenCallback}
                ></EntityInstanceGrid>
              </div>
            ) : (
              <div></div>
            )}
          </div>
        ) : (
          <span>No elements in the report</span>
        )
      ) : (
        <ThemedSpan style={{ color: "red" }}>
          ReportSectionListDisplay, no report or incorrect report to display:{" "}
          {JSON.stringify(reportSectionDefinitionFromFormik)}
        </ThemedSpan>
      )}
    </ThemedBox>
  );
}