import { ColDef } from "ag-grid-community";
import equal from "fast-deep-equal";
import { useCallback, useMemo, useState } from "react";
// import { SubmitHandler } from 'react-hook-form';
import { v4 as uuidv4 } from 'uuid';
import { z } from "zod";


import {
  Action2Error,
  Action2VoidReturnType,
  adminConfigurationDeploymentMiroir,
  ApplicationSection,
  applicationSection,
  ReduxDeploymentsState,
  domain2ElementObjectZodSchema,
  Domain2QueryReturnType,
  DomainControllerInterface,
  DomainElementSuccess,
  Entity,
  EntityDefinition,
  EntityInstancesUuidIndex,
  ExtendedTransformerForRuntime,
  ExtractorOrCombinerRecord,
  getApplicationSection,
  getDefaultValueForJzodSchemaWithResolutionNonHook,
  getQueryRunnerParamsForReduxDeploymentsState,
  InstanceAction,
  JzodElement,
  JzodObject,
  jzodObject,
  LoggerInterface,
  MetaModel,
  MiroirLoggerFactory,
  objectListReportSection,
  SelfApplicationDeploymentConfiguration,
  selfApplicationDeploymentConfiguration,
  SyncBoxedExtractorOrQueryRunnerMap,
  SyncQueryRunner,
  SyncQueryRunnerParams,
  type MiroirModelEnvironment,
  miroirFundamentalJzodSchema,
  type JzodSchema,
  resolvePathOnObject,
  type ReportSection
} from "miroir-core";

import AddBox from "@mui/icons-material/AddBox";
import { getMemoizedReduxDeploymentsStateSelectorForTemplateMap, getMemoizedReduxDeploymentsStateSelectorMap, ReduxStateWithUndoRedo } from "miroir-localcache-redux";
import { packageName } from "../../../../constants.js";
import { deleteCascade } from "../../scripts.js";
import {
  useDomainControllerService,
  useMiroirContextInnerFormOutput,
  useMiroirContextService,
  useSnackbar,
} from "../../MiroirContextReactProvider.js";
import { useCurrentModel, useReduxDeploymentsStateQuerySelectorForCleanedResult } from "../../ReduxHooks.js";
import { cleanLevel } from "../../constants.js";
import { getMDataGridColumnDefinitionsFromEntityDefinition } from "../../getColumnDefinitionsFromEntityAttributes.js";
import { analyzeForeignKeyAttributes, convertToLegacyFormat } from "../../utils/foreignKeyAttributeAnalyzer.js";
import { JsonObjectEditFormDialog, JsonObjectEditFormDialogInputs } from "../JsonObjectEditFormDialog.js";
import { noValue } from "../ValueObjectEditor/JzodElementEditorInterface.js";
import { EntityInstanceGrid } from "../Grids/EntityInstanceGrid.js";
import { TableComponentType, TableComponentTypeSchema } from "../Grids/EntityInstanceGridInterface.js";
import { useRenderTracker } from "../../tools/renderCountTracker.js";
import { ThemedBox, ThemedButton, ThemedSpan } from "../Themes/index.js";
import { useSelector } from "react-redux";
import type { AutoGeneratedColumnDef } from "../Grids/ValueObjectGridInterface.js";
import { useFormikContext } from "formik";


let log: LoggerInterface = console as any as LoggerInterface;
MiroirLoggerFactory.registerLoggerToStart(
  MiroirLoggerFactory.getLoggerName(packageName, cleanLevel, "ReportSectionListDisplay"), "UI",
).then((logger: LoggerInterface) => {log = logger});



// ################################################################################################
export const ReportSectionDisplayCorePropsSchema = z.object({
  styles: z.any().optional(),
  label: z.string(),
  defaultlabel: z.string().optional(),
  paramsAsdomainElements: domain2ElementObjectZodSchema,
  displayedDeploymentDefinition: selfApplicationDeploymentConfiguration.optional(),
  // 
  // domainElementObject: domainElementObject, // ugly, this is due to the need of calling hooks in the same order, irrelevant of tableComponentReportType. Should be in ReportSectionDisplayEntityInstancePropsSchema.
  domainElementObjectDEFUNCT: domain2ElementObjectZodSchema, // DEFUNCT because formikContext.values shall be used instead
  fetchedDataJzodSchemaDEFUNCT: z.record(jzodObject.optional()).optional(), // the Jzod schemas of the domainElementObject, defunct because formikContext.values shall be used instead
  formikValuePath: z.array(z.union([z.string(), z.number()])).optional(), // the path to the section inside the report definition
  // 
  reportSectionDEFUNCT: objectListReportSection, // ugly, this is due to the need of calling hooks in the same order, irrelevant of tableComponentReportType. Should be in ReportSectionDisplayEntityInstancePropsSchema.
  formikReportDefinitionPathString: z.string(), // the path inside formik values to the report definition for the current Section
  reportSectionPath: z.array(z.union([z.string(), z.number()])).optional(), // the path to the section inside the report definition
  chosenApplicationSection: applicationSection.optional(), // ugly, this is due to the need of calling hooks in the same order, irrelevant of tableComponentReportType. Should be in ReportSectionDisplayEntityInstancePropsSchema.
});

export const ReportSectionDisplayEntityInstancePropsSchema = ReportSectionDisplayCorePropsSchema.extend({
  tableComponentReportType: z.literal(TableComponentTypeSchema.enum.EntityInstance),
  chosenApplicationSection: applicationSection,
  deploymentUuid: z.string().uuid()
});

export const ReportSectionDisplayJsonArrayPropsSchema = ReportSectionDisplayCorePropsSchema.extend({
  tableComponentReportType: z.literal(TableComponentTypeSchema.enum.JSON_ARRAY),
  columnDefs: z.array(z.any()),
  rowData: z.array(z.any()),
});

// ##########################################################################################
export const ReportSectionDisplayPropsSchema = ReportSectionDisplayEntityInstancePropsSchema;
export type ReportComponentProps = z.infer<typeof ReportSectionDisplayPropsSchema>;

// ##########################################################################################
// ##########################################################################################
// ##########################################################################################
// ##########################################################################################
// ##########################################################################################
export function defaultFormValues(
  tableComponentType: TableComponentType,
  currentEntityJzodSchema: JzodObject,
  idList?:{id:number}[],
  currentMiroirEntity?: Entity,
  displayedDeploymentDefinition?: SelfApplicationDeploymentConfiguration,
):any {
  // log.info(
  //   "defaultFormValues called TableComponentType",
  //   tableComponentType,
  //   "currentMiroirEntity",
  //   currentMiroirEntity,
  //   "currentEntityJzodSchema",
  //   currentEntityJzodSchema
  // );

  let subresult
  switch (tableComponentType) {
    case "EntityInstance": {
      const attributeDefaultValue:any = {
        'uuid': uuidv4(),
        // 'id': 1,
        'parentName':currentMiroirEntity?.name,
        'parentUuid':currentMiroirEntity?.uuid,
        'conceptLevel':'Model',
        'selfApplication': displayedDeploymentDefinition?.selfApplication,
        'attributes': [],
      }
      log.info();
      
      const currentEditorAttributes = Object.entries(currentEntityJzodSchema?.definition??{}).reduce((acc,attributeJzodSchema)=>{
        let result
        if (attributeJzodSchema[1].tag?.value?.selectorParams?.targetEntity) {
          result = Object.assign({},acc,{[attributeJzodSchema[0]]:noValue})
        } else {
          if (Object.keys(attributeDefaultValue).includes(attributeJzodSchema[0])) {
            result = Object.assign({},acc,{[attributeJzodSchema[0]]:attributeDefaultValue[attributeJzodSchema[0]]})
          } else {
            result = Object.assign({},acc,{[attributeJzodSchema[0]]:''})
          }
        }
        // log.info('ReportComponent defaultFormValues',tableComponentType,'EntityInstance setting default value for attribute',a.name,':',result);
        return result;
      },{});
      log.info('defaultFormValues return',currentEditorAttributes);
      // return currentEditorAttributes;
      subresult = currentEditorAttributes;
      break;
    }
    case "JSON_ARRAY": {
      const newId = idList? idList?.reduce((acc:number,curr:{id:number}) => Math.max(curr?.id,acc),0) + 1 : 1;
      const attributeDefaultValue:any = {
        'uuid': uuidv4(),
        'id': newId,
        'conceptLevel':'Model',
        // 'attributes': [],
      }
      // TODO: CORRECT THIS IT DOES NOT WORK!!!
      const currentEditorAttributes = Object.entries(currentEntityJzodSchema).reduce((acc,currentAttribute)=>{
        const attributeName = (currentAttribute[1] as any).name
        let result
        if (Object.keys(attributeDefaultValue).includes((currentAttribute[1] as any).name)) {
          result = Object.assign({},acc,{[attributeName]:attributeDefaultValue[attributeName]})
        } else {
          result = Object.assign({},acc,{[attributeName]:''})
        }
        log.info('ReportComponent defaultFormValues',tableComponentType,'setting default value for attribute',attributeName,':',result);
        return result;
      },{});
      log.info('defaultFormValues return',currentEditorAttributes);
      subresult = currentEditorAttributes;
      // return currentEditorAttributes;
      break;
    }
    default: {
      throw new Error("defaultFormValues could not handle tableComponentType " + tableComponentType);
      break;
    }
  }
  // return {ROOT: subresult}
  return subresult;
}

// ##########################################################################################
// let prevProps = {};

// ##########################################################################################
// ##########################################################################################
// ##########################################################################################
// ##########################################################################################
export const ReportSectionListDisplay: React.FC<ReportComponentProps> = (
  props: ReportComponentProps
) => {
  // prevProps = props;
  
  // Track render counts with centralized tracker
  const currentNavigationKey = `${props.deploymentUuid}-${props.chosenApplicationSection}`;
  const { navigationCount, totalCount } = useRenderTracker("ReportSectionListDisplay", currentNavigationKey);

  const formikContext = useFormikContext<Record<string, any>>();

  // const formikValuePathAsString = props.reportSectionPath?.join("_") || "";
  const formikValuePathAsString = props.formikValuePath?.join("_") || "";

  // log.info(
  //   "ReportSectionListDisplay: formik values =",
  //   formikContext.values,
  //   "props.formikValuePath =",
  //   props.formikValuePath,
  //   "props.formikReportDefinitionPathString =",
  //   props.formikReportDefinitionPathString,
  //   "props.reportSectionPath =",
  //   props.reportSectionPath
  // );
  const reportDefinitionFromFormik: Report | undefined =
    formikContext.values &&
    props.formikReportDefinitionPathString &&
    formikContext.values[props.formikReportDefinitionPathString]
      ? formikContext.values[props.formikReportDefinitionPathString]
      : undefined;

  const reportSectionDefinitionFromFormik: ReportSection | undefined =
    reportDefinitionFromFormik &&
    props.reportSectionPath
      ? resolvePathOnObject(
          // props.reportDefinitionDEFUNCT, props.reportSectionPath ?? []
          reportDefinitionFromFormik,
          props.reportSectionPath ?? []
        )
      : undefined;

  // ##############################################################################################
  const instancesToDisplay: EntityInstancesUuidIndex = useMemo(
    () =>
      formikValuePathAsString &&
      formikContext.values &&
      formikContext.values[formikValuePathAsString]
        ? formikContext.values[formikValuePathAsString]
        : props.domainElementObjectDEFUNCT &&
          // props.domainElementObject.elementType == "object" &&
          props.reportSectionDEFUNCT?.definition.fetchedDataReference &&
          props.domainElementObjectDEFUNCT[
            props.reportSectionDEFUNCT.definition.fetchedDataReference
          ]
        ? (props.domainElementObjectDEFUNCT[
            props.reportSectionDEFUNCT.definition.fetchedDataReference
          ] as any as EntityInstancesUuidIndex)
        : {},
    [
      formikValuePathAsString,
      formikContext.values,
      props.domainElementObjectDEFUNCT,
      props.reportSectionDEFUNCT?.definition.fetchedDataReference,
    ]
  );


  // log.info('@@@@@@@@@@@@@@@@@@@@@@@ ReportSectionListDisplay',count,props === prevProps, equal(props,prevProps));
  log.info(
    "@@@@@@@@@@@@@@@@@@@@@@@ ReportSectionListDisplay",
    "navigationCount",
    navigationCount,
    "totalCount",
    totalCount,
    "instancesToDisplay",
    instancesToDisplay,
    "localReportDefinition",
    reportDefinitionFromFormik,
    "localReportSectionDefinition",
    reportSectionDefinitionFromFormik,
    "formikContext.values",
    formikContext.values,
    // "props === prevProps",
    // props === prevProps
  );
  
  // log.info('ReportSectionListDisplay props.domainElement',props.domainElement);
  // log.info('ReportSectionListDisplay props',props);

  // ##############################################################################################
  const [addObjectdialogFormIsOpen, setAddObjectdialogFormIsOpen] = useState(false);
  const setAddObjectdialogFormIsOpenCallback = useCallback((a:boolean) => {
    log.info("ReportSectionListDisplay setAddObjectdialogFormIsOpen called with",a);
    setAddObjectdialogFormIsOpen(a);
  },[setAddObjectdialogFormIsOpen]);
  const [dialogOuterFormObject, setdialogOuterFormObject] = useMiroirContextInnerFormOutput();
  // const [dialogOuterFormObject, setdialogOuterFormObject] = useState({});

  const miroirMetaModel: MetaModel = useCurrentModel(adminConfigurationDeploymentMiroir.uuid);
  const currentModel: MetaModel = useCurrentModel(props.deploymentUuid)
  const context = useMiroirContextService();
  
  const currentMiroirModelEnvironment: MiroirModelEnvironment = useMemo(() => {
    return {
      miroirFundamentalJzodSchema: context.miroirFundamentalJzodSchema?? miroirFundamentalJzodSchema as JzodSchema,
      miroirMetaModel: miroirMetaModel,
      currentModel: currentModel,
    };
  }, [
    miroirMetaModel,
    currentModel,
    context.miroirFundamentalJzodSchema,
  ]);
  // Get snackbar functionality from context
  const { showSnackbar, handleAsyncAction } = useSnackbar();
  
  // Example usage:
  // showSnackbar("Operation completed successfully!", "success");
  // handleAsyncAction(
  //   async () => { /* your async operation */ },
  //   "Operation completed successfully!",
  //   "MyAsyncOperation"
  // );

  // log.info("ReportSectionListDisplay props.deploymentUuid", props.deploymentUuid);

  const domainController: DomainControllerInterface = useDomainControllerService();

  const deploymentEntityStateSelectorMap: SyncBoxedExtractorOrQueryRunnerMap<ReduxDeploymentsState> =
      getMemoizedReduxDeploymentsStateSelectorMap();

  const deploymentEntityState: ReduxDeploymentsState = useSelector(
    (state: ReduxStateWithUndoRedo) =>
      deploymentEntityStateSelectorMap.extractState(
        state.presentModelSnapshot.current,
        () => ({}),
        currentMiroirModelEnvironment
      )
  );

  const { availableReports, entities, entityDefinitions } = useMemo(() => {
    // return displayedDeploymentDefinition &&
    return props.deploymentUuid &&
      context.deploymentUuidToReportsEntitiesDefinitionsMapping &&
      context.deploymentUuidToReportsEntitiesDefinitionsMapping[props.deploymentUuid]
      ? context.deploymentUuidToReportsEntitiesDefinitionsMapping[props.deploymentUuid][
      // context.deploymentUuidToReportsEntitiesDefinitionsMapping[displayedDeploymentDefinition?.uuid]
      // ? context.deploymentUuidToReportsEntitiesDefinitionsMapping[displayedDeploymentDefinition?.uuid][
        props.chosenApplicationSection
        ]
      : { availableReports: [], entities: [], entityDefinitions: [] };
  }, [
    props.deploymentUuid,
    // displayedDeploymentDefinition,
    context.deploymentUuidToReportsEntitiesDefinitionsMapping,
    props.chosenApplicationSection,
  ]);
    
  // log.info("ReportSectionListDisplay availableReports",availableReports);

  const currentReportTargetEntity: Entity | undefined =
    reportSectionDefinitionFromFormik?.type === "objectListReportSection" 
    // props.reportSectionDEFUNCT?.type === "objectListReportSection" 
      ? entities?.find(
          (e:Entity) =>
            e?.uuid === reportSectionDefinitionFromFormik?.definition.parentUuid
        )
      : undefined;
  const currentReportTargetEntityDefinition: EntityDefinition | undefined =
    entityDefinitions?.find((e:EntityDefinition) => e?.entityUuid === currentReportTargetEntity?.uuid);

  // TODO: AMBIGUOUS!! APPEARS ALSO IN THE Report DEFINITION. PROVIDE A DIRECT WAY TO DETERMINE THIS?
  // const currentApplicationSection = (props.section?.definition as any)["applicationSection"]??"data";
  const currentApplicationSection = props.chosenApplicationSection??"data";

  // ##############################################################################################
  const instancesToDisplayJzodSchema: JzodObject | undefined = useMemo(
    () =>
      props.fetchedDataJzodSchemaDEFUNCT &&
      props.reportSectionDEFUNCT.type == "objectListReportSection" &&
      props.reportSectionDEFUNCT.definition.fetchedDataReference &&
      props.fetchedDataJzodSchemaDEFUNCT[props.reportSectionDEFUNCT.definition.fetchedDataReference]
        ? props.fetchedDataJzodSchemaDEFUNCT[
            props.reportSectionDEFUNCT.definition.fetchedDataReference
          ]
        : currentReportTargetEntityDefinition?.jzodSchema,
    [
      currentReportTargetEntityDefinition,
      currentReportTargetEntityDefinition?.jzodSchema,
      props.fetchedDataJzodSchemaDEFUNCT,
      props.reportSectionDEFUNCT,
    ]
  );

  log.info(
    "ReportSectionListDisplay currentReportTargetEntity",
    currentReportTargetEntity,
    "currentReportTargetEntityDefinition",
    currentReportTargetEntityDefinition,
    "instancesToDisplayJzodSchema",
    instancesToDisplayJzodSchema
  );

  // const instancesToDisplayViewAttributes: string[] | undefined = useMemo(()=>
  //   currentReportTargetEntityDefinition?.viewAttributes
  //   ,[currentReportTargetEntityDefinition]
  // )

  // ##############################################################################################
  // FOREIGN KEY OBJECTS FETCHING
  const foreignKeyObjectsAttributeDefinition:[string, JzodElement][] = useMemo(
    ()=> {
      if (props.tableComponentReportType !== TableComponentTypeSchema.enum.EntityInstance) {
        return [];
      }

      const foreignKeyAttributes = analyzeForeignKeyAttributes(
        currentReportTargetEntityDefinition,
        entityDefinitions,
        { includeTransitive: true, maxDepth: 5 }
      );

      return convertToLegacyFormat(foreignKeyAttributes);
    },
    [
      currentReportTargetEntityDefinition?.jzodSchema.definition,
      currentReportTargetEntityDefinition?.entityUuid,
      props.tableComponentReportType,
      entityDefinitions,
    ]
  );

  const foreignKeyObjectsFetchQueryParams: SyncQueryRunnerParams<
    ReduxDeploymentsState
  > = useMemo(
    () => {
      const extractors: ExtractorOrCombinerRecord = Object.fromEntries(
        foreignKeyObjectsAttributeDefinition.map((e) => [
          e[1].tag?.value?.selectorParams?.targetEntity + "_extractor",
          {
            extractorOrCombinerType: "extractorByEntityReturningObjectList",
            label: "extractorForForeignKey_" + e[0],
            applicationSection: getApplicationSection(
              props.deploymentUuid,
              e[1].tag?.value?.selectorParams?.targetEntity ?? "undefined"
            ),
            parentName: "",
            parentUuid: e[1].tag?.value?.selectorParams?.targetEntity??"ERROR NO TARGET ENTITY FOR ATTRIBUTE " + e[0], // does not happen because of filter in foreignKeyObjectsAttributeDefinition
          },
        ])
      );
      const runtimeTransformers: {
        [x: string]: ExtendedTransformerForRuntime
      } = {
        ...Object.fromEntries(
          foreignKeyObjectsAttributeDefinition.map((e) => [
            e[1].tag?.value?.selectorParams?.targetEntity,
            {
              transformerType: "indexListBy",
              interpolation: "runtime",
              applyTo: {
                transformerType: "getFromContext",
                interpolation: "runtime",
                referenceName: e[1].tag?.value?.selectorParams?.targetEntity + "_extractor",
              },
              indexAttribute: "uuid",
            },
          ])
        ),
      };
      return getQueryRunnerParamsForReduxDeploymentsState(
        {
          queryType: "boxedQueryWithExtractorCombinerTransformer",
          deploymentUuid: props.deploymentUuid,
          pageParams: props.paramsAsdomainElements,
          queryParams: {},
          contextResults: {},
          extractors,
          runtimeTransformers
        },
        deploymentEntityStateSelectorMap
      )
    },
    [
      foreignKeyObjectsAttributeDefinition,
      props.deploymentUuid,
      props.paramsAsdomainElements,
      deploymentEntityStateSelectorMap,
    ]
  );

  const foreignKeyObjects: Record<string, EntityInstancesUuidIndex> =
  useReduxDeploymentsStateQuerySelectorForCleanedResult(
    deploymentEntityStateSelectorMap.runQuery as SyncQueryRunner<
      ReduxDeploymentsState,
      Domain2QueryReturnType<DomainElementSuccess>
    >,
    foreignKeyObjectsFetchQueryParams
  );

  // // ##############################################################################################
  const onCreateFormObject = useCallback(
    async (data:any) => {
      log.info('ReportComponent onEditFormObject called with new object value',data);
      
      if (props.displayedDeploymentDefinition && props.displayedDeploymentDefinition.uuid) {
        if (props.chosenApplicationSection == 'model') {
          await domainController.handleActionFromUI(
            {
              actionType: "transactionalInstanceAction",
              deploymentUuid: props.displayedDeploymentDefinition.uuid,
              instanceAction: {
                actionType: "createInstance",
                deploymentUuid: props.displayedDeploymentDefinition.uuid,
                endpoint: "ed520de4-55a9-4550-ac50-b1b713b72a89",
                payload: {
                  applicationSection: currentApplicationSection,
                  parentUuid: data.parentUuid,
                  objects: [
                    {
                      parentName: data.name,
                      parentUuid: data.parentUuid,
                      applicationSection:'model',
                      instances: [
                        // newEntity 
                        data
                      ]
                    }
                  ],
                }
              }
            },
            // props.tableComponentReportType == "EntityInstance"?currentModel:undefined
            currentMiroirModelEnvironment // TODO: use model environment for current deployment
          );
        } else {
          const createAction: InstanceAction = {
            // actionType: "instanceAction",
            actionType: "createInstance",
            deploymentUuid: props.displayedDeploymentDefinition?.uuid,
            endpoint: "ed520de4-55a9-4550-ac50-b1b713b72a89",
            payload: {
              applicationSection: currentApplicationSection,
              parentUuid: data.parentUuid,
              objects: [
                {
                  parentName: data.name,
                  parentUuid: data.parentUuid,
                  applicationSection:currentApplicationSection,
                  instances: [
                    data 
                  ],
                },
              ],
            }
          };
          await domainController.handleActionFromUI(createAction);
        }
      } else {
        throw new Error('ReportComponent onSubmitOuterDialog props.displayedDeploymentDefinition is undefined.')
      }
    },
    [domainController, props.displayedDeploymentDefinition, props.chosenApplicationSection, props.tableComponentReportType, currentApplicationSection, currentModel]
  )

  // ##############################################################################################
  const onEditFormObject = useCallback(
    async (data: any): Promise<Action2VoidReturnType> => {
      // const newEntity:EntityInstance = Object.assign({...data as EntityInstance},{attributes:dialogFormObject?dialogFormObject['attributes']:[]});
      log.info("ReportComponent onEditFormObject called with new object value", data);

      if (props.displayedDeploymentDefinition) {
        let result: Action2VoidReturnType;
        if (props.chosenApplicationSection == "model") {
          result = await domainController.handleActionFromUI(
            {
              actionType: "transactionalInstanceAction",
              deploymentUuid: props.displayedDeploymentDefinition.uuid,
              instanceAction: {
                // actionType: "instanceAction",
                actionType: "updateInstance",
                deploymentUuid: props.displayedDeploymentDefinition.uuid,
                endpoint: "ed520de4-55a9-4550-ac50-b1b713b72a89",
                payload: {
                  applicationSection: "model",
                  objects: [
                    {
                      parentName: data.name,
                      parentUuid: data.parentUuid,
                      applicationSection: props.chosenApplicationSection,
                      instances: [data],
                    },
                  ],
                },
              },
            },
            // props.tableComponentReportType == "EntityInstance" ? currentModel : undefined
            currentMiroirModelEnvironment // TODO: use model environment for current deployment
          );
        } else {
          const updateAction: InstanceAction = {
            // actionType: "instanceAction",
            actionType: "updateInstance",
            deploymentUuid: props.displayedDeploymentDefinition?.uuid,
            endpoint: "ed520de4-55a9-4550-ac50-b1b713b72a89",
            payload: {
              applicationSection: props.chosenApplicationSection
                ? props.chosenApplicationSection
                : "data",
              objects: [
                {
                  parentName: data.name,
                  parentUuid: data.parentUuid,
                  applicationSection: props.chosenApplicationSection
                    ? props.chosenApplicationSection
                    : "data",
                  instances: [data],
                },
              ],
            },
          };
          result = await domainController.handleActionFromUI(updateAction);
        }
        return result;
      } else {
        throw new Error(
          "ReportComponent onSubmitOuterDialog props.displayedDeploymentDefinition is undefined."
        );
      }
    },
    [
      domainController,
      props.displayedDeploymentDefinition,
      props.chosenApplicationSection,
      props.tableComponentReportType,
      currentModel,
    ]
  );


  // ##############################################################################################
  const onDeleteFormObject = useCallback(
    async (data:any) => {
      // const newEntity:EntityInstance = Object.assign({...data as EntityInstance},{attributes:dialogFormObject?dialogFormObject['attributes']:[]});
      log.info('onDeleteFormObject called with new object value',data);
      log.info('onDeleteFormObject called with props',props);
      
      if (props.displayedDeploymentDefinition) {
          if (!currentReportTargetEntityDefinition) {
           throw new Error("ReportSectionListDisplay onDeleteFormObject no EntityDefinition found for object to delete! " + currentReportTargetEntity?.name);
          }

          await deleteCascade(
            {
              applicationSection: props.chosenApplicationSection?props.chosenApplicationSection:"data" as ApplicationSection,
              deploymentUuid: props.displayedDeploymentDefinition?.uuid,
              domainController: domainController,
              entityDefinition: currentReportTargetEntityDefinition,
              entityDefinitions: currentModel.entityDefinitions,
              entityInstances: [data],
            }
          )
      }
    },
    [domainController, props.displayedDeploymentDefinition, props.chosenApplicationSection, currentReportTargetEntityDefinition, currentModel]
  )

  
  // ##############################################################################################
  const onSubmitOuterDialog: (data: JsonObjectEditFormDialogInputs)=>void = useCallback(
    async (data) => {
      log.info('ReportComponent onSubmitOuterDialog','data',data);
    
      // showSnackbar("Operation completed successfully!", "success");
      await handleAsyncAction(
        async () => { 
            const editResult = await onEditFormObject(data);

            log.info('ReportComponent onSubmitOuterDialog done for','data',data, "editResult",editResult);

            if (editResult && editResult instanceof Action2Error) {
              log.error('ReportComponent onSubmitOuterDialog error',editResult);
            } else {
              // The form already calls onCreateFormObject, so we just need to close the dialog
              setAddObjectdialogFormIsOpen(false);
            }
         },
        "Operation completed successfully!",
        "onEditFormObject"
      );

    // const editResult = await onEditFormObject(data);

    // log.info('ReportComponent onSubmitOuterDialog done for','data',data, "editResult",editResult);

    // if (editResult && editResult instanceof Action2Error) {
    //   log.error('ReportComponent onSubmitOuterDialog error',editResult);
    // }

    },
    [setAddObjectdialogFormIsOpen]
  )

  // ##############################################################################################
  const handleAddObjectDialogFormOpen = useCallback(
    // (label: string  | undefined, a: any) => {
    () => {
      const defaultFormValuesObject =
        currentReportTargetEntity &&
        currentReportTargetEntityDefinition &&
        currentReportTargetEntityDefinition?.jzodSchema &&
        context.miroirFundamentalJzodSchema
          ? getDefaultValueForJzodSchemaWithResolutionNonHook(
              "build",
              currentReportTargetEntityDefinition?.jzodSchema,
              undefined, // rootObject
              "", // rootLessListKey,
              undefined, // No need to pass currentDefaultValue here
              [], // currentPath on value is root
              false, // forceOptional
              props.deploymentUuid,
              currentMiroirModelEnvironment,
              {}, // transformerParams
              {}, // contextResults
              deploymentEntityState,
            )
          : undefined;

      log.info(
        "handleAddObjectDialogFormOpen",
        "called, formObject",
        defaultFormValuesObject,
        "currentReportTargetEntityDefinition",
        currentReportTargetEntityDefinition
      );

      setdialogOuterFormObject(defaultFormValuesObject);
      setAddObjectdialogFormIsOpen(true);
    },
    [
      setAddObjectdialogFormIsOpen,
      setdialogOuterFormObject,
      currentReportTargetEntity,
      currentReportTargetEntityDefinition,
    ]
  );

  // ##############################################################################################
  const handleAddObjectDialogTableRowFormClose = useCallback((value?: string, event?:any) => {
    event?.stopPropagation();
    log.info('ReportSectionListDisplay handleDialogTableRowFormClose',value);
    
    // setAddObjectdialogFormIsOpen(false);
    setAddObjectdialogFormIsOpenCallback(false);
  },[setAddObjectdialogFormIsOpen]);


  // log.info("instancesToDisplay",instancesToDisplay);
  // log.info("currentApplicationSection",currentApplicationSection);
  // log.info("props.domainElementObject",props.domainElementObject);
  // log.info("props.currentMiroirEntity",currentReportTargetEntity);
  // log.info("tableColumnDefs",tableColumnDefs);
  const tableColumnDefs: { columnDefs: AutoGeneratedColumnDef[] } = useMemo(
    () =>
      ({
        columnDefs: getMDataGridColumnDefinitionsFromEntityDefinition(
          props.deploymentUuid,
          instancesToDisplayJzodSchema ?? { type: "object", definition: {} },
          currentReportTargetEntityDefinition
        ),
      } as { columnDefs: AutoGeneratedColumnDef[] }),
    [
      props.deploymentUuid,
      instancesToDisplayJzodSchema,
      currentReportTargetEntityDefinition,
    ]
  );
  // forcing global rerender of grid whenever the reportSectionDefinitionFromFormik changes
  // const entityInstanceGrid = useMemo(() => {
  //   return props.displayedDeploymentDefinition && reportSectionDefinitionFromFormik &&
  //     reportSectionDefinitionFromFormik.type == "objectListReportSection" &&
  //     currentReportTargetEntity &&
  //     currentReportTargetEntityDefinition?(
  //     <EntityInstanceGrid
  //       key={JSON.stringify(reportSectionDefinitionFromFormik)}
  //       type={props.tableComponentReportType}
  //       displayedDeploymentDefinition={props.displayedDeploymentDefinition}
  //       styles={props.styles}
  //       currentEntity={currentReportTargetEntity}
  //       currentEntityDefinition={currentReportTargetEntityDefinition}
  //       foreignKeyObjects={foreignKeyObjects}
  //       currentModel={currentModel}
  //       columnDefs={tableColumnDefs}
  //       instancesToDisplay={instancesToDisplay}
  //       deploymentUuid={props.deploymentUuid}
  //       displayTools={true}
  //       maxRows={50}
  //       onRowEdit={onEditFormObject}
  //       onRowDelete={onDeleteFormObject}
  //       // sortByAttribute={props.reportSectionDEFUNCT.definition.sortByAttribute}
  //       sortByAttribute={reportSectionDefinitionFromFormik.definition?.sortByAttribute}
  //       paramsAsdomainElements={props.paramsAsdomainElements as any} // TODO: which is right? DomainElementObject or record<string, any>?
  //     ></EntityInstanceGrid>
  //   ): (<></>);
  // }, [
  //   reportSectionDefinitionFromFormik,
  //   reportSectionDefinitionFromFormik?.definition,
  //   props.tableComponentReportType,
  //   props.displayedDeploymentDefinition,
  //   props.styles,
  //   currentReportTargetEntity,
  //   currentReportTargetEntityDefinition,
  //   foreignKeyObjects,
  //   currentModel,
  //   tableColumnDefs,
  //   instancesToDisplay,
  //   props.deploymentUuid,
  //   onEditFormObject,
  //   onDeleteFormObject,
  //   props.paramsAsdomainElements,
  // ]);
  return (
    <ThemedBox className="MiroirReport-global" display="block">
      {context.showPerformanceDisplay && (
        <div>
          {" "}
          ReportSectionListDisplay renders: {navigationCount} (total: {totalCount}) times.
        </div>
      )}
      {/* labelll:{props.select?.label?<span>{props.select?.label}</span>:<></>} */}
      {reportSectionDefinitionFromFormik &&
      reportSectionDefinitionFromFormik.type == "objectListReportSection" &&
      currentReportTargetEntity &&
      currentReportTargetEntityDefinition ? (
        !!tableColumnDefs ? (
          // columnDefs?.length > 0
          // <div style={{ display: "flex", flexDirection: "column", alignItems: "center" }}>
          <div>
            <div
              style={{ display: "flex", alignItems: "baseline", gap: "10px", marginBottom: "10px" }}
            >
              <h3 style={{ margin: 0 }}>
                {props.defaultlabel ??
                  currentReportTargetEntityDefinition?.name ??
                  "No Entity Found!"}
              </h3>
              <ThemedButton
                style={{
                  padding: "4px 8px",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                }}
                variant="secondary"
                onClick={() => {
                  handleAddObjectDialogFormOpen();
                }}
              >
                <AddBox style={{ fontSize: "1em", display: "block" }} />
              </ThemedButton>
            </div>
            {addObjectdialogFormIsOpen ? (
              <JsonObjectEditFormDialog
                showButton={false}
                isOpen={addObjectdialogFormIsOpen}
                isAttributes={true}
                label={props.defaultlabel ?? currentReportTargetEntityDefinition?.name}
                defaultFormValuesObject={dialogOuterFormObject}
                entityDefinition={currentReportTargetEntityDefinition}
                entityDefinitionJzodSchema={
                  currentReportTargetEntityDefinition?.jzodSchema as JzodObject
                }
                foreignKeyObjects={foreignKeyObjects}
                currentDeploymentUuid={props.displayedDeploymentDefinition?.uuid}
                currentApplicationSection={props.chosenApplicationSection}
                currentAppModel={currentModel}
                currentMiroirModel={miroirMetaModel}
                addObjectdialogFormIsOpen={addObjectdialogFormIsOpen}
                onSubmit={onSubmitOuterDialog}
                onClose={handleAddObjectDialogTableRowFormClose}
                onCreateFormObject={onCreateFormObject}
                //
                // setAddObjectdialogFormIsOpen={setAddObjectdialogFormIsOpen}
                setAddObjectdialogFormIsOpen={setAddObjectdialogFormIsOpenCallback}
              />
            ) : (
              <></>
            )}
            {props.displayedDeploymentDefinition ? (
              <div>
                {/* <div>instancesToDisplay: {JSON.stringify(instancesToDisplay)}</div> */}
                {/* {entityInstanceGrid} */}
                <EntityInstanceGrid
                  type={props.tableComponentReportType}
                  displayedDeploymentDefinition={props.displayedDeploymentDefinition}
                  styles={props.styles}
                  currentEntity={currentReportTargetEntity}
                  currentEntityDefinition={currentReportTargetEntityDefinition}
                  foreignKeyObjects={foreignKeyObjects}
                  currentModel={currentModel}
                  columnDefs={tableColumnDefs}
                  instancesToDisplay={instancesToDisplay}
                  deploymentUuid={props.deploymentUuid}
                  displayTools={true}
                  maxRows={50}
                  onRowEdit={onEditFormObject}
                  onRowDelete={onDeleteFormObject}
                  // sortByAttribute={props.reportSectionDEFUNCT.definition.sortByAttribute}
                  sortByAttribute={reportSectionDefinitionFromFormik.definition?.sortByAttribute}
                  paramsAsdomainElements={props.paramsAsdomainElements as any} // TODO: which is right? DomainElementObject or record<string, any>?
                  //
                  addObjectdialogFormIsOpen={addObjectdialogFormIsOpen}
                  setAddObjectdialogFormIsOpen={setAddObjectdialogFormIsOpenCallback}
                ></EntityInstanceGrid>
              </div>
            ) : (
              <div></div>
            )}
          </div>
        ) : (
          <span>No elements in the report</span>
        )
      ) : (
        <ThemedSpan style={{ color: "red" }}>
          ReportSectionListDisplay, no report or incorrect report to display:{" "}
          {/* {JSON.stringify(props.reportSectionDEFUNCT)} */}
          {JSON.stringify(reportSectionDefinitionFromFormik)}
        </ThemedSpan>
      )}
    </ThemedBox>
  );
  // } else { // props.tableComponentReportType == "JSON_ARRAY"
  //   // const existingRows = dialogOuterFormObject && dialogOuterFormObject['attributes']?dialogOuterFormObject['attributes']:props.rowData
  //   // log.info('ReportComponent display report for',props.label,props.tableComponentReportType,'dialogFormObject',dialogOuterFormObject);
    
  //   return (
  //     <div>
  //       {/* <span>rendered ReportSectionListDisplay: {count} times.</span> */}
  //       {/* <JsonObjectEditFormDialog
  //         showButton={true}
  //         jzodSchema={entityDefinitionEntityDefinition.jzodSchema as JzodObject}
  //         initialValuesObject={defaultFormValues(props.tableComponentReportType, entityDefinitionEntityDefinition.jzodSchema as JzodObject, [], existingRows)}
  //         label='InnerDialog'
  //         onSubmit={onSubmitInnerFormDialog}
  //       />
  //       <EntityInstanceGrid
  //         type="JSON_ARRAY"
  //         styles={props.styles}
  //         columnDefs={props.columnDefs}
  //         rowData={existingRows}
  //         displayTools={true}
  //       >
  //       </EntityInstanceGrid> */}
  //     </div>
  //   );
  // }
}