// Auto-generated stub declarations for tsup consumers (dts: false).
// Keeps miroir-core DTS builds from inferring widened JSON types.

export declare const entityEndpointVersion: any;
export declare const entityEntity: any;
export declare const entityEntityVersion: any;
/** @deprecated Use entityEntityVersion */
export declare const entityEntityDefinition: any;
export declare const entityJzodSchema: any;
export declare const entityMenu: any;
export declare const entityReport: any;
export declare const entityRunner: any;
export declare const entitySelfApplication: any;
export declare const entitySelfApplicationVersion: any;
export declare const entitySelfApplicationModelBranch: any;
export declare const entityQueryVersion: any;
/** #227 — historical QueryVersion Entity (freeze snapshots). */
export declare const entityHistoricalQueryVersion: any;
export declare const entityApplicationVersionCrossQueryVersion: any;
/** #227 — historical ReportVersion Entity (freeze snapshots). */
export declare const entityHistoricalReportVersion: any;
export declare const entityApplicationVersionCrossReportVersion: any;
export declare const entityHistoricalMenuVersion: any;
export declare const entityApplicationVersionCrossMenuVersion: any;
export declare const entityHistoricalEndpointVersion: any;
export declare const entityApplicationVersionCrossEndpointVersion: any;
export declare const entityTest: any;
export declare const entityTransformerDefinition: any;
export declare const entityMiroirTest: any;
export declare const entityBlob: any;
export declare const entityCommit: any;
export declare const entityApplicationVersionCrossEntityVersion: any;
/** @deprecated Use entityApplicationVersionCrossEntityVersion */
export declare const entityApplicationVersionCrossEntityDefinition: any;
export declare const entityApplicationEvolutionTrace: any;
export declare const entityApplicationEvolutionTraceEvent: any;
export declare const entityVersionEndpoint: any;
/** @deprecated Use entityVersionEndpoint */
export declare const entityDefinitionEndpoint: any;
export declare const entityVersionEntity: any;
/** @deprecated Use entityVersionEntity */
export declare const entityDefinitionEntity: any;
export declare const entityVersionEntityVersion: any;
/** @deprecated Use entityVersionEntityVersion */
export declare const entityDefinitionEntityDefinition: any;
export declare const entityVersionMenu: any;
/** @deprecated Use entityVersionMenu */
export declare const entityDefinitionMenu: any;
export declare const entityVersionJzodSchema: any;
/** @deprecated Use entityVersionJzodSchema */
export declare const entityDefinitionJzodSchema: any;
export declare const entityVersionQuery: any;
/** @deprecated Use entityVersionQuery */
export declare const entityDefinitionQuery: any;
export declare const entityVersionReport: any;
/** @deprecated Use entityVersionReport */
export declare const entityDefinitionReport: any;
export declare const entityVersionRunner: any;
/** @deprecated Use entityVersionRunner */
export declare const entityDefinitionRunner: any;
export declare const entityVersionSelfApplication: any;
/** @deprecated Use entityVersionSelfApplication */
export declare const entityDefinitionSelfApplication: any;
export declare const entityVersionSelfApplicationDeploymentConfiguration: any;
/** @deprecated Use entityVersionSelfApplicationDeploymentConfiguration */
export declare const entityDefinitionSelfApplicationDeploymentConfiguration: any;
export declare const entityVersionSelfApplicationVersion: any;
/** @deprecated Use entityVersionSelfApplicationVersion */
export declare const entityDefinitionSelfApplicationVersion: any;
export declare const entityVersionSelfApplicationModelBranch: any;
/** @deprecated Use entityVersionSelfApplicationModelBranch */
export declare const entityDefinitionSelfApplicationModelBranch: any;
export declare const entityVersionTest: any;
/** @deprecated Use entityVersionTest */
export declare const entityDefinitionTest: any;
export declare const entityVersionMiroirTest: any;
/** @deprecated Use entityVersionMiroirTest */
export declare const entityDefinitionMiroirTest: any;
export declare const entityVersionStoreBasedConfiguration: any;
/** @deprecated Use entityVersionStoreBasedConfiguration */
export declare const entityDefinitionStoreBasedConfiguration: any;
export declare const entityVersionTransformerDefinition: any;
/** @deprecated Use entityVersionTransformerDefinition */
export declare const entityDefinitionTransformerDefinition: any;
export declare const entityVersionCommit: any;
/** @deprecated Use entityVersionCommit */
export declare const entityDefinitionCommit: any;
export declare const entityVersionQueryVersionV1: any;
/** #227 — bootstrap EntityVersion row for historical QueryVersion Entity. */
export declare const entityVersionHistoricalQueryVersion: any;
export declare const entityVersionApplicationVersionCrossQueryVersion: any;
/** #227 — bootstrap EntityVersion row for historical ReportVersion Entity. */
export declare const entityVersionHistoricalReportVersion: any;
export declare const entityVersionApplicationVersionCrossReportVersion: any;
export declare const entityVersionHistoricalMenuVersion: any;
export declare const entityVersionApplicationVersionCrossMenuVersion: any;
export declare const entityVersionHistoricalEndpointVersion: any;
export declare const entityVersionApplicationVersionCrossEndpointVersion: any;
/** @deprecated Use entityVersionQueryVersionV1 */
export declare const entityDefinitionQueryVersionV1: any;
export declare const entityVersionBlob: any;
/** @deprecated Use entityVersionBlob */
export declare const entityDefinitionBlob: any;
export declare const entityVersionApplicationVersionCrossEntityVersion: any;
/** @deprecated Use entityVersionApplicationVersionCrossEntityVersion */
export declare const entityDefinitionApplicationVersionCrossEntityDefinition: any;
export declare const entityVersionApplicationEvolutionTrace: any;
/** @deprecated Use entityVersionApplicationEvolutionTrace */
export declare const entityDefinitionApplicationEvolutionTrace: any;
export declare const entityVersionApplicationEvolutionTraceEvent: any;
/** @deprecated Use entityVersionApplicationEvolutionTraceEvent */
export declare const entityDefinitionApplicationEvolutionTraceEvent: any;
export declare const entityApplicationVersionCrossEntityDeployment: any;
export declare const entityVersionApplicationVersionCrossEntityDeployment: any;
/** @deprecated Use entityVersionApplicationVersionCrossEntityDeployment */
export declare const entityDefinitionApplicationVersionCrossEntityDeployment: any;
export declare const entityVersionSelfApplicationV1: any;
/** @deprecated Use entityVersionSelfApplicationV1 */
export declare const entityDefinitionSelfApplicationV1: any;
export declare const entityVersionSelfApplicationVersionV1: any;
/** @deprecated Use entityVersionSelfApplicationVersionV1 */
export declare const entityDefinitionSelfApplicationVersionV1: any;
export declare const entityVersionEntityVersionV1: any;
/** @deprecated Use entityVersionEntityVersionV1 */
export declare const entityDefinitionEntityDefinitionV1: any;
export declare const entityVersionJzodSchemaV1: any;
/** @deprecated Use entityVersionJzodSchemaV1 */
export declare const entityDefinitionJzodSchemaV1: any;
export declare const entityVersionReportV1: any;
/** @deprecated Use entityVersionReportV1 */
export declare const entityDefinitionReportV1: any;
export declare const modelEndpointVersionV1: any;
export declare const selfApplicationMiroir: any;
export declare const selfApplicationDeploymentMiroir: any;
export declare const selfApplicationStoreBasedConfigurationMiroir: any;
export declare const selfApplicationModelBranchMiroirMasterBranch: any;
export declare const selfApplicationVersionInitialMiroirVersion: any;
export declare const reportApplicationList: any;
export declare const reportApplicationDeploymentConfigurationList: any;
export declare const reportApplicationModelBranchList: any;
export declare const reportApplicationVersionList: any;
export declare const reportApplicationVersionDetails: any;
export declare const reportVersioning: any;
export declare const reportConfigurationList: any;
export declare const reportEndpointVersionList: any;
export declare const reportEntityVersionList: any;
/** @deprecated Use reportEntityVersionList */
export declare const reportEntityDefinitionList: any;
export declare const reportEntityVersionDetails: any;
/** @deprecated Use reportEntityVersionDetails */
export declare const reportEntityDefinitionDetails: any;
export declare const reportEntityList: any;
export declare const reportEntityDetails: any;
export declare const reportMenuList: any;
export declare const reportJzodSchemaList: any;
export declare const reportQueryList: any;
export declare const reportQueryDetails: any;
export declare const reportReportList: any;
export declare const reportRunnerList: any;
export declare const reportRunnerDetails: any;
export declare const reportReportDetails: any;
export declare const reportTestList: any;
export declare const reportTestDetails: any;
export declare const reportMiroirTestList: any;
export declare const reportMiroirTestDetails: any;
export declare const reportEndpointDetails: any;
export declare const reportMenuDetails: any;
export declare const reportMiroirQueryList: any;
export declare const reportBlobDetails: any;
export declare const reportTransformerDetails: any;
export declare const reportCommitList: any;
export declare const reportApplicationEvolutionTraceList: any;
export declare const reportApplicationEvolutionTraceHistory: any;
export declare const reportApplicationEvolutionTraceDetails: any;
export declare const reportMiroirDocumentation: any;
export declare const reportBlobList: any;
export declare const reportSelfApplicationDetails: any;
export declare const reportTransformerList: any;
export declare const reportMiroirWebAppOrDesktopHome: any;
export declare const reportMiroirSandboxHome: any;
export declare const reportMiroirRunners: any;
export declare const applicationEndpointV1: any;
export declare const instanceEndpointV1: any;
export declare const modelEndpointV1: any;
export declare const domainEndpointVersionV1: any;
export declare const testEndpointVersionV1: any;
export declare const storeManagementEndpoint: any;
export declare const instanceEndpointVersionV1: any;
export declare const undoRedoEndpointVersionV1: any;
export declare const localCacheEndpointVersionV1: any;
export declare const queryEndpointVersionV1: any;
export declare const persistenceEndpointVersionV1: any;
export declare const menuEndpointV1: any;
export declare const deploymentEndpointV1: any;
export declare const queryVersionBundleProducerV1: any;
export declare const queryVersionEntityList: any;
export declare const menuDefaultMiroir: any;
export declare const miroirJzodSchemaBootstrap: any;
export declare const transformerJzodSchema: any;
export declare const jzodSchemajzodMiroirBootstrapSchema: any;
export declare const test_createEntityAndReportFromSpreadsheetAndUpdateMenu: any;
export declare const miroirTest_adminTransformers: any;
export declare const miroirTest_alterObject: any;
export declare const miroirTest_ansiColumnsToJzodSchema: any;
export declare const miroirTest_buildAnyKeyMap: any;
export declare const miroirTest_defaultValueForMLSchema: any;
export declare const miroirTest_EntityPrimaryKey: any;
export declare const miroirTest_getAttributeTypesFromJzodSchema: any;
export declare const miroirTest_jzodObjectFlatten: any;
export declare const miroirTest_jzodReferencesGraphConnectedComponents: any;
export declare const miroirTest_JzodSchemaReferencesList: any;
export declare const miroirTest_JzodSchemaReferencesSet: any;
export declare const miroirTest_jzodToCopilotKitParameter: any;
export declare const miroirTest_jzodToJsonSchema: any;
export declare const miroirTest_jzodToJzod_Summary: any;
export declare const miroirTest_jzodTransitiveDependencySet: any;
export declare const miroirTest_jzodTypeCheck: any;
export declare const miroirTest_jzodUnion_RecursiveUnfold: any;
export declare const miroirTest_jzodUnionResolvedTypeForArray: any;
export declare const miroirTest_jzodUnionResolvedTypeForObject: any;
export declare const miroirTest_localizeJzodSchemaReferenceContext: any;
export declare const miroirTest_menu: any;
export declare const miroirTest_mergePositionBased: any;
export declare const miroirTest_metaModelTransformers: any;
export declare const miroirTest_miroirCoreTransformers: any;
export declare const miroirTest_modelUpdates: any;
export declare const miroirTest_mustache: any;
export declare const miroirTest_pilot_transformer_plus: any;
export declare const miroirTest_queries_library: any;
export declare const miroirTest_resolveConditionalSchema: any;
export declare const miroirTest_resolveQueryTemplates: any;
export declare const miroirTest_resolveSchemaReferenceInContext: any;
export declare const miroirTest_selectUnionBranchFromDiscriminator: any;
export declare const miroirTest_tools: any;
export declare const miroirTest_unfoldSchemaOnce: any;
export declare const miroirTest_domain_controller_data_crud: any;
export declare const miroirTest_domain_controller_model_crud: any;
export declare const miroirTest_domain_controller_composite_pk_crud: any;
export declare const miroirTest_domain_controller_non_uuid_pk_model_crud: any;
export declare const miroirTest_domain_controller_non_uuid_pk_data_crud: any;
export declare const miroirTest_domain_controller_no_parent_uuid_crud: any;
export declare const miroirTest_domain_controller_model_undo_redo: any;
export declare const miroirTest_domain_controller_application_version_freeze: any;
export declare const miroirTest_evolutionTraceWP1: any;
export declare const miroirTest_runner_create_entity: any;
export declare const miroirTest_runner_drop_entity: any;
export declare const miroirTest_runner_freeze_application_version: any;
export declare const miroirTest_unionArrayChoices: any;
export declare const miroirTest_unionObjectChoices: any;
export declare const transformerMenuV1: any;
export declare const transformer_spreadSheetToJzodSchema_json: any;
export declare const transformer_ifThenElse_json: any;
export declare const transformer_boolExpr_json: any;
export declare const transformer_plus_json: any;
export declare const transformer_case_json: any;
export declare const transformer_returnValue_json: any;
export declare const transformer_constantAsExtractor_json: any;
export declare const transformer_getFromContext_json: any;
export declare const transformer_aggregate_json: any;
export declare const transformer_dataflowObject_json: any;
export declare const transformer_createObject_json: any;
export declare const transformer_pickFromList_json: any;
export declare const transformer_indexListBy_json: any;
export declare const transformer_listReducerToSpreadObject_json: any;
export declare const transformer_mapList_json: any;
export declare const transformer_mustacheStringTemplate_json: any;
export declare const transformer_generateUuid_json: any;
export declare const transformer_objectFullTemplate_json: any;
export declare const transformer_mergeIntoObject_json: any;
export declare const transformer_accessDynamicPath_json: any;
export declare const transformer_getObjectEntries_json: any;
export declare const transformer_getObjectValues_json: any;
export declare const transformer_getFromParameters_json: any;
export declare const transformer_getUniqueValues_json: any;
export declare const transformer_getActiveDeployment_json: any;
export declare const transformer_duplicateApplicationModel_json: any;
export declare const transformer_ansiColumnsToJzodSchema_json: any;
export declare const transformer_concatLists_json: any;
export declare const transformer_filterList_json: any;
export declare const transformer_find_json: any;
export declare const transformer_object_fromEntries_json: any;
export declare const transformer_sortList_json: any;
export declare const transformer_listLength_json: any;
export declare const transformer_stringOp_json: any;
export declare const transformer_currentTimestamp_json: any;
export declare const transformer_currentDate_json: any;
export declare const transformer_numericOp_json: any;
export declare const transformer_menu_addItem_json: any;
export declare const transformer_defaultValueForMLSchema_json: any;
export declare const transformer_jzodTypeCheck_json: any;
export declare const transformer_resolveConditionalSchema_json: any;
export declare const transformer_resolveSchemaReferenceInContext_json: any;
export declare const transformer_unfoldSchemaOnce_json: any;
export declare const transformer_metaModel_entityDefinition_extractAttributes_json: any;
export declare const runnerDeployApplication: any;
export declare const runnerDropApplication: any;
export declare const runnerDropEntity: any;
export declare const runnerCreateEntity: any;
export declare const runnerFreezeApplicationVersion: any;
export declare const blobMiroirLogo: any;
export declare const applicationVersionInitialMiroirVersionCrossEntityDefinitionEntity: any;
export declare const applicationVersionInitialMiroirVersionCrossEntityVersionEntityVersion: any;
/** @deprecated Use applicationVersionInitialMiroirVersionCrossEntityVersionEntityVersion */
export declare const applicationVersionInitialMiroirVersionCrossEntityDefinitionEntityDefinition: any;
export declare const applicationVersionInitialMiroirVersionCrossEntityDefinitionApplicationModelBranch: any;
export declare const applicationVersionInitialMiroirVersionCrossEntityDefinitionApplicationVersion: any;
export declare const applicationVersionInitialMiroirVersionCrossEntityDefinitionStoreBasedConfiguration: any;
export declare const applicationVersionInitialMiroirVersionCrossEntityDefinitionApplication: any;
export declare const applicationVersionInitialMiroirVersionCrossEntityDefinitionReport: any;
export declare const commitInitialCommit: any;
export declare const entityTheme: any;
export declare const defaultStoredMiroirTheme: any;
export declare const darkStoredMiroirTheme: any;
export declare const compactStoredMiroirTheme: any;
export declare const materialStoredMiroirTheme: any;
export declare const entityVersionTheme: any;
/** @deprecated Use entityVersionTheme */
export declare const entityDefinitionTheme: any;
import type { MetaModel } from "miroir-core";

export declare const defaultMiroirMetaModel: MetaModel;
export declare const RUNNER_MIROIR_ENTITY_RUNNER_REGISTRY: any;
export declare const miroirThemeSchemaJson: any;
export declare const tableThemeSchemaJson: any;
export declare const defaultMiroirMetaModelEntityNameToAttributeName: any;
