import { ColDef } from "ag-grid-community";


import {
  Entity,
  JzodElement,
  LoggerInterface,
  MiroirLoggerFactory,
  type ObjectListReportSection,
} from "miroir-core";

import { packageName } from "../../constants.js";
import { EntityInstanceCellRenderer } from "./components/Grids/EntityInstanceCellRenderer.js";
import { TableComponentRow } from "./components/Grids/EntityInstanceGridInterface.js";
import { GenderCellEditor } from "./components/Grids/GenderCellEditor.js";
import GenderCellRenderer from "./components/Grids/GenderCellRenderer.js";
import type { AutoGeneratedColumnDef } from "./components/Grids/ValueObjectGridInterface.js";
import {
  DefaultCellRenderer,
} from "./components/SelectEntityInstanceEditor.js";
import { cleanLevel } from "./constants.js";

const _miroirLoggerName = MiroirLoggerFactory.getLoggerName(packageName, cleanLevel, "getColumnDefinitionsFromEntityAttributes");
let log: LoggerInterface = MiroirLoggerFactory.getPreStartLogger(_miroirLoggerName);
MiroirLoggerFactory.registerLoggerToStart(_miroirLoggerName, "UI",
).then((logger: LoggerInterface) => {log = logger});

// ################################################################################################
export function getMDataGridColumnDefinition(
  deploymentUuid: string, // prop drilling
  name: string,
  mlSchema: JzodElement,
  reportSectionDefinition: ObjectListReportSection | undefined,
  entity?: Entity | undefined,
): AutoGeneratedColumnDef {
  const sortParams =
    reportSectionDefinition?.definition.sortByAttribute === name
      ? { sort: reportSectionDefinition.definition.sortOrder ?? "asc", sortIndex: 0 }
      : {};

  if (mlSchema?.tag?.value?.foreignKeyParams?.targetEntity) {
    const result: AutoGeneratedColumnDef =  {
      field: name,
      ...sortParams,
      headerName: mlSchema.tag?.value?.defaultLabel ? mlSchema.tag?.value?.defaultLabel : name,
      cellRenderer: EntityInstanceCellRenderer,
      cellRendererParams: {
        deploymentUuid,
        isFK: true,
        entityUuid: mlSchema?.tag?.value?.foreignKeyParams?.targetEntity,
        entity,
      },
    };

    return result;
  }

  switch (name) {
    case "uuid":
    case "name": {

      return {
        field: name,
        headerName: mlSchema.tag?.value?.defaultLabel ? mlSchema.tag?.value?.defaultLabel : name,
        ...sortParams,
        cellRenderer: EntityInstanceCellRenderer,
        cellRendererParams: {
          deploymentUuid,
          entityUuid: entity?.uuid,
          entity,
        },
      };
      break;
    }
    case "gender": { // TODO: not used anymore, come up with another similar example 
      return {
        field: "gender",
        ...sortParams,
        headerName: mlSchema.tag?.value?.defaultLabel ? mlSchema.tag?.value?.defaultLabel : name,
        cellRenderer: GenderCellRenderer,
        cellEditor: GenderCellEditor,
        cellEditorPopup: true,
        editable: true,
        cellRendererParams: {
          deploymentUuid,
          entityUuid: entity?.uuid,
          entity,
        },
      };
      break;
    }
    case "conceptLevel": { // TODO: not used anymore, come up with a general solution for enums
      return {
        field: name,
        ...sortParams,
        headerName: mlSchema.tag?.value?.defaultLabel ? mlSchema.tag?.value?.defaultLabel : name,
        cellRendererParams: {
          deploymentUuid,
          entityUuid: entity?.uuid,
          entity,
        },
      };
    }
    default: {
      if (!mlSchema) {
        log.error(
          "getMDataGridColumnDefinition: mlSchema is undefined for name",
          name,
          "entity",
          entity
        );
      }
      return {
        field: name,
        ...sortParams,
        headerName: mlSchema.tag?.value?.defaultLabel
          ? mlSchema.tag?.value?.defaultLabel
          : name,
        cellRenderer: DefaultCellRenderer,
        cellRendererParams: {
          columnName: name,
          deploymentUuid,
          entityUuid: entity?.uuid,
          entity,
        },
      };
      break;
    }
  }
}

// ################################################################################################
export function getMDataGridColumnDefinitionsFromEntity(
  deploymentUuid: string,
  mlSchema: JzodElement | undefined,
  reportSectionDefinition: ObjectListReportSection | undefined,
  entity?: Entity | undefined,
  rowData?: TableComponentRow[],
  availableWidth?: number
): ColDef<any>[] {
  log.info(
    "getMDataGridColumnDefinitionsFromEntity",
    "deploymentUuid",
    deploymentUuid,
    "mlSchema",
    mlSchema,
    "viewAttributes",
    entity?.viewAttributes,
    "entity",
    entity,
    "reportSectionDefinition",
    reportSectionDefinition
  );
  
  let columnDefs: AutoGeneratedColumnDef[] = [];
  
  switch (mlSchema?.type) {
    case "object":
      {
        const schemaKeys = Object.keys(mlSchema.definition)
        if (entity?.viewAttributes) {
          columnDefs = entity.viewAttributes
            .filter((a: string) => [a, schemaKeys.find((b) => b == a)])
            .map((a: string) =>
              getMDataGridColumnDefinition(
                deploymentUuid,
                a,
                mlSchema.definition[a],
                reportSectionDefinition,
                entity,
              )
            );
        } else {
          columnDefs = Object.entries(mlSchema.definition ? mlSchema.definition : {})
            .map((e: [string, any]) =>
              getMDataGridColumnDefinition(deploymentUuid, e[0], e[1], reportSectionDefinition, entity)
            );
        }
      }
      break;
    default: {
      columnDefs = [];
      break;
    }
  }

  return columnDefs;
}
