import { ColDef } from "ag-grid-community";


import {
  EntityDefinition,
  JzodElement,
  LoggerInterface,
  MiroirLoggerFactory,
  type ObjectListReportSection,
  type ReportSection
} from "miroir-core";

import { packageName } from "../../constants.js";
import { EntityInstanceCellRenderer } from "./components/Grids/EntityInstanceCellRenderer.js";
import { TableComponentRow } from "./components/Grids/EntityInstanceGridInterface.js";
import { GenderCellEditor } from "./components/Grids/GenderCellEditor.js";
import GenderCellRenderer from "./components/Grids/GenderCellRenderer.js";
import type { AutoGeneratedColumnDef } from "./components/Grids/ValueObjectGridInterface.js";
import {
  DefaultCellRenderer,
} from "./components/SelectEntityInstanceEditor.js";
import { cleanLevel } from "./constants.js";

let log: LoggerInterface = console as any as LoggerInterface;
MiroirLoggerFactory.registerLoggerToStart(
  MiroirLoggerFactory.getLoggerName(packageName, cleanLevel, "getColumnDefinitionsFromEntityDefinitionAttribute"), "UI",
).then((logger: LoggerInterface) => {log = logger});


// ################################################################################################
export function getMDataGridColumnDefinition(
  deploymentUuid: string, // prop drilling
  name: string,
  jzodSchema: JzodElement,
  reportSectionDefinition: ObjectListReportSection | undefined,
  // reportSectionDefinition: ReportSection | undefined,
  entityDefinition?: EntityDefinition | undefined,
  // defaultWidth?: number,
): AutoGeneratedColumnDef {
  const sortParams =
    reportSectionDefinition?.definition.sortByAttribute === name
      ? { sort: reportSectionDefinition.definition.sortOrder ?? "asc", sortIndex: 0 }
      : {};

  if (jzodSchema?.tag?.value?.selectorParams?.targetEntity) {
    const result: AutoGeneratedColumnDef =  {
      field: name,
      ...sortParams,
      headerName: jzodSchema.tag?.value?.defaultLabel ? jzodSchema.tag?.value?.defaultLabel : name,
      cellRenderer: EntityInstanceCellRenderer,
      // cellEditor: SelectEntityInstanceEditorNotUsed, // can not be edited in table column: click navigates to instance details report page
      // cellEditorPopup: true,
      // editable: true,
      // sort:'asc',
      // cellEditorParams: {
      //   entityUuid: jzodSchema?.tag?.value?.targetEntity,
      // },
      cellRendererParams: {
        deploymentUuid,
        isFK: true,
        entityUuid: jzodSchema?.tag?.value?.selectorParams?.targetEntity,
        entityDefinition
      },
      // width: defaultWidth,
    };
    // log.info(
    //   "column with targetEntity named",
    //   name,
    //   "jzodSchema",
    //   jzodSchema,
    //   "targetEntity",
    //   jzodSchema?.tag?.value?.targetEntity,
    //   "entityPublisher.uuid",
    //   entityPublisher.uuid,
    //   entityPublisher.uuid == jzodSchema?.tag?.value?.targetEntity,
    //   "result",
    //   result
    // );

    return result;
  }
  log.info(
    "getColumnDefinitionsFromEntityDefinitionAttribute name column",
    name,
    "jzodSchema",
    jzodSchema,
    // "jzodObjectSchema",
    // jzodObjectSchema,
    "entityDefinition",
    entityDefinition
  );


  switch (name) {
    case "uuid":
    case "name": {

      return {
        field: name,
        headerName: jzodSchema.tag?.value?.defaultLabel ? jzodSchema.tag?.value?.defaultLabel : name,
        ...sortParams,
        cellRenderer: EntityInstanceCellRenderer,
        // cellEditor: SelectEntityInstanceEditorNotUsed,
        // cellEditorPopup: true,
        // editable: true,
        // cellEditorParams: {
        //   entityUuid: entityDefinition?.uuid??"",
        // },
        cellRendererParams: {
          deploymentUuid,
          entityUuid: entityDefinition?.entityUuid??"",
          entityDefinition
        },
        // width: defaultWidth,
      };
      break;
    }
    case "gender": { // TODO: not used anymore, come up with another similar example 
      return {
        field: "gender",
        ...sortParams,
        headerName: jzodSchema.tag?.value?.defaultLabel ? jzodSchema.tag?.value?.defaultLabel : name,
        cellRenderer: GenderCellRenderer,
        cellEditor: GenderCellEditor,
        cellEditorPopup: true,
        editable: true,
        // width: defaultWidth,
        cellRendererParams: {
          deploymentUuid,
          entityUuid: entityDefinition?.entityUuid??"",
          entityDefinition
        },
      };
      break;
    }
    case "conceptLevel": { // TODO: not used anymore, come up with a general solution for enums
      // log.info("column conceptLevel", name, jzodSchema);
      return {
        field: name,
        ...sortParams,
        headerName: jzodSchema.tag?.value?.defaultLabel ? jzodSchema.tag?.value?.defaultLabel : name,
        // width: defaultWidth,
        cellRendererParams: {
          deploymentUuid,
          entityUuid: entityDefinition?.entityUuid??"",
          entityDefinition
        },
      };
    }
    default: {
      if (!jzodSchema) {
        log.error(
          "getColumnDefinitionsFromEntityDefinitionAttribute: jzodSchema is undefined for name",
          name,
          "entityDefinition",
          entityDefinition
        );
      } else {
        log.info("column default:", name, jzodSchema);
      }
      return {
        field: name,
        ...sortParams,
        headerName: jzodSchema.tag?.value?.defaultLabel
          ? jzodSchema.tag?.value?.defaultLabel
          : name,
        cellRenderer: DefaultCellRenderer,
        cellRendererParams: {
          columnName: name,
          deploymentUuid,
          entityUuid: entityDefinition?.entityUuid ?? "",
          entityDefinition,
        },
        // cellRendererParams: {
        //   deploymentUuid,
        //   columnName: name,
        // },
      };
      break;
    }
  }
}

// ################################################################################################
export function getMDataGridColumnDefinitionsFromEntityDefinition(
  deploymentUuid: string,
  jzodSchema: JzodElement | undefined,
  reportSectionDefinition: ObjectListReportSection | undefined,
  // reportSectionDefinition: ReportSection | undefined,
  entityDefinition?: EntityDefinition | undefined,
  rowData?: TableComponentRow[],
  availableWidth?: number
): ColDef<any>[] {
  log.info(
    "getMDataGridColumnDefinitionsFromEntityDefinition",
    "deploymentUuid",
    deploymentUuid,
    "jzodSchema",
    jzodSchema,
    "viewAttributes",
    entityDefinition?.viewAttributes,
    "entityDefinition",
    entityDefinition,
    "reportSectionDefinition",
    reportSectionDefinition
  );
  
  // let columnDefs: ColDef<any>[] = [];
  let columnDefs: AutoGeneratedColumnDef[] = [];
  
  switch (jzodSchema?.type) {
    case "object":
      {
        const schemaKeys = Object.keys(jzodSchema.definition)
        if (entityDefinition?.viewAttributes) {
          columnDefs = entityDefinition.viewAttributes
            .filter((a: string) => [a, schemaKeys.find((b) => b == a)])
            .map((a: string) =>
              getMDataGridColumnDefinition(
                deploymentUuid,
                a,
                jzodSchema.definition[a],
                reportSectionDefinition,
                entityDefinition,
              )
            );
        } else {
          columnDefs = Object.entries(jzodSchema.definition ? jzodSchema.definition : {})
            .map((e: [string, any]) =>
              getMDataGridColumnDefinition(deploymentUuid, e[0], e[1], reportSectionDefinition, entityDefinition)
            );
        }
      }
      break;
    default: {
      columnDefs = [];
      break;
    }
  }
  // // Calculate adaptive widths if row data is provided
  // if (rowData && rowData.length > 0 && columnDefs.length > 0) {
  //   const widthSpecs = calculateAdaptiveColumnWidths(
  //     columnDefs,
  //     rowData,
  //     availableWidth || 1200,
  //     {
  //       // field: "tools",
  //       field: "", // TODO: THIS IS WRONG!!!!!!!
  //       headerName: "Actions",
  //       width: 120,
  //     },
  //     jzodSchema?.type === "object" ? jzodSchema.definition : undefined
  //   );

  //   // // Apply calculated widths to column definitions
  //   // columnDefs.forEach((colDef, index) => {
  //   //   const widthSpec = widthSpecs.find(spec => spec.field === colDef.field);
  //   //   if (widthSpec) {
  //   //     colDef.width = Math.round(widthSpec.calculatedWidth);
  //   //     colDef.minWidth = Math.round(widthSpec.minWidth);
  //   //     colDef.maxWidth = Math.round(widthSpec.maxWidth);
  //   //     // colDef.suppressSizeToFit = true;// defined by Ag-Grid to limit auto-sizing
  //   //     // colDef.suppressAutoSize = true;
  //   //   }
  //   // });
  // }

  return columnDefs;
}
