#!/usr/bin/env tsx
/**
 * Issue #286: writes the MiroirTest instance `JzodElementEditor_ComponentTestSuite` from the
 * React-free component test manifest, and wires it in `miroir-test-app_deployment-miroir`:
 *
 * - the instance JSON in `assets/miroir_data/a311f363-…/<uuid>.json`, one sub-suite per manifest
 *   suite and one `reactComponentTest` leaf per case, in manifest order;
 * - the named export in `index.ts`;
 * - the `export declare const …: any;` line in the hand-kept `index.d.ts`;
 * - the import and the `defaultMiroirMetaModel.tests` entry in `src/Model.ts`.
 *
 * Idempotent: a second run leaves every file byte-identical.
 *
 * Run from the repo root, then rebuild the deployment package:
 * ```bash
 * npx tsx packages/miroir-standalone-app/scripts/generate-component-miroir-tests.ts
 * npm run build -w miroir-test-app_deployment-miroir
 * ```
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Only the manifest: this script must not load React or the component test registry.
import {
  componentTestLeafLabel,
  componentTestManifest,
  componentTestSuiteInstanceName,
  componentTestSuiteInstanceUuid,
} from "../src/miroir-fwk/4-tests/componentTests/componentTestManifest.js";

const MIROIR_TEST_ENTITY_UUID = "a311f363-e238-4203-bdfc-29e8c160c26b";
const MIROIR_SELF_APPLICATION_UUID = "360fcf1f-f0d4-4f8a-9262-07886e70fa15";
const MIROIR_BRANCH_UUID = "ad1ddc4e-556e-4598-9cff-706a2bde0be7";
const EOL = "\r\n";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const deploymentMiroirDir = path.resolve(scriptDir, "../../miroir-test-app_deployment-miroir");
const instanceRelativePath = `./assets/miroir_data/${MIROIR_TEST_ENTITY_UUID}/${componentTestSuiteInstanceUuid}.json`;
const exportName = `miroirTest_${componentTestSuiteInstanceName}`;

// ################################################################################################
export function buildComponentTestSuiteInstance(manifest: Record<string, readonly string[]>) {
  return {
    uuid: componentTestSuiteInstanceUuid,
    parentName: "MiroirTest",
    parentUuid: MIROIR_TEST_ENTITY_UUID,
    name: componentTestSuiteInstanceName,
    selfApplication: MIROIR_SELF_APPLICATION_UUID,
    branch: MIROIR_BRANCH_UUID,
    description:
      "Issue #286: JzodElementEditor React component tests. Generated by packages/miroir-standalone-app/scripts/generate-component-miroir-tests.ts from componentTestManifest.ts, do not edit by hand.",
    definition: {
      miroirTestType: "miroirTestSuite",
      miroirTestLabel: componentTestSuiteInstanceName,
      miroirTests: Object.entries(manifest).map(([suite, cases]) => ({
        miroirTestType: "miroirTestSuite",
        miroirTestLabel: suite,
        miroirTests: cases.map((caseLabel) => ({
          miroirTestType: "reactComponentTest",
          miroirTestLabel: componentTestLeafLabel(suite, caseLabel),
          componentTestRef: { suite, case: caseLabel },
        })),
      })),
    },
  };
}

// ################################################################################################
function readLines(filePath: string): string[] {
  return readFileSync(filePath, "utf-8").split(/\r?\n/);
}

function writeIfChanged(filePath: string, content: string): boolean {
  let previous: string | undefined;
  try {
    previous = readFileSync(filePath, "utf-8");
  } catch {
    previous = undefined;
  }
  if (previous === content) {
    return false;
  }
  writeFileSync(filePath, content, "utf-8");
  return true;
}

/** Inserts `line` after the last line matching `anchor`, unless a line equal to `line` exists. */
function insertLineAfterLastMatch(lines: string[], line: string, anchor: RegExp, what: string): string[] {
  if (lines.some((existing) => existing.trimEnd() === line)) {
    return lines;
  }
  let lastIndex = -1;
  lines.forEach((existing, index) => {
    if (anchor.test(existing)) {
      lastIndex = index;
    }
  });
  if (lastIndex < 0) {
    throw new Error(`generate-component-miroir-tests: anchor for ${what} not found`);
  }
  return [...lines.slice(0, lastIndex + 1), line, ...lines.slice(lastIndex + 1)];
}

/** Inserts `line` after the first line equal to `anchorLine`, unless a line equal to `line` exists. */
function insertLineAfterFirst(lines: string[], line: string, anchorLine: string, what: string): string[] {
  if (lines.some((existing) => existing.trimEnd() === line)) {
    return lines;
  }
  const index = lines.findIndex((existing) => existing.trimEnd() === anchorLine);
  if (index < 0) {
    throw new Error(`generate-component-miroir-tests: anchor "${anchorLine.trim()}" for ${what} not found`);
  }
  return [...lines.slice(0, index + 1), line, ...lines.slice(index + 1)];
}

// ################################################################################################
function main() {
  const changed: string[] = [];

  // 1. instance JSON
  const instancePath = path.join(deploymentMiroirDir, instanceRelativePath);
  const instanceJson =
    JSON.stringify(buildComponentTestSuiteInstance(componentTestManifest), null, 2).replace(/\n/g, EOL) + EOL;
  if (writeIfChanged(instancePath, instanceJson)) {
    changed.push(instancePath);
  }

  // 2. index.ts named export
  const indexTsPath = path.join(deploymentMiroirDir, "index.ts");
  const indexTsLines = insertLineAfterLastMatch(
    readLines(indexTsPath),
    `export { default as ${exportName} } from "${instanceRelativePath}" with { type: "json" };`,
    /^export \{ default as miroirTest_\w+ \} from "\.\/assets\/miroir_data\//,
    "index.ts export",
  );
  if (writeIfChanged(indexTsPath, indexTsLines.join(EOL))) {
    changed.push(indexTsPath);
  }

  // 3. index.d.ts declaration
  const indexDtsPath = path.join(deploymentMiroirDir, "index.d.ts");
  const indexDtsLines = insertLineAfterLastMatch(
    readLines(indexDtsPath),
    `export declare const ${exportName}: any;`,
    /^export declare const miroirTest_\w+: any;/,
    "index.d.ts declaration",
  );
  if (writeIfChanged(indexDtsPath, indexDtsLines.join(EOL))) {
    changed.push(indexDtsPath);
  }

  // 4. src/Model.ts import and defaultMiroirMetaModel.tests entry
  const modelTsPath = path.join(deploymentMiroirDir, "src/Model.ts");
  let modelLines = insertLineAfterFirst(
    readLines(modelTsPath),
    `  ${exportName},`,
    "  miroirTest_unfoldSchemaOnce,",
    "Model.ts import",
  );
  modelLines = insertLineAfterFirst(
    modelLines,
    `    ${exportName} as MiroirTestDefinition,`,
    "    miroirTest_runner_mcp_get_instances as MiroirTestDefinition,",
    "defaultMiroirMetaModel.tests entry",
  );
  if (writeIfChanged(modelTsPath, modelLines.join(EOL))) {
    changed.push(modelTsPath);
  }

  const caseCount = Object.values(componentTestManifest).reduce((sum, cases) => sum + cases.length, 0);
  console.log(
    `generate-component-miroir-tests: ${Object.keys(componentTestManifest).length} suite(s), ${caseCount} case(s).`,
  );
  console.log(
    changed.length === 0
      ? "generate-component-miroir-tests: no change."
      : `generate-component-miroir-tests: wrote\n  ${changed.join("\n  ")}`,
  );
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
