#!/bin/sh
# =============================================================================
# Miroir Framework — Docker entrypoint
# =============================================================================
# 1. On the very first start (empty /data volume), seeds the volume with the
#    image's /seed: the `docker` environment definition (environments/docker.json)
#    and the assets of the applications it installs (Miroir, Admin, Library).
#    The server runs that environment: MIROIR_ROOT=/data, MIROIR_ENV=docker (#345).
# 2. A volume seeded by an older image gets the environment definitions it lacks.
# 3. Delegates to the command passed as arguments (defaults to starting the
#    Node.js server).
# =============================================================================
set -e

# Overridable for tests (scripts/tests/test_docker_entrypoint.py).
SEED_DIR="${MIROIR_SEED_DIR:-/seed}"
DATA_DIR="${MIROIR_DATA_DIR:-/data}"

# Determine whether the data volume has already been initialised.
# A volume is considered uninitialised when it is empty (no files or dirs).
is_empty() {
  [ -z "$(ls -A "$1" 2>/dev/null)" ]
}

if is_empty "$DATA_DIR"; then
  echo "[miroir] First run detected — initialising data volume from seed..."
  # Copy seed data preserving directory structure and permissions.
  # The trailing /. on the source ensures hidden files are also copied.
  cp -r "${SEED_DIR}/." "${DATA_DIR}/"
  echo "[miroir] Data volume initialised at ${DATA_DIR}."
  echo "[miroir] Seeded:"
  find "${DATA_DIR}" -maxdepth 3 -type d | sed 's|^|  |'
else
  echo "[miroir] Data volume already initialised — skipping seed."
  # #344: application packages were renamed by role. A volume seeded before
  # the rename keeps its data under the old directory names, and its
  # Deployment rows point there: move the directories and rewrite the paths.
  for rename in \
    miroir-test-app_deployment-miroir:miroir-app-miroir \
    miroir-test-app_deployment-admin:miroir-app-admin \
    miroir-test-app_deployment-library:miroir-example-library \
    miroir-test-app_deployment-spotify:miroir-example-spotify \
    miroir-test-app_deployment-designer:miroir-example-designer \
    miroir-test-app_deployment-postgres:miroir-example-postgres \
    miroir-test-app_deployment-appForTest:miroir-fixture-appForTest; do
    old="${rename%%:*}"
    new="${rename#*:}"
    if [ -d "${DATA_DIR}/${old}" ] && [ ! -e "${DATA_DIR}/${new}" ]; then
      mv "${DATA_DIR}/${old}" "${DATA_DIR}/${new}"
      echo "[miroir] Moved ${old} to ${new}."
    fi
    find "${DATA_DIR}" -type f -name '*.json' -exec grep -l "${old}" {} + 2>/dev/null | while read -r file; do
      sed -i "s/${old}/${new}/g" "$file"
      echo "[miroir] Rewrote ${old} paths in ${file}."
    done
  done
  # #345: volumes seeded before the image ran an environment have no environments/.
  if [ -d "${SEED_DIR}/environments" ]; then
    mkdir -p "${DATA_DIR}/environments"
    for definition in "${SEED_DIR}"/environments/*.json; do
      target="${DATA_DIR}/environments/$(basename "$definition")"
      if [ ! -e "$target" ]; then
        cp "$definition" "$target"
        echo "[miroir] Added ${target}."
      fi
    done
  fi
fi

# ── TLS setup ─────────────────────────────────────────────────────────────────
# Use certificates mounted into /certs (generated by mkcert on the Docker host
# and therefore already trusted by the host browser).
# If no certs are found the server gracefully falls back to plain HTTP.
CERTS_DIR=/certs
if [ -f "$CERTS_DIR/localhost.pem" ] && [ -f "$CERTS_DIR/localhost-key.pem" ]; then
  export MIROIR_TLS_CERT="${MIROIR_TLS_CERT:-$CERTS_DIR/localhost.pem}"
  export MIROIR_TLS_KEY="${MIROIR_TLS_KEY:-$CERTS_DIR/localhost-key.pem}"
  echo "[miroir] TLS enabled — using certificates from $CERTS_DIR"
else
  echo "[miroir] WARNING: no TLS certificates found in $CERTS_DIR — server will use HTTP"
fi
# Allow Node.js to trust the host mkcert root CA for any internal HTTPS calls.
if [ -f "$CERTS_DIR/rootCA.pem" ]; then
  export NODE_EXTRA_CA_CERTS="$CERTS_DIR/rootCA.pem"
  echo "[miroir] NODE_EXTRA_CA_CERTS → $CERTS_DIR/rootCA.pem"
fi

echo "[miroir] Starting server..."
exec "$@"
