#!/bin/sh
# =============================================================================
# Miroir Framework — Docker entrypoint
# =============================================================================
# 1. On the very first start (empty /data volume), seeds the volume with the
#    framework bootstrap data and the library demo application.
# 2. Delegates to the command passed as arguments (defaults to starting the
#    Node.js server: node /miroir/packages/miroir-server/dist/server.js).
# =============================================================================
set -e

SEED_DIR=/seed
DATA_DIR=/data

# Determine whether the data volume has already been initialised.
# A volume is considered uninitialised when it is empty (no files or dirs).
is_empty() {
  [ -z "$(ls -A "$1" 2>/dev/null)" ]
}

if is_empty "$DATA_DIR"; then
  echo "[miroir] First run detected — initialising data volume from seed..."
  # Copy seed data preserving directory structure and permissions.
  # The trailing /. on the source ensures hidden files are also copied.
  cp -r "${SEED_DIR}/." "${DATA_DIR}/"
  echo "[miroir] Data volume initialised at ${DATA_DIR}."
  echo "[miroir] Seeded:"
  find "${DATA_DIR}" -maxdepth 3 -type d | sed 's|^|  |'
else
  echo "[miroir] Data volume already initialised — skipping seed."
fi

# ── TLS setup ─────────────────────────────────────────────────────────────────
# Use certificates mounted into /certs (generated by mkcert on the Docker host
# and therefore already trusted by the host browser).
# If no certs are found the server gracefully falls back to plain HTTP.
CERTS_DIR=/certs
if [ -f "$CERTS_DIR/localhost.pem" ] && [ -f "$CERTS_DIR/localhost-key.pem" ]; then
  export MIROIR_TLS_CERT="${MIROIR_TLS_CERT:-$CERTS_DIR/localhost.pem}"
  export MIROIR_TLS_KEY="${MIROIR_TLS_KEY:-$CERTS_DIR/localhost-key.pem}"
  echo "[miroir] TLS enabled — using certificates from $CERTS_DIR"
else
  echo "[miroir] WARNING: no TLS certificates found in $CERTS_DIR — server will use HTTP"
fi
# Allow Node.js to trust the host mkcert root CA for any internal HTTPS calls.
if [ -f "$CERTS_DIR/rootCA.pem" ]; then
  export NODE_EXTRA_CA_CERTS="$CERTS_DIR/rootCA.pem"
  echo "[miroir] NODE_EXTRA_CA_CERTS → $CERTS_DIR/rootCA.pem"
fi

echo "[miroir] Starting server..."
exec "$@"
