import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

import {
  adminApplicationRow,
  applicationAssetsDirectory,
  deploymentRow,
  type AdminApplication,
  type AdminRowLabels,
  type Deployment,
  type EnvironmentDeployment,
} from "miroir-core";

import type { ResolvedEnvironment } from "./environmentFiles.js";

// ################################################################################################
// The Deployment and AdminApplication rows an environment definition implies, and how the rows of
// an Admin data store compare with them (#321, analysis D15). The server applies the comparison
// at start (openEnvironment.ts); `miroir-env check` reports it without changing anything.
// ################################################################################################

const SELF_APPLICATION_ENTITY = "a659d350-dd97-4da9-91de-524fa01745dc";

export type AdminRow = Record<string, unknown>;
export type AdminRows = { deployments: AdminRow[]; applications: AdminRow[] };
export type EnvironmentAdminRows = { deployments: Deployment[]; adminApplications: AdminApplication[] };

export type AdminRowChange = {
  action: "create" | "rewrite";
  entity: "Deployment" | "AdminApplication";
  /** The row as written: the generated row, or the existing row updated with the generated fields. */
  row: AdminRow;
};

export type AdminRowsComparison = {
  changes: AdminRowChange[];
  /** The rows once the changes are applied. */
  rows: AdminRows;
  /** Deployment rows of the Admin data that the definition does not install. */
  extras: Deployment[];
  /** AdminApplication names by uuid, once the changes are applied. */
  applicationNames: Map<string, string>;
};

/** A JSON text with sorted keys: equal values give equal texts. */
export function stableJson(value: unknown): string {
  if (Array.isArray(value)) {
    return `[${value.map(stableJson).join(",")}]`;
  }
  if (value && typeof value === "object") {
    return `{${Object.keys(value)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${stableJson((value as Record<string, unknown>)[key])}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}

/**
 * Name and labels of an application: from the SelfApplication row in its package, else from its
 * AdminApplication row already in Admin data (an application that gives its configuration), else
 * its key in the definition.
 */
function applicationLabels(
  resolved: ResolvedEnvironment,
  deployment: EnvironmentDeployment,
  existingApplications: Map<string, AdminRow>,
): AdminRowLabels {
  const application = resolved.environment.applications?.[deployment.applicationKey];
  for (const section of ["model", "data"] as const) {
    if (!application?.package) {
      break;
    }
    const file = path.join(
      resolved.repositoryRoot,
      applicationAssetsDirectory(deployment.applicationKey, { ...application, package: application.package }, section),
      SELF_APPLICATION_ENTITY,
      `${deployment.selfApplication}.json`,
    );
    if (existsSync(file)) {
      const row = JSON.parse(readFileSync(file, "utf-8"));
      return { name: row.name, defaultLabel: row.defaultLabel, description: row.description };
    }
  }
  const existing = existingApplications.get(deployment.selfApplication);
  if (typeof existing?.name === "string") {
    return {
      name: existing.name,
      defaultLabel: typeof existing.defaultLabel === "string" ? existing.defaultLabel : undefined,
      description: typeof existing.description === "string" ? existing.description : undefined,
    };
  }
  return { name: deployment.applicationKey };
}

/**
 * The Deployment and AdminApplication rows the definition of an environment implies.
 * `existing` gives the labels of applications that name no package.
 */
export function environmentAdminRows(resolved: ResolvedEnvironment, existing: AdminRows = { deployments: [], applications: [] }): EnvironmentAdminRows {
  const existingApplications = new Map(existing.applications.map((row) => [String(row.uuid), row]));
  const rows: EnvironmentAdminRows = { deployments: [], adminApplications: [] };
  for (const deployment of resolved.deployments) {
    const labels = applicationLabels(resolved, deployment, existingApplications);
    rows.adminApplications.push(adminApplicationRow(deployment.selfApplication, labels));
    rows.deployments.push(
      deploymentRow(deployment.deployment, deployment.selfApplication, deployment.configuration, {
        name: `${labels.name}_${resolved.name}`,
        defaultLabel: `${labels.name} in environment ${resolved.name}`,
        description: `Deployment of ${labels.name} in environment "${resolved.name}", generated by miroir-env from the environment definition.`,
      }),
    );
  }
  return rows;
}

/** True when every field of `generated` has the same value in `existing`. */
function matches(existing: AdminRow, generated: AdminRow): boolean {
  return Object.keys(generated).every((key) => stableJson(existing[key]) === stableJson(generated[key]));
}

function compareRows(
  entity: AdminRowChange["entity"],
  existingRows: AdminRow[],
  generatedRows: AdminRow[],
): { rows: AdminRow[]; changes: AdminRowChange[] } {
  const byUuid = new Map(existingRows.map((row) => [String(row.uuid), row]));
  const changes: AdminRowChange[] = [];
  for (const generated of generatedRows) {
    const uuid = String(generated.uuid);
    const existing = byUuid.get(uuid);
    if (!existing) {
      byUuid.set(uuid, generated);
      changes.push({ action: "create", entity, row: generated });
    } else if (!matches(existing, generated)) {
      const updated = { ...existing, ...generated };
      byUuid.set(uuid, updated);
      changes.push({ action: "rewrite", entity, row: updated });
    }
  }
  return { rows: [...byUuid.values()], changes };
}

/**
 * How the Deployment and AdminApplication rows of an Admin data store compare with the
 * definition: rows to create or rewrite, and deployments the definition does not install
 * (kept: removing them is `miroir-env prune`'s decision, D15).
 */
export function compareAdminRows(resolved: ResolvedEnvironment, existing: AdminRows): AdminRowsComparison {
  const generated = environmentAdminRows(resolved, existing);
  const applications = compareRows("AdminApplication", existing.applications, generated.adminApplications);
  const deployments = compareRows("Deployment", existing.deployments, generated.deployments);
  const defined = new Set(resolved.deployments.map((d) => d.deployment));
  return {
    changes: [...applications.changes, ...deployments.changes],
    rows: { deployments: deployments.rows, applications: applications.rows },
    extras: (deployments.rows as Deployment[]).filter((row) => !defined.has(row.uuid)),
    applicationNames: new Map(applications.rows.map((row) => [String(row.uuid), String(row.name)])),
  };
}

/** A change once applied (server log). */
export function appliedChange(change: AdminRowChange): string {
  const subject = `${change.entity} ${change.row.uuid} (${change.row.name})`;
  return `${change.action === "create" ? "created" : "rewrote"} ${subject} from the definition`;
}

/** A change the next start applies (`miroir-env check`). */
export function pendingChange(change: AdminRowChange): string {
  const subject = `${change.entity} ${change.row.uuid} (${change.row.name})`;
  return change.action === "create"
    ? `${subject} is missing from the Admin data: the next start creates it from the definition`
    : `${subject} differs from the definition: the next start rewrites it`;
}

/** The name of the application of a deployment, for messages. */
export function deploymentLabel(comparison: AdminRowsComparison, deployment: Deployment): string {
  return comparison.applicationNames.get(deployment.selfApplication) ?? deployment.name;
}

/** The warning about a deployment of the Admin data that the definition does not install. */
export function extraDeploymentWarning(resolved: ResolvedEnvironment, deployment: Deployment, label: string): string {
  const where = `deployment ${deployment.uuid} (${label}) is in the Admin data of environment "${resolved.name}" but not in its definition`;
  return deployment.configuration
    ? `${where}: it is opened anyway; record it with "miroir-env import" or remove it with "miroir-env prune"`
    : `${where} and has no configuration: it is not opened; remove it with "miroir-env prune"`;
}
