import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

import {
  Action2Error,
  applicationAssetsDirectory,
  defaultMetaModelEnvironment,
  defaultSelfApplicationDeploymentMap,
  ENTITY_ADMIN_APPLICATION_UUID,
  ENTITY_DEPLOYMENT_UUID,
  type AdminApplication,
  type ApplicationDeploymentMap,
  type Deployment,
  type DomainControllerInterface,
  type EntityInstance,
  type EnvironmentDeployment,
  type StoreUnitConfiguration,
} from "miroir-core";

import { EnvironmentError, type ResolvedEnvironment } from "./environmentFiles.js";

// ################################################################################################
// Opening an environment's deployments (#321). The environment definition is the source of the
// Deployment and AdminApplication rows in Admin data; rows found there and absent from the
// definition (e.g. a UI install not recorded yet) are kept, opened, and reported as warnings.
// ################################################################################################

const ADMIN_APPLICATION = "55af124e-8c05-4bae-a3ef-0933d41daa92";
const SELF_APPLICATION_ENTITY = "a659d350-dd97-4da9-91de-524fa01745dc";
const INSTANCE_ENDPOINT = "ed520de4-55a9-4550-ac50-b1b713b72a89";
const QUERY_ENDPOINT = "9e404b3c-368c-40cb-be8b-e3c28550c25e";
const STORE_MANAGEMENT_ENDPOINT = "bbd08cbb-79ff-4539-b91f-7a14f15ac55f";

/** Opened first, with the platform's default application → deployment map. */
const BOOT_APPLICATIONS = ["admin", "miroir"];

export type EnvironmentAdminRows = { deployments: Deployment[]; adminApplications: AdminApplication[] };

export type EnvironmentReconciliation = {
  /** Every Deployment row in Admin data after reconciliation. */
  deployments: Deployment[];
  applicationDeploymentMap: ApplicationDeploymentMap;
  /** Deployment uuids open after reconciliation, boot deployments first. */
  opened: string[];
  /** Rows created or rewritten from the definition. */
  changes: string[];
  /** Deviations between the Admin data and the definition. */
  warnings: string[];
};

type ApplicationLabel = { name: string; defaultLabel: string; description?: string };

/** Name and labels of an application, from the SelfApplication row in its package. */
function applicationLabel(resolved: ResolvedEnvironment, deployment: EnvironmentDeployment): ApplicationLabel {
  const application = resolved.environment.applications?.[deployment.applicationKey];
  for (const section of ["model", "data"] as const) {
    if (!application) {
      break;
    }
    const file = path.join(
      resolved.repositoryRoot,
      applicationAssetsDirectory(deployment.applicationKey, application, section),
      SELF_APPLICATION_ENTITY,
      `${deployment.selfApplication}.json`,
    );
    if (existsSync(file)) {
      const row = JSON.parse(readFileSync(file, "utf-8"));
      return {
        name: row.name,
        defaultLabel: row.defaultLabel ?? row.name,
        ...(row.description ? { description: row.description } : {}),
      };
    }
  }
  return { name: deployment.applicationKey, defaultLabel: deployment.applicationKey };
}

/** The Deployment and AdminApplication rows the definition of an environment implies. */
export function environmentAdminRows(resolved: ResolvedEnvironment): EnvironmentAdminRows {
  const rows: EnvironmentAdminRows = { deployments: [], adminApplications: [] };
  for (const deployment of resolved.deployments) {
    const label = applicationLabel(resolved, deployment);
    rows.adminApplications.push({
      uuid: deployment.selfApplication,
      parentName: "AdminApplication",
      parentUuid: ENTITY_ADMIN_APPLICATION_UUID,
      name: label.name,
      defaultLabel: label.defaultLabel,
      ...(label.description ? { description: label.description } : {}),
      selfApplication: deployment.selfApplication,
    });
    rows.deployments.push({
      uuid: deployment.deployment,
      parentName: "Deployment",
      parentUuid: ENTITY_DEPLOYMENT_UUID,
      name: `${label.name}_${resolved.name}`,
      defaultLabel: `${label.name} in environment ${resolved.name}`,
      description: `Deployment of ${label.name} in environment "${resolved.name}", generated by miroir-env from the environment definition.`,
      selfApplication: deployment.selfApplication,
      configuration: deployment.configuration,
    });
  }
  return rows;
}

function stableJson(value: unknown): string {
  if (Array.isArray(value)) {
    return `[${value.map(stableJson).join(",")}]`;
  }
  if (value && typeof value === "object") {
    return `{${Object.keys(value)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${stableJson((value as Record<string, unknown>)[key])}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}

/** True when every field of `generated` has the same value in `existing`. */
function matches(existing: Record<string, unknown>, generated: Record<string, unknown>): boolean {
  return Object.keys(generated).every((key) => stableJson(existing[key]) === stableJson(generated[key]));
}

function rowsOf(value: unknown): Record<string, unknown>[] {
  if (Array.isArray(value)) {
    return value;
  }
  return value && typeof value === "object" ? (Object.values(value) as Record<string, unknown>[]) : [];
}

async function openDeployment(
  domainController: DomainControllerInterface,
  selfApplication: string,
  deployment: string,
  configuration: StoreUnitConfiguration,
  applicationDeploymentMap: ApplicationDeploymentMap,
): Promise<void> {
  const result = await domainController.handleAction(
    {
      actionType: "storeManagementAction_openStore",
      endpoint: STORE_MANAGEMENT_ENDPOINT,
      payload: {
        application: selfApplication,
        deploymentUuid: deployment,
        configuration: { [deployment]: configuration },
      },
    },
    applicationDeploymentMap,
    defaultMetaModelEnvironment,
  );
  if (result instanceof Action2Error) {
    throw new EnvironmentError(`could not open deployment ${deployment}: ${result.errorMessage}`);
  }
}

async function persistAdminRows(
  domainController: DomainControllerInterface,
  actionType: "createInstance" | "updateInstance",
  parentUuid: string,
  objects: EntityInstance[],
): Promise<void> {
  if (objects.length === 0) {
    return;
  }
  const result = await domainController.handleAction(
    {
      actionType,
      endpoint: INSTANCE_ENDPOINT,
      payload: { application: ADMIN_APPLICATION, applicationSection: "data", parentUuid, objects },
    },
    defaultSelfApplicationDeploymentMap,
    defaultMetaModelEnvironment,
  );
  if (result instanceof Action2Error) {
    throw new EnvironmentError(`could not write Admin rows of entity ${parentUuid}: ${result.errorMessage}`);
  }
}

/**
 * Opens the Admin and Miroir deployments of an environment. The platform addresses them through
 * `defaultSelfApplicationDeploymentMap`, so an environment cannot give them other uuids.
 */
export async function openEnvironmentBootDeployments(
  domainController: DomainControllerInterface,
  resolved: ResolvedEnvironment,
): Promise<string[]> {
  const opened: string[] = [];
  for (const key of BOOT_APPLICATIONS) {
    const deployment = resolved.deployments.find((d) => d.applicationKey === key);
    if (!deployment) {
      throw new EnvironmentError(`environment "${resolved.name}" does not install application "${key}"`);
    }
    const expected = defaultSelfApplicationDeploymentMap[deployment.selfApplication];
    if (expected !== deployment.deployment) {
      throw new EnvironmentError(
        `environment "${resolved.name}": application "${key}" must use deployment ${expected}, the one the platform opens, got ${deployment.deployment}`,
      );
    }
    await openDeployment(
      domainController,
      deployment.selfApplication,
      deployment.deployment,
      deployment.configuration,
      defaultSelfApplicationDeploymentMap,
    );
    opened.push(deployment.deployment);
  }
  return opened;
}

async function queryAdminRows(domainController: DomainControllerInterface) {
  const result = await domainController.handleBoxedExtractorOrQueryAction(
    {
      actionType: "runBoxedQueryAction",
      endpoint: QUERY_ENDPOINT,
      payload: {
        application: ADMIN_APPLICATION,
        applicationSection: "data",
        queryExecutionStrategy: "storage",
        query: {
          application: ADMIN_APPLICATION,
          queryType: "boxedQueryWithExtractorCombinerTransformer",
          extractors: {
            deployments: { extractorOrCombinerType: "extractorInstancesByEntity", parentUuid: ENTITY_DEPLOYMENT_UUID },
            applications: { extractorOrCombinerType: "extractorInstancesByEntity", parentUuid: ENTITY_ADMIN_APPLICATION_UUID },
          },
        },
      },
    },
    defaultSelfApplicationDeploymentMap,
    defaultMetaModelEnvironment,
  );
  if (result instanceof Action2Error) {
    throw new EnvironmentError(`could not read the Deployment rows of Admin: ${result.errorMessage}`);
  }
  const element = (result as { returnedDomainElement?: { deployments?: unknown; applications?: unknown } }).returnedDomainElement;
  return { deployments: rowsOf(element?.deployments), applications: rowsOf(element?.applications) };
}

/** Creates missing rows and rewrites rows that differ from the definition; returns the changes. */
async function reconcileRows(
  domainController: DomainControllerInterface,
  entity: { uuid: string; name: string },
  existingRows: Record<string, unknown>[],
  generatedRows: (Deployment | AdminApplication)[],
): Promise<{ rows: Record<string, unknown>[]; changes: string[] }> {
  const byUuid = new Map(existingRows.map((row) => [String(row.uuid), row]));
  const toCreate: EntityInstance[] = [];
  const toUpdate: EntityInstance[] = [];
  const changes: string[] = [];
  for (const generated of generatedRows) {
    const existing = byUuid.get(generated.uuid);
    if (!existing) {
      toCreate.push(generated as EntityInstance);
      byUuid.set(generated.uuid, generated);
      changes.push(`created ${entity.name} ${generated.uuid} (${generated.name})`);
    } else if (!matches(existing, generated)) {
      const updated = { ...existing, ...generated };
      toUpdate.push(updated as EntityInstance);
      byUuid.set(generated.uuid, updated);
      changes.push(`rewrote ${entity.name} ${generated.uuid} (${generated.name}) from the definition`);
    }
  }
  await persistAdminRows(domainController, "createInstance", entity.uuid, toCreate);
  await persistAdminRows(domainController, "updateInstance", entity.uuid, toUpdate);
  return { rows: [...byUuid.values()], changes };
}

/**
 * After the boot deployments are open: aligns the Deployment and AdminApplication rows of Admin
 * with the definition, then opens every other deployment, those of the definition and the extra
 * ones found in Admin data (with a warning).
 */
export async function reconcileEnvironmentDeployments(
  domainController: DomainControllerInterface,
  resolved: ResolvedEnvironment,
): Promise<EnvironmentReconciliation> {
  const existing = await queryAdminRows(domainController);
  const generated = environmentAdminRows(resolved);
  const applications = await reconcileRows(
    domainController,
    { uuid: ENTITY_ADMIN_APPLICATION_UUID, name: "AdminApplication" },
    existing.applications,
    generated.adminApplications,
  );
  const deploymentRows = await reconcileRows(
    domainController,
    { uuid: ENTITY_DEPLOYMENT_UUID, name: "Deployment" },
    existing.deployments,
    generated.deployments,
  );
  const deployments = deploymentRows.rows as Deployment[];

  const applicationDeploymentMap: ApplicationDeploymentMap = Object.fromEntries(
    deployments.map((deployment) => [deployment.selfApplication, deployment.uuid]),
  );
  const applicationNames = new Map(applications.rows.map((row) => [String(row.uuid), String(row.name)]));
  const defined = new Set(resolved.deployments.map((d) => d.deployment));
  const opened = resolved.deployments.filter((d) => BOOT_APPLICATIONS.includes(d.applicationKey)).map((d) => d.deployment);
  const warnings: string[] = [];

  for (const deployment of resolved.deployments) {
    if (opened.includes(deployment.deployment)) {
      continue;
    }
    await openDeployment(
      domainController,
      deployment.selfApplication,
      deployment.deployment,
      deployment.configuration,
      applicationDeploymentMap,
    );
    opened.push(deployment.deployment);
  }
  for (const deployment of deployments) {
    if (defined.has(deployment.uuid)) {
      continue;
    }
    const label = applicationNames.get(deployment.selfApplication) ?? deployment.name;
    if (!deployment.configuration) {
      warnings.push(
        `deployment ${deployment.uuid} (${label}) is in the Admin data of environment "${resolved.name}" but not in its definition, and has no configuration; not opened`,
      );
      continue;
    }
    warnings.push(
      `deployment ${deployment.uuid} (${label}) is in the Admin data of environment "${resolved.name}" but not in its definition; opened anyway`,
    );
    await openDeployment(
      domainController,
      deployment.selfApplication,
      deployment.uuid,
      deployment.configuration,
      applicationDeploymentMap,
    );
    opened.push(deployment.uuid);
  }

  return {
    deployments,
    applicationDeploymentMap,
    opened,
    changes: [...applications.changes, ...deploymentRows.changes],
    warnings,
  };
}
