import type {
  EndpointDefinition,
  Entity,
  EntityInstance,
  EntityVersion,
  Menu,
  MetaModel,
  MiroirTestDefinition,
  MlSchema,
  Report,
  Runner,
  SelfApplication,
} from "miroir-core";
import {
  applicationEndpointV1,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionApplication,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionApplicationModelBranch,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionApplicationVersion,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionEntity,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionEntityDefinition,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionReport,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionStoreBasedConfiguration,
  compactStoredMiroirTheme,
  darkStoredMiroirTheme,
  defaultStoredMiroirTheme,
  deploymentEndpointV1,
  domainEndpointVersionV1,
  entityApplicationEvolutionTrace,
  entityApplicationEvolutionTraceEvent,
  entityApplicationVersionCrossEntityVersion,
  entityApplicationVersionCrossQueryVersion,
  entityHistoricalQueryVersion,
  entityHistoricalReportVersion,
  entityApplicationVersionCrossReportVersion,
  entityHistoricalMenuVersion,
  entityApplicationVersionCrossMenuVersion,
  entityHistoricalEndpointVersion,
  entityApplicationVersionCrossEndpointVersion,
  entityHistoricalRunnerVersion,
  entityApplicationVersionCrossRunnerVersion,
  entityHistoricalThemeVersion,
  entityApplicationVersionCrossThemeVersion,
  entityHistoricalTransformerDefinitionVersion,
  entityApplicationVersionCrossTransformerDefinitionVersion,
  entityDefinitionApplicationEvolutionTrace,
  entityDefinitionApplicationEvolutionTraceEvent,
  entityDefinitionApplicationVersionCrossEntityDefinition,
  entityDefinitionEndpoint,
  entityDefinitionEntity,
  entityDefinitionEntityDefinition,
  entityDefinitionMlSchema,
  entityDefinitionMenu,
  entityDefinitionMiroirTest,
  entityDefinitionQuery,
  entityDefinitionReport,
  entityDefinitionRunner,
  entityDefinitionSelfApplication,
  entityDefinitionSelfApplicationModelBranch,
  entityDefinitionSelfApplicationVersion,
  entityDefinitionTestConfiguration,
  entityDefinitionTheme,
  entityEndpointVersion,
  entityEntity,
  entityEntityVersion,
  entityMlSchema,
  entityMenu,
  entityMiroirTest,
  entityQueryVersion,
  entityReport,
  entityRunner,
  entitySelfApplication,
  entitySelfApplicationModelBranch,
  entitySelfApplicationVersion,
  entityTestConfiguration,
  entityTheme,
  entityVersionEntityVersion,
  entityVersionHistoricalQueryVersion,
  entityVersionApplicationVersionCrossQueryVersion,
  entityVersionHistoricalReportVersion,
  entityVersionApplicationVersionCrossReportVersion,
  entityVersionHistoricalMenuVersion,
  entityVersionApplicationVersionCrossMenuVersion,
  entityVersionHistoricalEndpointVersion,
  entityVersionApplicationVersionCrossEndpointVersion,
  entityVersionHistoricalRunnerVersion,
  entityVersionApplicationVersionCrossRunnerVersion,
  entityVersionHistoricalThemeVersion,
  entityVersionApplicationVersionCrossThemeVersion,
  entityVersionHistoricalTransformerDefinitionVersion,
  entityVersionApplicationVersionCrossTransformerDefinitionVersion,
  instanceEndpointV1,
  instanceEndpointVersionV1,
  mlSchemaMlMiroirBootstrapSchema,
  localCacheEndpointVersionV1,
  materialStoredMiroirTheme,
  menuDefaultMiroir,
  miroirMlSchemaBootstrap,
  miroirTest_tr_admin_duplicateApplicationModel,
  miroirTest_fn_tools_alterObjectAtPath,
  miroirTest_fn_ansiColumnsToMlSchema,
  miroirTest_fn_mlsTypeCheck_buildAnyKeyMap,
  miroirTest_tr_defaultValueForMlSchema,
  miroirTest_action_domainController_dataCrud_compositePk,
  miroirTest_action_domainController_dataCrud,
  miroirTest_action_domainController_modelCrud,
  miroirTest_action_domainController_modelUndoRedo,
  miroirTest_action_domainController_freezeApplicationVersion,
  miroirTest_action_domainController_dataCrud_noParentUuid,
  miroirTest_action_domainController_dataCrud_nonUuidPk,
  miroirTest_action_domainController_modelCrud_nonUuidPk,
  miroirTest_fn_entityPrimaryKey,
  miroirTest_action_scenario_evolutionTrace,
  miroirTest_fn_postgres_attributeTypesFromMlSchema,
  miroirTest_fn_mlObjectFlatten,
  miroirTest_fn_mlSchemaReferences_list,
  miroirTest_fn_mlSchemaReferences_set,
  miroirTest_fn_mlsToCopilotKitParameter,
  miroirTest_fn_mlsToJsonSchema,
  miroirTest_fn_environment_deriveDeployments,
  miroirTest_fn_environment_resolveEnvironment,
  miroirTest_fn_mlsToMls_summary,
  miroirTest_fn_mlSchemaReferences_transitiveDependencySet,
  miroirTest_tr_mlsTypeCheck,
  miroirTest_fn_mlUnion_recursivelyUnfold,
  miroirTest_fn_mlsTypeCheck_unionResolvedTypeForArray,
  miroirTest_fn_mlsTypeCheck_unionResolvedTypeForObject,
  miroirTest_fn_mlsUnfoldSchemaOnce_localizeReferenceContext,
  miroirTest_tr_menuBuild,
  miroirTest_fn_mlsToMls_mergePositionBased,
  miroirTest_tr_metaModel_extractAttributes,
  miroirTest_tr_core,
  miroirTest_fn_modelUpdate,
  miroirTest_fn_mustache_extractDoubleBracePatterns,
  miroirTest_tr_resolveConditionalSchema_build,
  miroirTest_query_library_instances,
  miroirTest_tr_resolveConditionalSchema,
  miroirTest_fn_templates_resolveQueryTemplates,
  miroirTest_tr_resolveSchemaReferenceInContext,
  miroirTest_runner_createEntity,
  miroirTest_runner_dropEntity,
  miroirTest_runner_freezeApplicationVersion,
  miroirTest_runner_mcp_getInstances,
  miroirTest_runner_deployApplication,
  miroirTest_fn_mlsTypeCheck_selectUnionBranchFromDiscriminator,
  miroirTest_fn_tools_pathsAndMerges,
  miroirTest_fn_transformer_resultSchema,
  miroirTest_tr_unfoldSchemaOnce,
  miroirTest_ui_mlElementEditor_enum,
  miroirTest_ui_mlElementEditor_array,
  miroirTest_ui_mlElementEditor_literal,
  miroirTest_ui_mlElementEditor_object,
  miroirTest_ui_mlElementEditor_simpleType,
  miroirTest_ui_mlElementEditor_union,
  miroirTest_ui_mlElementEditor_any,
  miroirTest_ui_mlElementEditor_allTypesPattern,
  miroirTest_ui_mlElementEditor_renderPerformance,
  modelEndpointV1,
  queryVersionBundleProducerV1,
  persistenceEndpointVersionV1,
  queryEndpointVersionV1,
  reportApplicationEvolutionTraceDetails,
  reportApplicationEvolutionTraceHistory,
  reportApplicationEvolutionTraceList,
  reportApplicationList,
  reportApplicationModelBranchList,
  reportApplicationVersionList,
  reportApplicationVersionDetails,
  reportVersioning,
  reportEndpointVersionList,
  reportEntityDefinitionList,
  reportEntityList,
  reportEntityVersionList,
  reportMlSchemaList,
  reportMenuList,
  reportQueryList,
  reportReportList,
  reportRunnerDetails,
  reportRunnerList,
  reportTestConfigurationList,
  runnerDropApplication,
  runnerDropEntity,
  runnerFreezeApplicationVersion,
  selfApplicationMiroir,
  selfApplicationVersionInitialMiroirVersion,
  storeManagementEndpoint,
  testEndpointVersionV1,
  undoRedoEndpointVersionV1,
  entityCommit
} from "..";

export const defaultMiroirMetaModelEntityNameToAttributeName: Record<string, string> = {
  Entity: "entities",
  EntityVersion: "entityVersions",
  Endpoint: "endpoints",
  MlSchema: "mlSchemas",
  Menu: "menus",
  ApplicationVersion: "applicationVersions",
  Report: "reports",
  Runner: "runners",
  MiroirTest: "tests",
  Theme: "themes",
  ApplicationVersionCrossEntityDefinition: "applicationVersionCrossEntityVersion",
  ApplicationVersionCrossEntityVersion: "applicationVersionCrossEntityVersion",
  ApplicationVersionCrossQueryVersion: "applicationVersionCrossQueryVersion",
  QueryVersion: "queryVersions",
  ApplicationVersionCrossReportVersion: "applicationVersionCrossReportVersion",
  ReportVersion: "reportVersions",
  ApplicationVersionCrossMenuVersion: "applicationVersionCrossMenuVersion",
  MenuVersion: "menuVersions",
  ApplicationVersionCrossEndpointVersion: "applicationVersionCrossEndpointVersion",
  EndpointVersion: "endpointVersions",
  ApplicationVersionCrossRunnerVersion: "applicationVersionCrossRunnerVersion",
  RunnerVersion: "runnerVersions",
  ApplicationVersionCrossThemeVersion: "applicationVersionCrossThemeVersion",
  ThemeVersion: "themeVersions",
  ApplicationVersionCrossTransformerDefinitionVersion:
    "applicationVersionCrossTransformerDefinitionVersion",
  TransformerDefinitionVersion: "transformerDefinitionVersions",
};
export const defaultMiroirMetaModel: MetaModel = {
  applicationUuid: selfApplicationMiroir.uuid,
  applicationName: selfApplicationMiroir.name,
  // configuration: [instanceConfigurationReference],
  storedQueries: [],
  applications: [selfApplicationMiroir as SelfApplication],
  entities: [
    // this is used in tests, the bootstrap entities have to come first
    entityEntity as Entity,
    entityEntityVersion as Entity,
    //
    entityCommit as Entity,
    entityEndpointVersion as Entity,
    entityMlSchema as Entity, // null
    entityMenu as Entity,
    entityQueryVersion as Entity,
    entityReport as Entity,
    entityRunner as Entity,
    entitySelfApplication as Entity,
    entitySelfApplicationModelBranch as Entity,
    entitySelfApplicationVersion as Entity,
    entityMiroirTest as Entity,
    entityTestConfiguration as Entity,
    entityTheme as Entity,
    entityApplicationEvolutionTrace as Entity,
    entityApplicationEvolutionTraceEvent as Entity,
    entityApplicationVersionCrossEntityVersion as Entity,
    entityApplicationVersionCrossQueryVersion as Entity,
    entityHistoricalQueryVersion as Entity,
    entityApplicationVersionCrossReportVersion as Entity,
    entityHistoricalReportVersion as Entity,
    entityApplicationVersionCrossMenuVersion as Entity,
    entityHistoricalMenuVersion as Entity,
    entityApplicationVersionCrossEndpointVersion as Entity,
    entityHistoricalEndpointVersion as Entity,
    entityApplicationVersionCrossRunnerVersion as Entity,
    entityHistoricalRunnerVersion as Entity,
    entityApplicationVersionCrossThemeVersion as Entity,
    entityHistoricalThemeVersion as Entity,
    entityApplicationVersionCrossTransformerDefinitionVersion as Entity,
    entityHistoricalTransformerDefinitionVersion as Entity,
  ],
  entityVersions: [
    // bootstrap entities have to come first
    entityVersionEntityVersion as EntityVersion,
    entityDefinitionEntity as EntityVersion,
    //
    entityDefinitionEndpoint as EntityVersion,
    entityDefinitionMlSchema as EntityVersion, //
    entityDefinitionMenu as EntityVersion,
    entityDefinitionQuery as EntityVersion,
    entityDefinitionReport as EntityVersion,
    entityDefinitionRunner as EntityVersion,
    entityDefinitionSelfApplication as EntityVersion,
    entityDefinitionSelfApplicationModelBranch as EntityVersion,
    entityDefinitionSelfApplicationVersion as EntityVersion,
    entityDefinitionMiroirTest as EntityVersion,
    entityDefinitionTestConfiguration as EntityVersion,
    entityDefinitionTheme as EntityVersion,
    entityDefinitionApplicationEvolutionTrace as EntityVersion,
    entityDefinitionApplicationEvolutionTraceEvent as EntityVersion,
    entityDefinitionApplicationVersionCrossEntityDefinition as EntityVersion,
    entityVersionHistoricalQueryVersion as EntityVersion,
    entityVersionApplicationVersionCrossQueryVersion as EntityVersion,
    entityVersionHistoricalReportVersion as EntityVersion,
    entityVersionApplicationVersionCrossReportVersion as EntityVersion,
    entityVersionHistoricalMenuVersion as EntityVersion,
    entityVersionApplicationVersionCrossMenuVersion as EntityVersion,
    entityVersionHistoricalEndpointVersion as EntityVersion,
    entityVersionApplicationVersionCrossEndpointVersion as EntityVersion,
    entityVersionHistoricalRunnerVersion as EntityVersion,
    entityVersionApplicationVersionCrossRunnerVersion as EntityVersion,
    entityVersionHistoricalThemeVersion as EntityVersion,
    entityVersionApplicationVersionCrossThemeVersion as EntityVersion,
    entityVersionHistoricalTransformerDefinitionVersion as EntityVersion,
    entityVersionApplicationVersionCrossTransformerDefinitionVersion as EntityVersion,
  ],
  endpoints: [
    applicationEndpointV1 as any as EndpointDefinition,
    deploymentEndpointV1 as any as EndpointDefinition,
    instanceEndpointV1 as any as EndpointDefinition,
    modelEndpointV1 as any as EndpointDefinition,
    domainEndpointVersionV1 as any as EndpointDefinition,
    testEndpointVersionV1 as any as EndpointDefinition,
    storeManagementEndpoint as any as EndpointDefinition,
    instanceEndpointVersionV1 as any as EndpointDefinition,
    undoRedoEndpointVersionV1 as any as EndpointDefinition,
    localCacheEndpointVersionV1 as any as EndpointDefinition,
    queryEndpointVersionV1 as any as EndpointDefinition,
    persistenceEndpointVersionV1 as any as EndpointDefinition,
  ],
  mlSchemas: [mlSchemaMlMiroirBootstrapSchema as MlSchema],
  menus: [menuDefaultMiroir as Menu],
  applicationVersions: [selfApplicationVersionInitialMiroirVersion],
  reports: [
    // TODO: MISSING "DETAILS" REPORTS
    // reportApplicationDeploymentConfigurationList as Report,
    reportApplicationList as Report,
    reportApplicationModelBranchList as Report,
    reportApplicationVersionList as Report,
    reportApplicationVersionDetails as Report,
    reportVersioning as Report,
    reportApplicationEvolutionTraceList as Report,
    reportApplicationEvolutionTraceHistory as Report,
    reportApplicationEvolutionTraceDetails as Report,
    reportEndpointVersionList as Report,
    reportEntityVersionList as Report,
    reportEntityList as Report,
    reportMlSchemaList as Report,
    reportMenuList as Report,
    reportReportList as Report,
    reportRunnerList as Report,
    reportRunnerDetails as Report,
    reportTestConfigurationList as Report,
  ],
  runners: [
    runnerDropApplication as Runner,
    runnerDropEntity as any as Runner,
    runnerFreezeApplicationVersion as any as Runner,
  ],
  applicationVersionCrossEntityVersion: [
    applicationVersionInitialMiroirVersionCrossEntityDefinitionApplication,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionApplicationModelBranch,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionApplicationVersion,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionEntity,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionEntityDefinition,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionReport,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionStoreBasedConfiguration,
  ],
  applicationVersionCrossQueryVersion: [],
  queryVersions: [],
  applicationVersionCrossReportVersion: [],
  reportVersions: [],
  applicationVersionCrossMenuVersion: [],
  menuVersions: [],
  applicationVersionCrossEndpointVersion: [],
  endpointVersions: [],
  applicationVersionCrossRunnerVersion: [],
  runnerVersions: [],
  applicationVersionCrossThemeVersion: [],
  themeVersions: [],
  applicationVersionCrossTransformerDefinitionVersion: [],
  transformerDefinitionVersions: [],
  tests: [
    miroirTest_tr_admin_duplicateApplicationModel as MiroirTestDefinition,
    miroirTest_fn_tools_alterObjectAtPath as MiroirTestDefinition,
    miroirTest_fn_ansiColumnsToMlSchema as MiroirTestDefinition,
    miroirTest_fn_mlsTypeCheck_buildAnyKeyMap as MiroirTestDefinition,
    miroirTest_tr_defaultValueForMlSchema as MiroirTestDefinition,
    miroirTest_fn_entityPrimaryKey as MiroirTestDefinition,
    miroirTest_fn_postgres_attributeTypesFromMlSchema as MiroirTestDefinition,
    miroirTest_fn_mlObjectFlatten as MiroirTestDefinition,
    miroirTest_fn_mlSchemaReferences_list as MiroirTestDefinition,
    miroirTest_fn_mlSchemaReferences_set as MiroirTestDefinition,
    miroirTest_fn_mlsToCopilotKitParameter as MiroirTestDefinition,
    miroirTest_fn_mlsToJsonSchema as MiroirTestDefinition,
    miroirTest_fn_environment_deriveDeployments as MiroirTestDefinition,
    miroirTest_fn_environment_resolveEnvironment as MiroirTestDefinition,
    miroirTest_fn_mlsToMls_summary as MiroirTestDefinition,
    miroirTest_fn_mlSchemaReferences_transitiveDependencySet as MiroirTestDefinition,
    miroirTest_tr_mlsTypeCheck as MiroirTestDefinition,
    miroirTest_fn_mlUnion_recursivelyUnfold as MiroirTestDefinition,
    miroirTest_fn_mlsTypeCheck_unionResolvedTypeForArray as MiroirTestDefinition,
    miroirTest_fn_mlsTypeCheck_unionResolvedTypeForObject as MiroirTestDefinition,
    miroirTest_fn_mlsUnfoldSchemaOnce_localizeReferenceContext as MiroirTestDefinition,
    miroirTest_tr_menuBuild as MiroirTestDefinition,
    miroirTest_fn_mlsToMls_mergePositionBased as MiroirTestDefinition,
    miroirTest_tr_metaModel_extractAttributes as MiroirTestDefinition,
    miroirTest_tr_core as MiroirTestDefinition,
    miroirTest_fn_modelUpdate as MiroirTestDefinition,
    miroirTest_fn_mustache_extractDoubleBracePatterns as MiroirTestDefinition,
    miroirTest_tr_resolveConditionalSchema_build as MiroirTestDefinition,
    miroirTest_query_library_instances as MiroirTestDefinition,
    miroirTest_tr_resolveConditionalSchema as MiroirTestDefinition,
    miroirTest_fn_templates_resolveQueryTemplates as MiroirTestDefinition,
    miroirTest_tr_resolveSchemaReferenceInContext as MiroirTestDefinition,
    miroirTest_fn_mlsTypeCheck_selectUnionBranchFromDiscriminator as MiroirTestDefinition,
    miroirTest_fn_tools_pathsAndMerges as MiroirTestDefinition,
    miroirTest_fn_transformer_resultSchema as MiroirTestDefinition,
    miroirTest_tr_unfoldSchemaOnce as MiroirTestDefinition,
    miroirTest_action_domainController_dataCrud as MiroirTestDefinition,
    miroirTest_action_domainController_modelCrud as MiroirTestDefinition,
    miroirTest_action_domainController_dataCrud_compositePk as MiroirTestDefinition,
    miroirTest_action_domainController_modelCrud_nonUuidPk as MiroirTestDefinition,
    miroirTest_action_domainController_dataCrud_nonUuidPk as MiroirTestDefinition,
    miroirTest_action_domainController_dataCrud_noParentUuid as MiroirTestDefinition,
    miroirTest_action_domainController_modelUndoRedo as MiroirTestDefinition,
    miroirTest_action_domainController_freezeApplicationVersion as MiroirTestDefinition,
    miroirTest_action_scenario_evolutionTrace as MiroirTestDefinition,
    miroirTest_runner_createEntity as MiroirTestDefinition,
    miroirTest_runner_dropEntity as MiroirTestDefinition,
    miroirTest_runner_freezeApplicationVersion as MiroirTestDefinition,
    miroirTest_runner_mcp_getInstances as MiroirTestDefinition,
    miroirTest_runner_deployApplication as MiroirTestDefinition,
    miroirTest_ui_mlElementEditor_enum as MiroirTestDefinition,
    miroirTest_ui_mlElementEditor_array as MiroirTestDefinition,
    miroirTest_ui_mlElementEditor_literal as MiroirTestDefinition,
    miroirTest_ui_mlElementEditor_object as MiroirTestDefinition,
    miroirTest_ui_mlElementEditor_simpleType as MiroirTestDefinition,
    miroirTest_ui_mlElementEditor_union as MiroirTestDefinition,
    miroirTest_ui_mlElementEditor_any as MiroirTestDefinition,
    miroirTest_ui_mlElementEditor_allTypesPattern as MiroirTestDefinition,
    miroirTest_ui_mlElementEditor_renderPerformance as MiroirTestDefinition,
    // miroirTest_fn_mustache_extractDoubleBracePatterns as MiroirTestDefinition
  ],
  themes: [
    defaultStoredMiroirTheme,
    darkStoredMiroirTheme,
    compactStoredMiroirTheme,
    materialStoredMiroirTheme,
  ],
  transformerDefinitions: [],
};

function entitiesInBootstrapOrder(uuids: readonly string[]): Entity[] {
  const entityByUuid = new Map(
    defaultMiroirMetaModel.entities.map((entity) => [entity.uuid, entity as Entity]),
  );
  return uuids.map((uuid) => {
    const entity = entityByUuid.get(uuid);
    if (!entity) {
      throw new Error(`defaultMiroirMetaModel bootstrap: unknown entity uuid ${uuid}`);
    }
    return entity;
  });
}

/** EntityVersion rows upserted to Miroir data during modelInitialize. */
export const miroirModelInitializeEntityVersionInstances: EntityVersion[] = [
  entityDefinitionEntity as EntityVersion,
  entityDefinitionEntityDefinition as EntityVersion,
  entityDefinitionApplicationVersionCrossEntityDefinition as EntityVersion,
  entityVersionApplicationVersionCrossQueryVersion as EntityVersion,
  entityVersionHistoricalQueryVersion as EntityVersion,
  entityVersionApplicationVersionCrossReportVersion as EntityVersion,
  entityVersionHistoricalReportVersion as EntityVersion,
  entityVersionApplicationVersionCrossMenuVersion as EntityVersion,
  entityVersionHistoricalMenuVersion as EntityVersion,
  entityVersionApplicationVersionCrossEndpointVersion as EntityVersion,
  entityVersionHistoricalEndpointVersion as EntityVersion,
  entityVersionApplicationVersionCrossRunnerVersion as EntityVersion,
  entityVersionHistoricalRunnerVersion as EntityVersion,
  entityVersionApplicationVersionCrossThemeVersion as EntityVersion,
  entityVersionHistoricalThemeVersion as EntityVersion,
  entityVersionApplicationVersionCrossTransformerDefinitionVersion as EntityVersion,
  entityVersionHistoricalTransformerDefinitionVersion as EntityVersion,
];

/** EntityVersion rows upserted immediately after createEntity(entityEntityVersion). */
export const miroirModelInitializeEntityVersionsAfterEntityEntityVersion: EntityVersion[] =
  miroirModelInitializeEntityVersionInstances.filter(
    (ev) => ev.entityUuid === entityEntity.uuid || ev.entityUuid === entityEntityVersion.uuid,
  );

/** EntityVersion rows keyed by Entity.uuid — upsert after matching createEntity. */
export const miroirModelInitializeEntityVersionsByEntityUuid: ReadonlyMap<
  string,
  readonly EntityVersion[]
> = new Map(
  defaultMiroirMetaModel.entities.map((entity) => [
    entity.uuid,
    miroirModelInitializeEntityVersionInstances.filter((ev) => ev.entityUuid === entity.uuid),
  ]),
);

/** createEntity order for Miroir bootstrap (excludes meta Entity row). */
export const miroirModelInitializeCreateEntityOrder: Entity[] = entitiesInBootstrapOrder([
  entityEntityVersion.uuid!,
  entitySelfApplication.uuid!,
  entitySelfApplicationModelBranch.uuid!,
  entitySelfApplicationVersion.uuid!,
  entityEndpointVersion.uuid!,
  entityCommit.uuid!,
  entityMenu.uuid!,
  entityMlSchema.uuid!,
  entityReport.uuid!,
  entityRunner.uuid!,
  entityMiroirTest.uuid!,
  entityTestConfiguration.uuid!,
  entityTheme.uuid!,
  entityQueryVersion.uuid!,
  entityHistoricalQueryVersion.uuid!,
  entityApplicationEvolutionTrace.uuid!,
  entityApplicationEvolutionTraceEvent.uuid!,
  entityApplicationVersionCrossEntityVersion.uuid!,
  entityApplicationVersionCrossQueryVersion.uuid!,
  entityApplicationVersionCrossReportVersion.uuid!,
  entityHistoricalReportVersion.uuid!,
  entityApplicationVersionCrossMenuVersion.uuid!,
  entityHistoricalMenuVersion.uuid!,
  entityApplicationVersionCrossEndpointVersion.uuid!,
  entityHistoricalEndpointVersion.uuid!,
  entityApplicationVersionCrossRunnerVersion.uuid!,
  entityHistoricalRunnerVersion.uuid!,
  entityApplicationVersionCrossThemeVersion.uuid!,
  entityHistoricalThemeVersion.uuid!,
  entityApplicationVersionCrossTransformerDefinitionVersion.uuid!,
  entityHistoricalTransformerDefinitionVersion.uuid!,
]);

/** Non-entity instances upserted to Miroir data during bootstrap. */
export const miroirModelInitializeDataInstances: EntityInstance[] = [
  reportEndpointVersionList as EntityInstance,
  reportEntityDefinitionList as EntityInstance,
  reportEntityList as EntityInstance,
  reportApplicationList as EntityInstance,
  reportApplicationModelBranchList as EntityInstance,
  reportApplicationVersionList as EntityInstance,
  reportMenuList as EntityInstance,
  reportReportList as EntityInstance,
  reportMlSchemaList as EntityInstance,
  reportApplicationEvolutionTraceList as EntityInstance,
  reportApplicationEvolutionTraceHistory as EntityInstance,
  reportQueryList as EntityInstance,
  reportTestConfigurationList as EntityInstance,
  menuDefaultMiroir as EntityInstance,
  miroirMlSchemaBootstrap as EntityInstance,
  applicationEndpointV1 as EntityInstance,
  deploymentEndpointV1 as EntityInstance,
  instanceEndpointV1 as EntityInstance,
  modelEndpointV1 as EntityInstance,
  queryVersionBundleProducerV1 as EntityInstance,
  defaultStoredMiroirTheme as EntityInstance,
  darkStoredMiroirTheme as EntityInstance,
  compactStoredMiroirTheme as EntityInstance,
  materialStoredMiroirTheme as EntityInstance,
];

/** createModelStorageSpace order for application (app) bootstrap. */
export const appModelInitializeCreateEntityOrder: Entity[] = entitiesInBootstrapOrder([
  entityEntity.uuid!,
  entityEntityVersion.uuid!,
  entitySelfApplication.uuid!,
  entitySelfApplicationModelBranch.uuid!,
  entitySelfApplicationVersion.uuid!,
  entityMenu.uuid!,
  entityEndpointVersion.uuid!,
  entityMlSchema.uuid!,
  entityQueryVersion.uuid!,
  entityReport.uuid!,
  entityRunner.uuid!,
  entityMiroirTest.uuid!,
  entityTestConfiguration.uuid!,
  entityTheme.uuid!,
  entityApplicationEvolutionTrace.uuid!,
  entityApplicationEvolutionTraceEvent.uuid!,
  entityApplicationVersionCrossEntityVersion.uuid!,
]);
