"""#330: build the Library TestConfiguration of the Report MiroirTests.

`libraryBookDetailsSeed` is `libraryDocumentSeed` (entities, endpoints, instances) plus the
Reports under test in `testbedModel.reports` and the Library Menu in `testbedModel.menus`, so
that the testbed store holds them (the ConnectExternalServiceWizard adds its Report to the
Menu), and the Queries under test in `testbedModel.storedQueries` (#503: `report.queryDetails`
edits one). It is generated rather than edited, so that it follows the seed and the model assets.

Usage:
    python3 make_report_test_configuration.py           # write the TestConfiguration
    python3 make_report_test_configuration.py --check   # fail when the file is not up to date
"""
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[3]
LIBRARY_MODEL = REPO / "packages/miroir-example-library/assets/library_model"
TEST_CONFIGURATION_FOLDER = LIBRARY_MODEL / "675ccd46-7dd3-400b-a2bd-1319c39e11da"
SEED = TEST_CONFIGURATION_FOLDER / "d669558c-7cda-4037-81bf-0b9a71fbcb94.json"
REPORT_FOLDER = LIBRARY_MODEL / "3f2baa83-3ef7-45ce-82ea-6a43f7a8c916"
MENU_FOLDER = LIBRARY_MODEL / "dde4c883-ae6d-47c3-b6df-26bc6e3c1842"
QUERY_FOLDER = LIBRARY_MODEL / "e4320b9e-ab45-4abe-85d8-359604b3c62f"

UUID = "3123740d-2398-458f-82e6-4f1294866e39"
TARGET = TEST_CONFIGURATION_FOLDER / f"{UUID}.json"
REPORTS = ["c3503412-3d8a-43ef-a168-aa36e975e606"]  # BookDetails
MENUS = ["dd168e5a-2a21-4d2d-a443-032c6d15eb22"]  # the Library menu
QUERIES = ["6176dcdf-39a6-4805-8dc5-3c2366a31a11"]  # BookCountByPublisher (#503)


def build() -> str:
    seed = json.loads(SEED.read_text(encoding="utf-8"))
    reports = [
        json.loads((REPORT_FOLDER / f"{uuid}.json").read_text(encoding="utf-8")) for uuid in REPORTS
    ]
    menus = [json.loads((MENU_FOLDER / f"{uuid}.json").read_text(encoding="utf-8")) for uuid in MENUS]
    queries = [json.loads((QUERY_FOLDER / f"{uuid}.json").read_text(encoding="utf-8")) for uuid in QUERIES]
    configuration = {
        "uuid": UUID,
        "parentName": seed["parentName"],
        "parentUuid": seed["parentUuid"],
        "selfApplication": seed["selfApplication"],
        "name": "libraryBookDetailsSeed",
        "description": (
            "libraryDocumentSeed plus the BookDetails Report, the Library Menu and the "
            "BookCountByPublisher Query, for the Report MiroirTests (#330, #503). "
            "Generated by code-helpers/features/330-FEATURE-report-level-miroir-tests/"
            "make_report_test_configuration.py: do not edit."
        ),
        "testbedModel": {**seed["testbedModel"], "reports": reports, "menus": menus, "storedQueries": queries},
        "testbedEntitiesAndInstances": seed["testbedEntitiesAndInstances"],
    }
    return json.dumps(configuration, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    content = build()
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != content:
            print(f"{TARGET} is not up to date: run {pathlib.Path(__file__).name}")
            return 1
        return 0
    TARGET.write_text(content, encoding="utf-8")
    print("written:", TARGET)
    return 0


if __name__ == "__main__":
    sys.exit(main())
