import type {
  EndpointDefinition,
  Entity,
  EntityInstance,
  EntityVersion,
  Menu,
  MetaModel,
  MiroirTestDefinition,
  MlSchema,
  Report,
  Runner,
  SelfApplication,
} from "miroir-core";
import {
  applicationEndpointV1,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionApplication,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionApplicationModelBranch,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionApplicationVersion,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionEntity,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionEntityDefinition,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionReport,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionStoreBasedConfiguration,
  compactStoredMiroirTheme,
  darkStoredMiroirTheme,
  defaultStoredMiroirTheme,
  deploymentEndpointV1,
  domainEndpointVersionV1,
  entityApplicationEvolutionTrace,
  entityApplicationEvolutionTraceEvent,
  entityApplicationVersionCrossEntityVersion,
  entityApplicationVersionCrossQueryVersion,
  entityHistoricalQueryVersion,
  entityHistoricalReportVersion,
  entityApplicationVersionCrossReportVersion,
  entityHistoricalMenuVersion,
  entityApplicationVersionCrossMenuVersion,
  entityHistoricalEndpointVersion,
  entityApplicationVersionCrossEndpointVersion,
  entityHistoricalRunnerVersion,
  entityApplicationVersionCrossRunnerVersion,
  entityHistoricalThemeVersion,
  entityApplicationVersionCrossThemeVersion,
  entityHistoricalTransformerDefinitionVersion,
  entityApplicationVersionCrossTransformerDefinitionVersion,
  entityDefinitionApplicationEvolutionTrace,
  entityDefinitionApplicationEvolutionTraceEvent,
  entityDefinitionApplicationVersionCrossEntityDefinition,
  entityDefinitionEndpoint,
  entityDefinitionEntity,
  entityDefinitionEntityDefinition,
  entityDefinitionMlSchema,
  entityDefinitionMenu,
  entityDefinitionMiroirTest,
  entityDefinitionQuery,
  entityDefinitionReport,
  entityDefinitionRunner,
  entityDefinitionSelfApplication,
  entityDefinitionSelfApplicationModelBranch,
  entityDefinitionSelfApplicationVersion,
  entityDefinitionTestConfiguration,
  entityDefinitionTheme,
  entityEndpointVersion,
  entityEntity,
  entityEntityVersion,
  entityMlSchema,
  entityMenu,
  entityMiroirTest,
  entityQueryVersion,
  entityReport,
  entityRunner,
  entitySelfApplication,
  entitySelfApplicationModelBranch,
  entitySelfApplicationVersion,
  entityTestConfiguration,
  entityTheme,
  entityVersionEntityVersion,
  entityVersionHistoricalQueryVersion,
  entityVersionApplicationVersionCrossQueryVersion,
  entityVersionHistoricalReportVersion,
  entityVersionApplicationVersionCrossReportVersion,
  entityVersionHistoricalMenuVersion,
  entityVersionApplicationVersionCrossMenuVersion,
  entityVersionHistoricalEndpointVersion,
  entityVersionApplicationVersionCrossEndpointVersion,
  entityVersionHistoricalRunnerVersion,
  entityVersionApplicationVersionCrossRunnerVersion,
  entityVersionHistoricalThemeVersion,
  entityVersionApplicationVersionCrossThemeVersion,
  entityVersionHistoricalTransformerDefinitionVersion,
  entityVersionApplicationVersionCrossTransformerDefinitionVersion,
  instanceEndpointV1,
  instanceEndpointVersionV1,
  mlSchemaMlMiroirBootstrapSchema,
  localCacheEndpointVersionV1,
  materialStoredMiroirTheme,
  menuDefaultMiroir,
  miroirMlSchemaBootstrap,
  miroirTest_adminTransformers,
  miroirTest_alterObject_atPath,
  miroirTest_ansiColumnsToMlSchema,
  miroirTest_buildAnyKeyMap,
  miroirTest_defaultValueForMLSchema,
  miroirTest_domain_controller_composite_pk_crud,
  miroirTest_domain_controller_data_crud,
  miroirTest_domain_controller_model_crud,
  miroirTest_domain_controller_model_undo_redo,
  miroirTest_domain_controller_application_version_freeze,
  miroirTest_domain_controller_no_parent_uuid_crud,
  miroirTest_domain_controller_non_uuid_pk_data_crud,
  miroirTest_domain_controller_non_uuid_pk_model_crud,
  miroirTest_EntityPrimaryKey,
  miroirTest_evolutionTraceWP1,
  miroirTest_getAttributeTypesFromMlSchema,
  miroirTest_mlObjectFlatten,
  miroirTest_MlSchemaReferencesList,
  miroirTest_MlSchemaReferencesSet,
  miroirTest_mlsToCopilotKitParameter,
  miroirTest_mlsToJsonSchema,
  miroirTest_mlsToMls_Summary,
  miroirTest_mlsTransitiveDependencySet,
  miroirTest_mlsTypeCheck_TransformerTestSuite,
  miroirTest_mlUnion_RecursiveUnfold,
  miroirTest_mlUnionResolvedTypeForArray,
  miroirTest_mlUnionResolvedTypeForObject,
  miroirTest_localizeMlSchemaReferenceContext,
  miroirTest_menu_build,
  miroirTest_mergePositionBased,
  miroirTest_metaModelTransformersTest,
  miroirTest_miroirCoreTransformers,
  miroirTest_modelUpdates,
  miroirTest_mustache,
  miroirTest_pilot_transformer_plus,
  miroirTest_queries_library,
  miroirTest_resolveConditionalSchema,
  miroirTest_resolveQueryTemplates,
  miroirTest_resolveSchemaReferenceInContext,
  miroirTest_runner_create_entity,
  miroirTest_runner_drop_entity,
  miroirTest_runner_freeze_application_version,
  miroirTest_runner_mcp_get_instances,
  miroirTest_selectUnionBranchFromDiscriminator,
  miroirTest_tools,
  miroirTest_transformerResultSchema,
  miroirTest_unfoldSchemaOnce,
  miroirTest_MlEnumEditor_ComponentTestSuite,
  miroirTest_MlArrayEditor_ComponentTestSuite,
  miroirTest_MlLiteralEditor_ComponentTestSuite,
  miroirTest_MlObjectEditor_ComponentTestSuite,
  miroirTest_MlSimpleTypeEditor_ComponentTestSuite,
  miroirTest_MlUnionEditor_ComponentTestSuite,
  miroirTest_MlAnyEditor_ComponentTestSuite,
  miroirTest_MlTestPattern_ComponentTestSuite,
  miroirTest_MlEditorRenderPerformance_ComponentTestSuite,
  modelEndpointV1,
  queryVersionBundleProducerV1,
  persistenceEndpointVersionV1,
  queryEndpointVersionV1,
  reportApplicationEvolutionTraceDetails,
  reportApplicationEvolutionTraceHistory,
  reportApplicationEvolutionTraceList,
  reportApplicationList,
  reportApplicationModelBranchList,
  reportApplicationVersionList,
  reportApplicationVersionDetails,
  reportVersioning,
  reportEndpointVersionList,
  reportEntityDefinitionList,
  reportEntityList,
  reportEntityVersionList,
  reportMlSchemaList,
  reportMenuList,
  reportQueryList,
  reportReportList,
  reportRunnerDetails,
  reportRunnerList,
  reportTestConfigurationList,
  runnerDropApplication,
  runnerDropEntity,
  runnerFreezeApplicationVersion,
  selfApplicationMiroir,
  selfApplicationVersionInitialMiroirVersion,
  storeManagementEndpoint,
  testEndpointVersionV1,
  undoRedoEndpointVersionV1,
  entityCommit
} from "..";

export const defaultMiroirMetaModelEntityNameToAttributeName: Record<string, string> = {
  Entity: "entities",
  EntityVersion: "entityVersions",
  Endpoint: "endpoints",
  MlSchema: "mlSchemas",
  Menu: "menus",
  ApplicationVersion: "applicationVersions",
  Report: "reports",
  Runner: "runners",
  MiroirTest: "tests",
  Theme: "themes",
  ApplicationVersionCrossEntityDefinition: "applicationVersionCrossEntityVersion",
  ApplicationVersionCrossEntityVersion: "applicationVersionCrossEntityVersion",
  ApplicationVersionCrossQueryVersion: "applicationVersionCrossQueryVersion",
  QueryVersion: "queryVersions",
  ApplicationVersionCrossReportVersion: "applicationVersionCrossReportVersion",
  ReportVersion: "reportVersions",
  ApplicationVersionCrossMenuVersion: "applicationVersionCrossMenuVersion",
  MenuVersion: "menuVersions",
  ApplicationVersionCrossEndpointVersion: "applicationVersionCrossEndpointVersion",
  EndpointVersion: "endpointVersions",
  ApplicationVersionCrossRunnerVersion: "applicationVersionCrossRunnerVersion",
  RunnerVersion: "runnerVersions",
  ApplicationVersionCrossThemeVersion: "applicationVersionCrossThemeVersion",
  ThemeVersion: "themeVersions",
  ApplicationVersionCrossTransformerDefinitionVersion:
    "applicationVersionCrossTransformerDefinitionVersion",
  TransformerDefinitionVersion: "transformerDefinitionVersions",
};
export const defaultMiroirMetaModel: MetaModel = {
  applicationUuid: selfApplicationMiroir.uuid,
  applicationName: selfApplicationMiroir.name,
  // configuration: [instanceConfigurationReference],
  storedQueries: [],
  applications: [selfApplicationMiroir as SelfApplication],
  entities: [
    // this is used in tests, the bootstrap entities have to come first
    entityEntity as Entity,
    entityEntityVersion as Entity,
    //
    entityCommit as Entity,
    entityEndpointVersion as Entity,
    entityMlSchema as Entity, // null
    entityMenu as Entity,
    entityQueryVersion as Entity,
    entityReport as Entity,
    entityRunner as Entity,
    entitySelfApplication as Entity,
    entitySelfApplicationModelBranch as Entity,
    entitySelfApplicationVersion as Entity,
    entityMiroirTest as Entity,
    entityTestConfiguration as Entity,
    entityTheme as Entity,
    entityApplicationEvolutionTrace as Entity,
    entityApplicationEvolutionTraceEvent as Entity,
    entityApplicationVersionCrossEntityVersion as Entity,
    entityApplicationVersionCrossQueryVersion as Entity,
    entityHistoricalQueryVersion as Entity,
    entityApplicationVersionCrossReportVersion as Entity,
    entityHistoricalReportVersion as Entity,
    entityApplicationVersionCrossMenuVersion as Entity,
    entityHistoricalMenuVersion as Entity,
    entityApplicationVersionCrossEndpointVersion as Entity,
    entityHistoricalEndpointVersion as Entity,
    entityApplicationVersionCrossRunnerVersion as Entity,
    entityHistoricalRunnerVersion as Entity,
    entityApplicationVersionCrossThemeVersion as Entity,
    entityHistoricalThemeVersion as Entity,
    entityApplicationVersionCrossTransformerDefinitionVersion as Entity,
    entityHistoricalTransformerDefinitionVersion as Entity,
  ],
  entityVersions: [
    // bootstrap entities have to come first
    entityVersionEntityVersion as EntityVersion,
    entityDefinitionEntity as EntityVersion,
    //
    entityDefinitionEndpoint as EntityVersion,
    entityDefinitionMlSchema as EntityVersion, //
    entityDefinitionMenu as EntityVersion,
    entityDefinitionQuery as EntityVersion,
    entityDefinitionReport as EntityVersion,
    entityDefinitionRunner as EntityVersion,
    entityDefinitionSelfApplication as EntityVersion,
    entityDefinitionSelfApplicationModelBranch as EntityVersion,
    entityDefinitionSelfApplicationVersion as EntityVersion,
    entityDefinitionMiroirTest as EntityVersion,
    entityDefinitionTestConfiguration as EntityVersion,
    entityDefinitionTheme as EntityVersion,
    entityDefinitionApplicationEvolutionTrace as EntityVersion,
    entityDefinitionApplicationEvolutionTraceEvent as EntityVersion,
    entityDefinitionApplicationVersionCrossEntityDefinition as EntityVersion,
    entityVersionHistoricalQueryVersion as EntityVersion,
    entityVersionApplicationVersionCrossQueryVersion as EntityVersion,
    entityVersionHistoricalReportVersion as EntityVersion,
    entityVersionApplicationVersionCrossReportVersion as EntityVersion,
    entityVersionHistoricalMenuVersion as EntityVersion,
    entityVersionApplicationVersionCrossMenuVersion as EntityVersion,
    entityVersionHistoricalEndpointVersion as EntityVersion,
    entityVersionApplicationVersionCrossEndpointVersion as EntityVersion,
    entityVersionHistoricalRunnerVersion as EntityVersion,
    entityVersionApplicationVersionCrossRunnerVersion as EntityVersion,
    entityVersionHistoricalThemeVersion as EntityVersion,
    entityVersionApplicationVersionCrossThemeVersion as EntityVersion,
    entityVersionHistoricalTransformerDefinitionVersion as EntityVersion,
    entityVersionApplicationVersionCrossTransformerDefinitionVersion as EntityVersion,
  ],
  endpoints: [
    applicationEndpointV1 as any as EndpointDefinition,
    deploymentEndpointV1 as any as EndpointDefinition,
    instanceEndpointV1 as any as EndpointDefinition,
    modelEndpointV1 as any as EndpointDefinition,
    domainEndpointVersionV1 as any as EndpointDefinition,
    testEndpointVersionV1 as any as EndpointDefinition,
    storeManagementEndpoint as any as EndpointDefinition,
    instanceEndpointVersionV1 as any as EndpointDefinition,
    undoRedoEndpointVersionV1 as any as EndpointDefinition,
    localCacheEndpointVersionV1 as any as EndpointDefinition,
    queryEndpointVersionV1 as any as EndpointDefinition,
    persistenceEndpointVersionV1 as any as EndpointDefinition,
  ],
  mlSchemas: [mlSchemaMlMiroirBootstrapSchema as MlSchema],
  menus: [menuDefaultMiroir as Menu],
  applicationVersions: [selfApplicationVersionInitialMiroirVersion],
  reports: [
    // TODO: MISSING "DETAILS" REPORTS
    // reportApplicationDeploymentConfigurationList as Report,
    reportApplicationList as Report,
    reportApplicationModelBranchList as Report,
    reportApplicationVersionList as Report,
    reportApplicationVersionDetails as Report,
    reportVersioning as Report,
    reportApplicationEvolutionTraceList as Report,
    reportApplicationEvolutionTraceHistory as Report,
    reportApplicationEvolutionTraceDetails as Report,
    reportEndpointVersionList as Report,
    reportEntityVersionList as Report,
    reportEntityList as Report,
    reportMlSchemaList as Report,
    reportMenuList as Report,
    reportReportList as Report,
    reportRunnerList as Report,
    reportRunnerDetails as Report,
    reportTestConfigurationList as Report,
  ],
  runners: [
    runnerDropApplication as Runner,
    runnerDropEntity as any as Runner,
    runnerFreezeApplicationVersion as any as Runner,
  ],
  applicationVersionCrossEntityVersion: [
    applicationVersionInitialMiroirVersionCrossEntityDefinitionApplication,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionApplicationModelBranch,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionApplicationVersion,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionEntity,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionEntityDefinition,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionReport,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionStoreBasedConfiguration,
  ],
  applicationVersionCrossQueryVersion: [],
  queryVersions: [],
  applicationVersionCrossReportVersion: [],
  reportVersions: [],
  applicationVersionCrossMenuVersion: [],
  menuVersions: [],
  applicationVersionCrossEndpointVersion: [],
  endpointVersions: [],
  applicationVersionCrossRunnerVersion: [],
  runnerVersions: [],
  applicationVersionCrossThemeVersion: [],
  themeVersions: [],
  applicationVersionCrossTransformerDefinitionVersion: [],
  transformerDefinitionVersions: [],
  tests: [
    miroirTest_adminTransformers as MiroirTestDefinition,
    miroirTest_alterObject_atPath as MiroirTestDefinition,
    miroirTest_ansiColumnsToMlSchema as MiroirTestDefinition,
    miroirTest_buildAnyKeyMap as MiroirTestDefinition,
    miroirTest_defaultValueForMLSchema as MiroirTestDefinition,
    miroirTest_EntityPrimaryKey as MiroirTestDefinition,
    miroirTest_getAttributeTypesFromMlSchema as MiroirTestDefinition,
    miroirTest_mlObjectFlatten as MiroirTestDefinition,
    miroirTest_MlSchemaReferencesList as MiroirTestDefinition,
    miroirTest_MlSchemaReferencesSet as MiroirTestDefinition,
    miroirTest_mlsToCopilotKitParameter as MiroirTestDefinition,
    miroirTest_mlsToJsonSchema as MiroirTestDefinition,
    miroirTest_mlsToMls_Summary as MiroirTestDefinition,
    miroirTest_mlsTransitiveDependencySet as MiroirTestDefinition,
    miroirTest_mlsTypeCheck_TransformerTestSuite as MiroirTestDefinition,
    miroirTest_mlUnion_RecursiveUnfold as MiroirTestDefinition,
    miroirTest_mlUnionResolvedTypeForArray as MiroirTestDefinition,
    miroirTest_mlUnionResolvedTypeForObject as MiroirTestDefinition,
    miroirTest_localizeMlSchemaReferenceContext as MiroirTestDefinition,
    miroirTest_menu_build as MiroirTestDefinition,
    miroirTest_mergePositionBased as MiroirTestDefinition,
    miroirTest_metaModelTransformersTest as MiroirTestDefinition,
    miroirTest_miroirCoreTransformers as MiroirTestDefinition,
    miroirTest_modelUpdates as MiroirTestDefinition,
    miroirTest_mustache as MiroirTestDefinition,
    miroirTest_pilot_transformer_plus as MiroirTestDefinition,
    miroirTest_queries_library as MiroirTestDefinition,
    miroirTest_resolveConditionalSchema as MiroirTestDefinition,
    miroirTest_resolveQueryTemplates as MiroirTestDefinition,
    miroirTest_resolveSchemaReferenceInContext as MiroirTestDefinition,
    miroirTest_selectUnionBranchFromDiscriminator as MiroirTestDefinition,
    miroirTest_tools as MiroirTestDefinition,
    miroirTest_transformerResultSchema as MiroirTestDefinition,
    miroirTest_unfoldSchemaOnce as MiroirTestDefinition,
    miroirTest_domain_controller_data_crud as MiroirTestDefinition,
    miroirTest_domain_controller_model_crud as MiroirTestDefinition,
    miroirTest_domain_controller_composite_pk_crud as MiroirTestDefinition,
    miroirTest_domain_controller_non_uuid_pk_model_crud as MiroirTestDefinition,
    miroirTest_domain_controller_non_uuid_pk_data_crud as MiroirTestDefinition,
    miroirTest_domain_controller_no_parent_uuid_crud as MiroirTestDefinition,
    miroirTest_domain_controller_model_undo_redo as MiroirTestDefinition,
    miroirTest_domain_controller_application_version_freeze as MiroirTestDefinition,
    miroirTest_evolutionTraceWP1 as MiroirTestDefinition,
    miroirTest_runner_create_entity as MiroirTestDefinition,
    miroirTest_runner_drop_entity as MiroirTestDefinition,
    miroirTest_runner_freeze_application_version as MiroirTestDefinition,
    miroirTest_runner_mcp_get_instances as MiroirTestDefinition,
    miroirTest_MlEnumEditor_ComponentTestSuite as MiroirTestDefinition,
    miroirTest_MlArrayEditor_ComponentTestSuite as MiroirTestDefinition,
    miroirTest_MlLiteralEditor_ComponentTestSuite as MiroirTestDefinition,
    miroirTest_MlObjectEditor_ComponentTestSuite as MiroirTestDefinition,
    miroirTest_MlSimpleTypeEditor_ComponentTestSuite as MiroirTestDefinition,
    miroirTest_MlUnionEditor_ComponentTestSuite as MiroirTestDefinition,
    miroirTest_MlAnyEditor_ComponentTestSuite as MiroirTestDefinition,
    miroirTest_MlTestPattern_ComponentTestSuite as MiroirTestDefinition,
    miroirTest_MlEditorRenderPerformance_ComponentTestSuite as MiroirTestDefinition,
    // miroirTest_mustache as MiroirTestDefinition
  ],
  themes: [
    defaultStoredMiroirTheme,
    darkStoredMiroirTheme,
    compactStoredMiroirTheme,
    materialStoredMiroirTheme,
  ],
  transformerDefinitions: [],
};

function entitiesInBootstrapOrder(uuids: readonly string[]): Entity[] {
  const entityByUuid = new Map(
    defaultMiroirMetaModel.entities.map((entity) => [entity.uuid, entity as Entity]),
  );
  return uuids.map((uuid) => {
    const entity = entityByUuid.get(uuid);
    if (!entity) {
      throw new Error(`defaultMiroirMetaModel bootstrap: unknown entity uuid ${uuid}`);
    }
    return entity;
  });
}

/** EntityVersion rows upserted to Miroir data during modelInitialize. */
export const miroirModelInitializeEntityVersionInstances: EntityVersion[] = [
  entityDefinitionEntity as EntityVersion,
  entityDefinitionEntityDefinition as EntityVersion,
  entityDefinitionApplicationVersionCrossEntityDefinition as EntityVersion,
  entityVersionApplicationVersionCrossQueryVersion as EntityVersion,
  entityVersionHistoricalQueryVersion as EntityVersion,
  entityVersionApplicationVersionCrossReportVersion as EntityVersion,
  entityVersionHistoricalReportVersion as EntityVersion,
  entityVersionApplicationVersionCrossMenuVersion as EntityVersion,
  entityVersionHistoricalMenuVersion as EntityVersion,
  entityVersionApplicationVersionCrossEndpointVersion as EntityVersion,
  entityVersionHistoricalEndpointVersion as EntityVersion,
  entityVersionApplicationVersionCrossRunnerVersion as EntityVersion,
  entityVersionHistoricalRunnerVersion as EntityVersion,
  entityVersionApplicationVersionCrossThemeVersion as EntityVersion,
  entityVersionHistoricalThemeVersion as EntityVersion,
  entityVersionApplicationVersionCrossTransformerDefinitionVersion as EntityVersion,
  entityVersionHistoricalTransformerDefinitionVersion as EntityVersion,
];

/** EntityVersion rows upserted immediately after createEntity(entityEntityVersion). */
export const miroirModelInitializeEntityVersionsAfterEntityEntityVersion: EntityVersion[] =
  miroirModelInitializeEntityVersionInstances.filter(
    (ev) => ev.entityUuid === entityEntity.uuid || ev.entityUuid === entityEntityVersion.uuid,
  );

/** EntityVersion rows keyed by Entity.uuid — upsert after matching createEntity. */
export const miroirModelInitializeEntityVersionsByEntityUuid: ReadonlyMap<
  string,
  readonly EntityVersion[]
> = new Map(
  defaultMiroirMetaModel.entities.map((entity) => [
    entity.uuid,
    miroirModelInitializeEntityVersionInstances.filter((ev) => ev.entityUuid === entity.uuid),
  ]),
);

/** createEntity order for Miroir bootstrap (excludes meta Entity row). */
export const miroirModelInitializeCreateEntityOrder: Entity[] = entitiesInBootstrapOrder([
  entityEntityVersion.uuid!,
  entitySelfApplication.uuid!,
  entitySelfApplicationModelBranch.uuid!,
  entitySelfApplicationVersion.uuid!,
  entityEndpointVersion.uuid!,
  entityCommit.uuid!,
  entityMenu.uuid!,
  entityMlSchema.uuid!,
  entityReport.uuid!,
  entityRunner.uuid!,
  entityMiroirTest.uuid!,
  entityTestConfiguration.uuid!,
  entityTheme.uuid!,
  entityQueryVersion.uuid!,
  entityHistoricalQueryVersion.uuid!,
  entityApplicationEvolutionTrace.uuid!,
  entityApplicationEvolutionTraceEvent.uuid!,
  entityApplicationVersionCrossEntityVersion.uuid!,
  entityApplicationVersionCrossQueryVersion.uuid!,
  entityApplicationVersionCrossReportVersion.uuid!,
  entityHistoricalReportVersion.uuid!,
  entityApplicationVersionCrossMenuVersion.uuid!,
  entityHistoricalMenuVersion.uuid!,
  entityApplicationVersionCrossEndpointVersion.uuid!,
  entityHistoricalEndpointVersion.uuid!,
  entityApplicationVersionCrossRunnerVersion.uuid!,
  entityHistoricalRunnerVersion.uuid!,
  entityApplicationVersionCrossThemeVersion.uuid!,
  entityHistoricalThemeVersion.uuid!,
  entityApplicationVersionCrossTransformerDefinitionVersion.uuid!,
  entityHistoricalTransformerDefinitionVersion.uuid!,
]);

/** Non-entity instances upserted to Miroir data during bootstrap. */
export const miroirModelInitializeDataInstances: EntityInstance[] = [
  reportEndpointVersionList as EntityInstance,
  reportEntityDefinitionList as EntityInstance,
  reportEntityList as EntityInstance,
  reportApplicationList as EntityInstance,
  reportApplicationModelBranchList as EntityInstance,
  reportApplicationVersionList as EntityInstance,
  reportMenuList as EntityInstance,
  reportReportList as EntityInstance,
  reportMlSchemaList as EntityInstance,
  reportApplicationEvolutionTraceList as EntityInstance,
  reportApplicationEvolutionTraceHistory as EntityInstance,
  reportQueryList as EntityInstance,
  reportTestConfigurationList as EntityInstance,
  menuDefaultMiroir as EntityInstance,
  miroirMlSchemaBootstrap as EntityInstance,
  applicationEndpointV1 as EntityInstance,
  deploymentEndpointV1 as EntityInstance,
  instanceEndpointV1 as EntityInstance,
  modelEndpointV1 as EntityInstance,
  queryVersionBundleProducerV1 as EntityInstance,
  defaultStoredMiroirTheme as EntityInstance,
  darkStoredMiroirTheme as EntityInstance,
  compactStoredMiroirTheme as EntityInstance,
  materialStoredMiroirTheme as EntityInstance,
];

/** createModelStorageSpace order for application (app) bootstrap. */
export const appModelInitializeCreateEntityOrder: Entity[] = entitiesInBootstrapOrder([
  entityEntity.uuid!,
  entityEntityVersion.uuid!,
  entitySelfApplication.uuid!,
  entitySelfApplicationModelBranch.uuid!,
  entitySelfApplicationVersion.uuid!,
  entityMenu.uuid!,
  entityEndpointVersion.uuid!,
  entityMlSchema.uuid!,
  entityQueryVersion.uuid!,
  entityReport.uuid!,
  entityRunner.uuid!,
  entityMiroirTest.uuid!,
  entityTestConfiguration.uuid!,
  entityTheme.uuid!,
  entityApplicationEvolutionTrace.uuid!,
  entityApplicationEvolutionTraceEvent.uuid!,
  entityApplicationVersionCrossEntityVersion.uuid!,
]);
