import type {
  EndpointDefinition,
  Entity,
  EntityInstance,
  EntityVersion,
  Menu,
  MetaModel,
  MiroirTestDefinition,
  MlSchema,
  Report,
  Runner,
  SelfApplication,
} from "miroir-core";
import {
  applicationEndpointV1,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionApplication,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionApplicationModelBranch,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionApplicationVersion,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionEntity,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionEntityDefinition,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionReport,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionStoreBasedConfiguration,
  compactStoredMiroirTheme,
  darkStoredMiroirTheme,
  defaultStoredMiroirTheme,
  deploymentEndpointV1,
  domainEndpointVersionV1,
  entityApplicationEvolutionTrace,
  entityApplicationEvolutionTraceEvent,
  entityApplicationVersionCrossEntityVersion,
  entityApplicationVersionCrossQueryVersion,
  entityHistoricalQueryVersion,
  entityHistoricalReportVersion,
  entityApplicationVersionCrossReportVersion,
  entityHistoricalMenuVersion,
  entityApplicationVersionCrossMenuVersion,
  entityHistoricalEndpointVersion,
  entityApplicationVersionCrossEndpointVersion,
  entityHistoricalRunnerVersion,
  entityApplicationVersionCrossRunnerVersion,
  entityDefinitionApplicationEvolutionTrace,
  entityDefinitionApplicationEvolutionTraceEvent,
  entityDefinitionApplicationVersionCrossEntityDefinition,
  entityDefinitionEndpoint,
  entityDefinitionEntity,
  entityDefinitionEntityDefinition,
  entityDefinitionJzodSchema,
  entityDefinitionMenu,
  entityDefinitionMiroirTest,
  entityDefinitionQuery,
  entityDefinitionReport,
  entityDefinitionRunner,
  entityDefinitionSelfApplication,
  entityDefinitionSelfApplicationModelBranch,
  entityDefinitionSelfApplicationVersion,
  entityDefinitionTheme,
  entityEndpointVersion,
  entityEntity,
  entityEntityVersion,
  entityJzodSchema,
  entityMenu,
  entityMiroirTest,
  entityQueryVersion,
  entityReport,
  entityRunner,
  entitySelfApplication,
  entitySelfApplicationModelBranch,
  entitySelfApplicationVersion,
  entityTheme,
  entityVersionEntityVersion,
  entityVersionHistoricalQueryVersion,
  entityVersionApplicationVersionCrossQueryVersion,
  entityVersionHistoricalReportVersion,
  entityVersionApplicationVersionCrossReportVersion,
  entityVersionHistoricalMenuVersion,
  entityVersionApplicationVersionCrossMenuVersion,
  entityVersionHistoricalEndpointVersion,
  entityVersionApplicationVersionCrossEndpointVersion,
  entityVersionHistoricalRunnerVersion,
  entityVersionApplicationVersionCrossRunnerVersion,
  instanceEndpointV1,
  instanceEndpointVersionV1,
  jzodSchemajzodMiroirBootstrapSchema,
  localCacheEndpointVersionV1,
  materialStoredMiroirTheme,
  menuDefaultMiroir,
  miroirJzodSchemaBootstrap,
  miroirTest_adminTransformers,
  miroirTest_alterObject,
  miroirTest_ansiColumnsToJzodSchema,
  miroirTest_buildAnyKeyMap,
  miroirTest_defaultValueForMLSchema,
  miroirTest_domain_controller_composite_pk_crud,
  miroirTest_domain_controller_data_crud,
  miroirTest_domain_controller_model_crud,
  miroirTest_domain_controller_model_undo_redo,
  miroirTest_domain_controller_application_version_freeze,
  miroirTest_domain_controller_no_parent_uuid_crud,
  miroirTest_domain_controller_non_uuid_pk_data_crud,
  miroirTest_domain_controller_non_uuid_pk_model_crud,
  miroirTest_EntityPrimaryKey,
  miroirTest_evolutionTraceWP1,
  miroirTest_getAttributeTypesFromJzodSchema,
  miroirTest_jzodObjectFlatten,
  miroirTest_JzodSchemaReferencesList,
  miroirTest_JzodSchemaReferencesSet,
  miroirTest_jzodToCopilotKitParameter,
  miroirTest_jzodToJsonSchema,
  miroirTest_jzodToJzod_Summary,
  miroirTest_jzodTransitiveDependencySet,
  miroirTest_jzodTypeCheck,
  miroirTest_jzodUnion_RecursiveUnfold,
  miroirTest_jzodUnionResolvedTypeForArray,
  miroirTest_jzodUnionResolvedTypeForObject,
  miroirTest_localizeJzodSchemaReferenceContext,
  miroirTest_menu,
  miroirTest_mergePositionBased,
  miroirTest_metaModelTransformers,
  miroirTest_miroirCoreTransformers,
  miroirTest_modelUpdates,
  miroirTest_mustache,
  miroirTest_pilot_transformer_plus,
  miroirTest_queries_library,
  miroirTest_resolveConditionalSchema,
  miroirTest_resolveQueryTemplates,
  miroirTest_resolveSchemaReferenceInContext,
  miroirTest_runner_create_entity,
  miroirTest_runner_drop_entity,
  miroirTest_runner_freeze_application_version,
  miroirTest_selectUnionBranchFromDiscriminator,
  miroirTest_tools,
  miroirTest_unfoldSchemaOnce,
  modelEndpointV1,
  queryVersionBundleProducerV1,
  persistenceEndpointVersionV1,
  queryEndpointVersionV1,
  reportApplicationEvolutionTraceDetails,
  reportApplicationEvolutionTraceHistory,
  reportApplicationEvolutionTraceList,
  reportApplicationList,
  reportApplicationModelBranchList,
  reportApplicationVersionList,
  reportApplicationVersionDetails,
  reportVersioning,
  reportEndpointVersionList,
  reportEntityDefinitionList,
  reportEntityList,
  reportEntityVersionList,
  reportJzodSchemaList,
  reportMenuList,
  reportQueryList,
  reportReportList,
  reportRunnerDetails,
  reportRunnerList,
  runnerDropApplication,
  runnerDropEntity,
  runnerFreezeApplicationVersion,
  selfApplicationMiroir,
  selfApplicationVersionInitialMiroirVersion,
  storeManagementEndpoint,
  testEndpointVersionV1,
  undoRedoEndpointVersionV1,
  entityCommit
} from "..";

export const defaultMiroirMetaModelEntityNameToAttributeName: Record<string, string> = {
  Entity: "entities",
  EntityVersion: "entityVersions",
  Endpoint: "endpoints",
  JzodSchema: "jzodSchemas",
  Menu: "menus",
  ApplicationVersion: "applicationVersions",
  Report: "reports",
  Runner: "runners",
  MiroirTest: "tests",
  Theme: "themes",
  ApplicationVersionCrossEntityDefinition: "applicationVersionCrossEntityVersion",
  ApplicationVersionCrossEntityVersion: "applicationVersionCrossEntityVersion",
  ApplicationVersionCrossQueryVersion: "applicationVersionCrossQueryVersion",
  QueryVersion: "queryVersions",
  ApplicationVersionCrossReportVersion: "applicationVersionCrossReportVersion",
  ReportVersion: "reportVersions",
  ApplicationVersionCrossMenuVersion: "applicationVersionCrossMenuVersion",
  MenuVersion: "menuVersions",
  ApplicationVersionCrossEndpointVersion: "applicationVersionCrossEndpointVersion",
  EndpointVersion: "endpointVersions",
  ApplicationVersionCrossRunnerVersion: "applicationVersionCrossRunnerVersion",
  RunnerVersion: "runnerVersions",
};
export const defaultMiroirMetaModel: MetaModel = {
  applicationUuid: selfApplicationMiroir.uuid,
  applicationName: selfApplicationMiroir.name,
  // configuration: [instanceConfigurationReference],
  storedQueries: [],
  applications: [selfApplicationMiroir as SelfApplication],
  entities: [
    // this is used in tests, the bootstrap entities have to come first
    entityEntity as Entity,
    entityEntityVersion as Entity,
    //
    entityCommit as Entity,
    entityEndpointVersion as Entity,
    entityJzodSchema as Entity, // null
    entityMenu as Entity,
    entityQueryVersion as Entity,
    entityReport as Entity,
    entityRunner as Entity,
    entitySelfApplication as Entity,
    entitySelfApplicationModelBranch as Entity,
    entitySelfApplicationVersion as Entity,
    entityMiroirTest as Entity,
    entityTheme as Entity,
    entityApplicationEvolutionTrace as Entity,
    entityApplicationEvolutionTraceEvent as Entity,
    entityApplicationVersionCrossEntityVersion as Entity,
    entityApplicationVersionCrossQueryVersion as Entity,
    entityHistoricalQueryVersion as Entity,
    entityApplicationVersionCrossReportVersion as Entity,
    entityHistoricalReportVersion as Entity,
    entityApplicationVersionCrossMenuVersion as Entity,
    entityHistoricalMenuVersion as Entity,
    entityApplicationVersionCrossEndpointVersion as Entity,
    entityHistoricalEndpointVersion as Entity,
    entityApplicationVersionCrossRunnerVersion as Entity,
    entityHistoricalRunnerVersion as Entity,
  ],
  entityVersions: [
    // bootstrap entities have to come first
    entityVersionEntityVersion as EntityVersion,
    entityDefinitionEntity as EntityVersion,
    //
    entityDefinitionEndpoint as EntityVersion,
    entityDefinitionJzodSchema as EntityVersion, //
    entityDefinitionMenu as EntityVersion,
    entityDefinitionQuery as EntityVersion,
    entityDefinitionReport as EntityVersion,
    entityDefinitionRunner as EntityVersion,
    entityDefinitionSelfApplication as EntityVersion,
    entityDefinitionSelfApplicationModelBranch as EntityVersion,
    entityDefinitionSelfApplicationVersion as EntityVersion,
    entityDefinitionMiroirTest as EntityVersion,
    entityDefinitionTheme as EntityVersion,
    entityDefinitionApplicationEvolutionTrace as EntityVersion,
    entityDefinitionApplicationEvolutionTraceEvent as EntityVersion,
    entityDefinitionApplicationVersionCrossEntityDefinition as EntityVersion,
    entityVersionHistoricalQueryVersion as EntityVersion,
    entityVersionApplicationVersionCrossQueryVersion as EntityVersion,
    entityVersionHistoricalReportVersion as EntityVersion,
    entityVersionApplicationVersionCrossReportVersion as EntityVersion,
    entityVersionHistoricalMenuVersion as EntityVersion,
    entityVersionApplicationVersionCrossMenuVersion as EntityVersion,
    entityVersionHistoricalEndpointVersion as EntityVersion,
    entityVersionApplicationVersionCrossEndpointVersion as EntityVersion,
    entityVersionHistoricalRunnerVersion as EntityVersion,
    entityVersionApplicationVersionCrossRunnerVersion as EntityVersion,
  ],
  endpoints: [
    applicationEndpointV1 as any as EndpointDefinition,
    deploymentEndpointV1 as any as EndpointDefinition,
    instanceEndpointV1 as any as EndpointDefinition,
    modelEndpointV1 as any as EndpointDefinition,
    domainEndpointVersionV1 as any as EndpointDefinition,
    testEndpointVersionV1 as any as EndpointDefinition,
    storeManagementEndpoint as any as EndpointDefinition,
    instanceEndpointVersionV1 as any as EndpointDefinition,
    undoRedoEndpointVersionV1 as any as EndpointDefinition,
    localCacheEndpointVersionV1 as any as EndpointDefinition,
    queryEndpointVersionV1 as any as EndpointDefinition,
    persistenceEndpointVersionV1 as any as EndpointDefinition,
  ],
  jzodSchemas: [jzodSchemajzodMiroirBootstrapSchema as MlSchema],
  menus: [menuDefaultMiroir as Menu],
  applicationVersions: [selfApplicationVersionInitialMiroirVersion],
  reports: [
    // TODO: MISSING "DETAILS" REPORTS
    // reportApplicationDeploymentConfigurationList as Report,
    reportApplicationList as Report,
    reportApplicationModelBranchList as Report,
    reportApplicationVersionList as Report,
    reportApplicationVersionDetails as Report,
    reportVersioning as Report,
    reportApplicationEvolutionTraceList as Report,
    reportApplicationEvolutionTraceHistory as Report,
    reportApplicationEvolutionTraceDetails as Report,
    reportEndpointVersionList as Report,
    reportEntityVersionList as Report,
    reportEntityList as Report,
    reportJzodSchemaList as Report,
    reportMenuList as Report,
    reportReportList as Report,
    reportRunnerList as Report,
    reportRunnerDetails as Report,
  ],
  runners: [
    runnerDropApplication as Runner,
    runnerDropEntity as any as Runner,
    runnerFreezeApplicationVersion as any as Runner,
  ],
  applicationVersionCrossEntityVersion: [
    applicationVersionInitialMiroirVersionCrossEntityDefinitionApplication,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionApplicationModelBranch,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionApplicationVersion,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionEntity,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionEntityDefinition,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionReport,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionStoreBasedConfiguration,
  ],
  applicationVersionCrossQueryVersion: [],
  queryVersions: [],
  applicationVersionCrossReportVersion: [],
  reportVersions: [],
  applicationVersionCrossMenuVersion: [],
  menuVersions: [],
  applicationVersionCrossEndpointVersion: [],
  endpointVersions: [],
  applicationVersionCrossRunnerVersion: [],
  runnerVersions: [],
  tests: [
    miroirTest_adminTransformers as MiroirTestDefinition,
    miroirTest_alterObject as MiroirTestDefinition,
    miroirTest_ansiColumnsToJzodSchema as MiroirTestDefinition,
    miroirTest_buildAnyKeyMap as MiroirTestDefinition,
    miroirTest_defaultValueForMLSchema as MiroirTestDefinition,
    miroirTest_EntityPrimaryKey as MiroirTestDefinition,
    miroirTest_getAttributeTypesFromJzodSchema as MiroirTestDefinition,
    miroirTest_jzodObjectFlatten as MiroirTestDefinition,
    miroirTest_JzodSchemaReferencesList as MiroirTestDefinition,
    miroirTest_JzodSchemaReferencesSet as MiroirTestDefinition,
    miroirTest_jzodToCopilotKitParameter as MiroirTestDefinition,
    miroirTest_jzodToJsonSchema as MiroirTestDefinition,
    miroirTest_jzodToJzod_Summary as MiroirTestDefinition,
    miroirTest_jzodTransitiveDependencySet as MiroirTestDefinition,
    miroirTest_jzodTypeCheck as MiroirTestDefinition,
    miroirTest_jzodUnion_RecursiveUnfold as MiroirTestDefinition,
    miroirTest_jzodUnionResolvedTypeForArray as MiroirTestDefinition,
    miroirTest_jzodUnionResolvedTypeForObject as MiroirTestDefinition,
    miroirTest_localizeJzodSchemaReferenceContext as MiroirTestDefinition,
    miroirTest_menu as MiroirTestDefinition,
    miroirTest_mergePositionBased as MiroirTestDefinition,
    miroirTest_metaModelTransformers as MiroirTestDefinition,
    miroirTest_miroirCoreTransformers as MiroirTestDefinition,
    miroirTest_modelUpdates as MiroirTestDefinition,
    miroirTest_mustache as MiroirTestDefinition,
    miroirTest_pilot_transformer_plus as MiroirTestDefinition,
    miroirTest_queries_library as MiroirTestDefinition,
    miroirTest_resolveConditionalSchema as MiroirTestDefinition,
    miroirTest_resolveQueryTemplates as MiroirTestDefinition,
    miroirTest_resolveSchemaReferenceInContext as MiroirTestDefinition,
    miroirTest_selectUnionBranchFromDiscriminator as MiroirTestDefinition,
    miroirTest_tools as MiroirTestDefinition,
    miroirTest_unfoldSchemaOnce as MiroirTestDefinition,
    miroirTest_domain_controller_data_crud as MiroirTestDefinition,
    miroirTest_domain_controller_model_crud as MiroirTestDefinition,
    miroirTest_domain_controller_composite_pk_crud as MiroirTestDefinition,
    miroirTest_domain_controller_non_uuid_pk_model_crud as MiroirTestDefinition,
    miroirTest_domain_controller_non_uuid_pk_data_crud as MiroirTestDefinition,
    miroirTest_domain_controller_no_parent_uuid_crud as MiroirTestDefinition,
    miroirTest_domain_controller_model_undo_redo as MiroirTestDefinition,
    miroirTest_domain_controller_application_version_freeze as MiroirTestDefinition,
    miroirTest_evolutionTraceWP1 as MiroirTestDefinition,
    miroirTest_runner_create_entity as MiroirTestDefinition,
    miroirTest_runner_drop_entity as MiroirTestDefinition,
    miroirTest_runner_freeze_application_version as MiroirTestDefinition,
    // miroirTest_mustache as MiroirTestDefinition
  ],
  themes: [
    defaultStoredMiroirTheme,
    darkStoredMiroirTheme,
    compactStoredMiroirTheme,
    materialStoredMiroirTheme,
  ],
};

function entitiesInBootstrapOrder(uuids: readonly string[]): Entity[] {
  const entityByUuid = new Map(
    defaultMiroirMetaModel.entities.map((entity) => [entity.uuid, entity as Entity]),
  );
  return uuids.map((uuid) => {
    const entity = entityByUuid.get(uuid);
    if (!entity) {
      throw new Error(`defaultMiroirMetaModel bootstrap: unknown entity uuid ${uuid}`);
    }
    return entity;
  });
}

/** EntityVersion rows upserted to Miroir data during modelInitialize. */
export const miroirModelInitializeEntityVersionInstances: EntityVersion[] = [
  entityDefinitionEntity as EntityVersion,
  entityDefinitionEntityDefinition as EntityVersion,
  entityDefinitionApplicationVersionCrossEntityDefinition as EntityVersion,
  entityVersionApplicationVersionCrossQueryVersion as EntityVersion,
  entityVersionHistoricalQueryVersion as EntityVersion,
  entityVersionApplicationVersionCrossReportVersion as EntityVersion,
  entityVersionHistoricalReportVersion as EntityVersion,
  entityVersionApplicationVersionCrossMenuVersion as EntityVersion,
  entityVersionHistoricalMenuVersion as EntityVersion,
  entityVersionApplicationVersionCrossEndpointVersion as EntityVersion,
  entityVersionHistoricalEndpointVersion as EntityVersion,
  entityVersionApplicationVersionCrossRunnerVersion as EntityVersion,
  entityVersionHistoricalRunnerVersion as EntityVersion,
];

/** EntityVersion rows upserted immediately after createEntity(entityEntityVersion). */
export const miroirModelInitializeEntityVersionsAfterEntityEntityVersion: EntityVersion[] =
  miroirModelInitializeEntityVersionInstances.filter(
    (ev) => ev.entityUuid === entityEntity.uuid || ev.entityUuid === entityEntityVersion.uuid,
  );

/** EntityVersion rows keyed by Entity.uuid — upsert after matching createEntity. */
export const miroirModelInitializeEntityVersionsByEntityUuid: ReadonlyMap<
  string,
  readonly EntityVersion[]
> = new Map(
  defaultMiroirMetaModel.entities.map((entity) => [
    entity.uuid,
    miroirModelInitializeEntityVersionInstances.filter((ev) => ev.entityUuid === entity.uuid),
  ]),
);

/** createEntity order for Miroir bootstrap (excludes meta Entity row). */
export const miroirModelInitializeCreateEntityOrder: Entity[] = entitiesInBootstrapOrder([
  entityEntityVersion.uuid!,
  entitySelfApplication.uuid!,
  entitySelfApplicationModelBranch.uuid!,
  entitySelfApplicationVersion.uuid!,
  entityEndpointVersion.uuid!,
  entityCommit.uuid!,
  entityMenu.uuid!,
  entityJzodSchema.uuid!,
  entityReport.uuid!,
  entityRunner.uuid!,
  entityMiroirTest.uuid!,
  entityTheme.uuid!,
  entityQueryVersion.uuid!,
  entityHistoricalQueryVersion.uuid!,
  entityApplicationEvolutionTrace.uuid!,
  entityApplicationEvolutionTraceEvent.uuid!,
  entityApplicationVersionCrossEntityVersion.uuid!,
  entityApplicationVersionCrossQueryVersion.uuid!,
  entityApplicationVersionCrossReportVersion.uuid!,
  entityHistoricalReportVersion.uuid!,
  entityApplicationVersionCrossMenuVersion.uuid!,
  entityHistoricalMenuVersion.uuid!,
  entityApplicationVersionCrossEndpointVersion.uuid!,
  entityHistoricalEndpointVersion.uuid!,
  entityApplicationVersionCrossRunnerVersion.uuid!,
  entityHistoricalRunnerVersion.uuid!,
]);

/** Non-entity instances upserted to Miroir data during bootstrap. */
export const miroirModelInitializeDataInstances: EntityInstance[] = [
  reportEndpointVersionList as EntityInstance,
  reportEntityDefinitionList as EntityInstance,
  reportEntityList as EntityInstance,
  reportApplicationList as EntityInstance,
  reportApplicationModelBranchList as EntityInstance,
  reportApplicationVersionList as EntityInstance,
  reportMenuList as EntityInstance,
  reportReportList as EntityInstance,
  reportJzodSchemaList as EntityInstance,
  reportApplicationEvolutionTraceList as EntityInstance,
  reportApplicationEvolutionTraceHistory as EntityInstance,
  reportQueryList as EntityInstance,
  menuDefaultMiroir as EntityInstance,
  miroirJzodSchemaBootstrap as EntityInstance,
  applicationEndpointV1 as EntityInstance,
  deploymentEndpointV1 as EntityInstance,
  instanceEndpointV1 as EntityInstance,
  modelEndpointV1 as EntityInstance,
  queryVersionBundleProducerV1 as EntityInstance,
  defaultStoredMiroirTheme as EntityInstance,
  darkStoredMiroirTheme as EntityInstance,
  compactStoredMiroirTheme as EntityInstance,
  materialStoredMiroirTheme as EntityInstance,
];

/** createModelStorageSpace order for application (app) bootstrap. */
export const appModelInitializeCreateEntityOrder: Entity[] = entitiesInBootstrapOrder([
  entityEntity.uuid!,
  entityEntityVersion.uuid!,
  entitySelfApplication.uuid!,
  entitySelfApplicationModelBranch.uuid!,
  entitySelfApplicationVersion.uuid!,
  entityMenu.uuid!,
  entityEndpointVersion.uuid!,
  entityJzodSchema.uuid!,
  entityQueryVersion.uuid!,
  entityReport.uuid!,
  entityRunner.uuid!,
  entityMiroirTest.uuid!,
  entityTheme.uuid!,
  entityApplicationEvolutionTrace.uuid!,
  entityApplicationEvolutionTraceEvent.uuid!,
  entityApplicationVersionCrossEntityVersion.uuid!,
]);
