import type {
  EndpointDefinition,
  Entity,
  EntityDefinition,
  Menu,
  MetaModel,
  MiroirTestDefinition,
  MlSchema,
  Report,
  Runner,
  SelfApplication,
} from "miroir-core";
import {
  entityTheme,
  entityDefinitionTheme,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionApplication,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionApplicationModelBranch,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionApplicationVersion,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionEntity,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionEntityDefinition,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionReport,
  applicationVersionInitialMiroirVersionCrossEntityDefinitionStoreBasedConfiguration,
  defaultStoredMiroirTheme,
  darkStoredMiroirTheme,
  compactStoredMiroirTheme,
  materialStoredMiroirTheme,
  selfApplicationMiroir,
  entityEntity,
  applicationEndpointV1,
  deploymentEndpointV1,
  domainEndpointVersionV1,
  entityDefinitionEndpoint,
  entityDefinitionEntity,
  entityDefinitionEntityDefinition,
  entityDefinitionJzodSchema,
  entityDefinitionMenu,
  entityDefinitionQuery,
  entityDefinitionReport,
  entityDefinitionRunner,
  entityDefinitionSelfApplication,
  entityDefinitionSelfApplicationModelBranch,
  entityDefinitionSelfApplicationVersion,
  entityEndpointVersion,
  entityEntityDefinition,
  entityJzodSchema,
  entityMenu,
  entityQueryVersion,
  entityReport,
  entityRunner,
  entitySelfApplication,
  entitySelfApplicationModelBranch,
  entitySelfApplicationVersion,
  instanceEndpointV1,
  instanceEndpointVersionV1,
  jzodSchemajzodMiroirBootstrapSchema,
  localCacheEndpointVersionV1,
  menuDefaultMiroir,
  miroirTest_mustache,
  modelEndpointV1,
  persistenceEndpointVersionV1,
  queryEndpointVersionV1,
  reportApplicationDeploymentConfigurationList,
  reportApplicationList,
  reportApplicationModelBranchList,
  reportApplicationVersionList,
  reportConfigurationList,
  reportEndpointVersionList,
  reportEntityDefinitionList,
  reportEntityList,
  reportJzodSchemaList,
  reportMenuList,
  reportReportList,
  reportRunnerDetails,
  reportRunnerList,
  runnerDropApplication,
  runnerDropEntity,
  selfApplicationVersionInitialMiroirVersion,
  storeManagementEndpoint,
  testEndpointVersionV1,
  undoRedoEndpointVersionV1,
  entityMiroirTest,
  entityDefinitionMiroirTest,
  miroirTest_adminTransformers,
  miroirTest_alterObject,
  miroirTest_ansiColumnsToJzodSchema,
  miroirTest_buildAnyKeyMap,
  miroirTest_defaultValueForMLSchema,
  miroirTest_EntityPrimaryKey,
  miroirTest_getAttributeTypesFromJzodSchema,
  miroirTest_jzodObjectFlatten,
  miroirTest_JzodSchemaReferencesList,
  miroirTest_JzodSchemaReferencesSet,
  miroirTest_jzodToCopilotKitParameter,
  miroirTest_jzodToJsonSchema,
  miroirTest_jzodToJzod_Summary,
  miroirTest_jzodTransitiveDependencySet,
  miroirTest_jzodTypeCheck,
  miroirTest_jzodUnion_RecursiveUnfold,
  miroirTest_jzodUnionResolvedTypeForArray,
  miroirTest_jzodUnionResolvedTypeForObject,
  miroirTest_localizeJzodSchemaReferenceContext,
  miroirTest_menu,
  miroirTest_mergePositionBased,
  miroirTest_metaModelTransformers,
  miroirTest_miroirCoreTransformers,
  miroirTest_modelUpdates,
  miroirTest_pilot_transformer_plus,
  miroirTest_queries_library,
  miroirTest_resolveConditionalSchema,
  miroirTest_resolveQueryTemplates,
  miroirTest_resolveSchemaReferenceInContext,
  miroirTest_selectUnionBranchFromDiscriminator,
  miroirTest_tools,
  miroirTest_unfoldSchemaOnce,
  miroirTest_domain_controller_data_crud,
  miroirTest_domain_controller_model_crud,
  miroirTest_domain_controller_composite_pk_crud,
  miroirTest_domain_controller_non_uuid_pk_model_crud,
  miroirTest_domain_controller_non_uuid_pk_data_crud,
  miroirTest_domain_controller_no_parent_uuid_crud,
  miroirTest_domain_controller_model_undo_redo,
  miroirTest_runner_create_entity,
  miroirTest_runner_drop_entity,
} from "..";

export const defaultMiroirMetaModelEntityNameToAttributeName: Record<string, string> = {
  Entity: "entities",
  EntityDefinition: "entityDefinitions",
  Endpoint: "endpoints",
  JzodSchema: "jzodSchemas",
  Menu: "menus",
  ApplicationVersion: "applicationVersions",
  Report: "reports",
  Runner: "runners",
  MiroirTest: "tests",
  Theme: "themes",
  ApplicationVersionCrossEntityDefinition: "applicationVersionCrossEntityDefinitions",
};
export const defaultMiroirMetaModel: MetaModel = {
  applicationUuid: selfApplicationMiroir.uuid,
  applicationName: selfApplicationMiroir.name,
  // configuration: [instanceConfigurationReference],
  storedQueries: [],
  applications: [selfApplicationMiroir as SelfApplication],
  entities: [
    // this is used in tests, the bootstrap entities have to come first
    entityEntity as Entity,
    entityEntityDefinition as Entity,
    //
    entityEndpointVersion as Entity,
    entityJzodSchema as Entity, // null
    entityMenu as Entity,
    entityQueryVersion as Entity,
    entityReport as Entity,
    entityRunner as Entity,
    entitySelfApplication as Entity,
    entitySelfApplicationModelBranch as Entity,
    entitySelfApplicationVersion as Entity,
    entityMiroirTest as Entity,
    entityTheme as Entity,
  ],
  entityDefinitions: [
    // bootstrap entities have to come first
    entityDefinitionEntityDefinition as EntityDefinition,
    entityDefinitionEntity as EntityDefinition,
    //
    entityDefinitionEndpoint as EntityDefinition,
    entityDefinitionJzodSchema as EntityDefinition, //
    entityDefinitionMenu as EntityDefinition,
    entityDefinitionQuery as EntityDefinition,
    entityDefinitionReport as EntityDefinition,
    entityDefinitionRunner as EntityDefinition,
    entityDefinitionSelfApplication as EntityDefinition,
    entityDefinitionSelfApplicationModelBranch as EntityDefinition,
    entityDefinitionSelfApplicationVersion as EntityDefinition,
    entityDefinitionMiroirTest as EntityDefinition,
    entityDefinitionTheme as EntityDefinition,
  ],
  endpoints: [
    applicationEndpointV1 as any as EndpointDefinition,
    deploymentEndpointV1 as any as EndpointDefinition,
    instanceEndpointV1 as any as EndpointDefinition,
    modelEndpointV1 as any as EndpointDefinition,
    domainEndpointVersionV1 as any as EndpointDefinition,
    testEndpointVersionV1 as any as EndpointDefinition,
    storeManagementEndpoint as any as EndpointDefinition,
    instanceEndpointVersionV1 as any as EndpointDefinition,
    undoRedoEndpointVersionV1 as any as EndpointDefinition,
    localCacheEndpointVersionV1 as any as EndpointDefinition,
    queryEndpointVersionV1 as any as EndpointDefinition,
    persistenceEndpointVersionV1 as any as EndpointDefinition,
  ],
  jzodSchemas: [jzodSchemajzodMiroirBootstrapSchema as MlSchema],
  menus: [menuDefaultMiroir as Menu],
  applicationVersions: [selfApplicationVersionInitialMiroirVersion],
  reports: [
    // TODO: MISSING "DETAILS" REPORTS
    reportApplicationDeploymentConfigurationList as Report,
    reportApplicationList as Report,
    reportApplicationModelBranchList as Report,
    reportApplicationVersionList as Report,
    reportConfigurationList as Report,
    reportEndpointVersionList as Report,
    reportEntityDefinitionList as Report,
    reportEntityList as Report,
    reportJzodSchemaList as Report,
    reportMenuList as Report,
    reportReportList as Report,
    reportRunnerList as Report,
    reportRunnerDetails as Report,
  ],
  runners: [runnerDropApplication as Runner, runnerDropEntity as any as Runner],
  applicationVersionCrossEntityDefinition: [
    applicationVersionInitialMiroirVersionCrossEntityDefinitionApplication,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionApplicationModelBranch,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionApplicationVersion,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionEntity,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionEntityDefinition,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionReport,
    applicationVersionInitialMiroirVersionCrossEntityDefinitionStoreBasedConfiguration,
  ],
  tests: [
    miroirTest_adminTransformers as MiroirTestDefinition,
    miroirTest_alterObject as MiroirTestDefinition,
    miroirTest_ansiColumnsToJzodSchema as MiroirTestDefinition,
    miroirTest_buildAnyKeyMap as MiroirTestDefinition,
    miroirTest_defaultValueForMLSchema as MiroirTestDefinition,
    miroirTest_EntityPrimaryKey as MiroirTestDefinition,
    miroirTest_getAttributeTypesFromJzodSchema as MiroirTestDefinition,
    miroirTest_jzodObjectFlatten as MiroirTestDefinition,
    miroirTest_JzodSchemaReferencesList as MiroirTestDefinition,
    miroirTest_JzodSchemaReferencesSet as MiroirTestDefinition,
    miroirTest_jzodToCopilotKitParameter as MiroirTestDefinition,
    miroirTest_jzodToJsonSchema as MiroirTestDefinition,
    miroirTest_jzodToJzod_Summary as MiroirTestDefinition,
    miroirTest_jzodTransitiveDependencySet as MiroirTestDefinition,
    miroirTest_jzodTypeCheck as MiroirTestDefinition,
    miroirTest_jzodUnion_RecursiveUnfold as MiroirTestDefinition,
    miroirTest_jzodUnionResolvedTypeForArray as MiroirTestDefinition,
    miroirTest_jzodUnionResolvedTypeForObject as MiroirTestDefinition,
    miroirTest_localizeJzodSchemaReferenceContext as MiroirTestDefinition,
    miroirTest_menu as MiroirTestDefinition,
    miroirTest_mergePositionBased as MiroirTestDefinition,
    miroirTest_metaModelTransformers as MiroirTestDefinition,
    miroirTest_miroirCoreTransformers as MiroirTestDefinition,
    miroirTest_modelUpdates as MiroirTestDefinition,
    miroirTest_mustache as MiroirTestDefinition,
    miroirTest_pilot_transformer_plus as MiroirTestDefinition,
    miroirTest_queries_library as MiroirTestDefinition,
    miroirTest_resolveConditionalSchema as MiroirTestDefinition,
    miroirTest_resolveQueryTemplates as MiroirTestDefinition,
    miroirTest_resolveSchemaReferenceInContext as MiroirTestDefinition,
    miroirTest_selectUnionBranchFromDiscriminator as MiroirTestDefinition,
    miroirTest_tools as MiroirTestDefinition,
    miroirTest_unfoldSchemaOnce as MiroirTestDefinition,
    miroirTest_domain_controller_data_crud as MiroirTestDefinition,
    miroirTest_domain_controller_model_crud as MiroirTestDefinition,
    miroirTest_domain_controller_composite_pk_crud as MiroirTestDefinition,
    miroirTest_domain_controller_non_uuid_pk_model_crud as MiroirTestDefinition,
    miroirTest_domain_controller_non_uuid_pk_data_crud as MiroirTestDefinition,
    miroirTest_domain_controller_no_parent_uuid_crud as MiroirTestDefinition,
    miroirTest_domain_controller_model_undo_redo as MiroirTestDefinition,
    miroirTest_runner_create_entity as MiroirTestDefinition,
    miroirTest_runner_drop_entity as MiroirTestDefinition,
    // miroirTest_mustache as MiroirTestDefinition
  ],
  themes: [
    defaultStoredMiroirTheme,
    darkStoredMiroirTheme,
    compactStoredMiroirTheme,
    materialStoredMiroirTheme,
  ],
};
