/// <reference types="vitest" />
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { nodePolyfills } from 'vite-plugin-node-polyfills'
// import { babelImport } from 'vite-plugin-babel-import';
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

// Resolve certificate paths (same defaults as miroir-server)
const __viteFilename = fileURLToPath(import.meta.url);
const __viteDirname = path.dirname(__viteFilename);
const defaultCertsDir = path.resolve(__viteDirname, '../../certs');
const certFile = process.env.MIROIR_TLS_CERT ?? path.join(defaultCertsDir, 'localhost.pem');
const keyFile  = process.env.MIROIR_TLS_KEY  ?? path.join(defaultCertsDir, 'localhost-key.pem');
const certsReady = fs.existsSync(certFile) && fs.existsSync(keyFile);
const apiBase = certsReady ? 'https://localhost:3080' : 'http://localhost:3080';

if (!certsReady) {
  console.warn(
    '[vite] TLS certificate files not found — serving over HTTP.\n' +
    '  Run  scripts/setup-https.sh  (bash) or  scripts/setup-https.ps1  (PowerShell)' +
    ' to enable HTTPS.'
  );
}

export default defineConfig({
  root: 'src',
  build: {
    // Relative to the root
    outDir: '../dist',
    target: 'esnext',
    // rollupOptions: {
    //   external: ["process"]
    // },
  },
  // resolve: {
  // // //   alias: {
  // // //     src: path.resolve(__dirname, 'src'),
  // // //   }
  //   alias: {
  //     '@uiw/react-codemirror': path.resolve(__dirname, '../../node_modules/@uiw/react-codemirror/cjs/useCodeMirror.js'),
  //     // '@uiw/react-codemirror': path.resolve(__dirname, '../../node_modules/@uiw/react-codemirror/cjs/useCodeMirror.js'),
  // //     '@codemirror/state': path.resolve(__dirname, './node_modules/@codemirror/state/dist/index.cjs'),
  // //     // '@codemirror/state': path.resolve(__dirname, '../../node_modules/@codemirror/state/dist/index.cjs'),
  // //     // '@codemirror/state': path.resolve(__dirname, 'node_modules/@codemirror/state/dist/index.cjs'),
  // //     // '@codemirror/state': path.resolve(
  // //     //   __dirname,
  // //     //   './node_modules/@codemirror/state/dist/index.cjs'
  // //     // ),
  // //     // // '@codemirror/lang-yaml': path.resolve(
  // //     // //   __dirname,
  // //     // // ),
  // //     // '@codemirror/lang-json': path.resolve(
  // //     //   __dirname,
  // //     //   './node_modules/@codemirror/lang-json/dist/index.cjs'
  // //     // )
  //   }
  // },
  optimizeDeps: {
    include: [
      '@emotion/react', 
      '@emotion/styled', 
      '@mui/material/Tooltip'
    ],
  },
  plugins: [
    nodePolyfills({
      // To add only specific polyfills, add them here. If no option is passed, adds all polyfills
      // include: [ "crypto", "stream", "perf_hooks", "process" ],
      include: [ "crypto" ],
      // To exclude specific polyfills, add them to this list. Note: if include is provided, this has no effect
      exclude: [
        // "stream", "perf_hooks"
        "process"
        // 'http', // Excludes the polyfill for `http` and `node:http`.
      ],
      // // Whether to polyfill specific globals.
      // globals: {
      //   Buffer: true, // can also be 'build', 'dev', or false
      //   global: true,
      //   process: true,
      // },
      // // Whether to polyfill `node:` protocol imports.
      // protocolImports: true,
    }),
    react({
      jsxImportSource: '@emotion/react',
      // Use React plugin in all *.jsx and *.tsx files
      include: '../src/**/*.{jsx,tsx}',
      babel: {
        plugins: ['@emotion/babel-plugin'],
      },
    }),
    // babelImport([
    //   {
    //     libraryName: '@mui/icons-material',
    //     libraryDirectory: '',
    //     camel2DashComponentName: false,
    //   },
    // ]),
  ],
  server: {
    // Enable HTTPS when certs are available (generated by scripts/setup-https.sh/.ps1).
    // Falls back to HTTP automatically when cert files are absent.
    https: certsReady
      ? { key: fs.readFileSync(keyFile), cert: fs.readFileSync(certFile) }
      : undefined,
    // cors: {
    //   origin: ['http://localhost:3080'],
    //   credentials: true
    // }
    proxy: {
      // Proxy API requests to the server; secure:false accepts self-signed/local-CA certs
      '/queryTemplate': { target: apiBase, secure: false },
      '/query':         { target: apiBase, secure: false },
      '/action':        { target: apiBase, secure: false },
      '/CRUD':          { target: apiBase, secure: false }
    }
  },
  test: {
    root: "tests",
    globals: true,
    watch: false,
    environment: 'happy-dom',
    hookTimeout: 30000,
    testTimeout: 180000, // 3 minutes for complex tests
    setupFiles: ['./setup.ts'],
    env: {
      VITE_TEST_MODE: 'true'
    },
    // Configure React Testing Library act warnings
    pool: 'threads',
    poolOptions: {
      threads: {
        singleThread: true
      }
    },
    // Configure environment for React Testing Library
    environmentOptions: {
      happyDOM: {
        settings: {
          // Enable React 18 features
          disableJavaScriptFileLoading: false,
          disableJavaScriptEvaluation: false,
          enableFileSystemHttpRequests: false
        }
      }
    }
  },
});