import { z } from "zod";

import {
  // selfApplicationDeploymentConfigurationsTO_REMOVEchema,
  domainElementObject,
  entity,
  entityInstance,
  entityInstancesUuidIndex,
  jzodElement,
  metaModel,
  deployment
} from "miroir-core";
import { autoGeneratedColumnDef } from "./ValueObjectGridInterface";
import {
  gridDefaultSizingPropsSchema,
  gridPagedSizingPropsSchema,
  gridScrollSizingPropsSchema,
} from "./gridPagination.js";

export const TableComponentTypeSchema = z.enum(["EntityInstance", "JSON_ARRAY"]);

export type TableComponentType = z.infer<typeof TableComponentTypeSchema>;

const tableComponentCoreBasePropsSchema = z.object({
  // columnDefs: z.object({ columnDefs: z.array(z.any()) }),
  application: z.string().uuid(),
  deploymentUuid: z.string().uuid(),
  columnDefs: z.object({ columnDefs: z.array(autoGeneratedColumnDef) }),
  instancesToDisplay: entityInstancesUuidIndex.optional(), // TODO: lower it down to TableCompnentEntityInstancePropsSchema, this should not appear in TableComponentJsonArrayPropsSchema
  styles: z.any().optional(),
  children: z.any(),
  displayTools: z.boolean(),
  applicationDeploymentMap: z.record(z.string(), z.string().uuid()),
  currentModel: metaModel,
  defaultFormValuesObject: z.any(),
  sortByAttribute: z.string().optional(),
  paramsAsdomainElements: domainElementObject,
  foreignKeyObjects: z.record(z.string(),entityInstancesUuidIndex),
  addObjectdialogFormIsOpen: z.boolean(), //.optional(),
  setAddObjectdialogFormIsOpen: z.function().args(z.boolean()).returns(z.void()), //.optional(),
  /** Fires when the visible page slice changes (paged mode only). */
  onDisplayedPageRowsChange: z
    .function()
    .args(entityInstancesUuidIndex)
    .returns(z.void())
    .optional(),
});

// Sizing modes (D2-d): the core props schema is a union of paged / scroll / default variants,
// so pageSize/maxRows mutual exclusivity is enforced by the schema itself.
const tableComponentCorePagedPropsSchema = tableComponentCoreBasePropsSchema.merge(gridPagedSizingPropsSchema);
const tableComponentCoreScrollPropsSchema = tableComponentCoreBasePropsSchema.merge(gridScrollSizingPropsSchema);
const tableComponentCoreDefaultPropsSchema = tableComponentCoreBasePropsSchema.merge(gridDefaultSizingPropsSchema);

export const tableComponentCorePropsSchema = z.union([
  tableComponentCorePagedPropsSchema,
  tableComponentCoreScrollPropsSchema,
  tableComponentCoreDefaultPropsSchema,
]);

const extendCoreProps = <T extends z.ZodRawShape>(extension: T) =>
  z.union([
    tableComponentCorePagedPropsSchema.extend(extension),
    tableComponentCoreScrollPropsSchema.extend(extension),
    tableComponentCoreDefaultPropsSchema.extend(extension),
  ]);

export const tableComponentEntityInstancePropsSchema = extendCoreProps({
  type: z.literal(TableComponentTypeSchema.enum.EntityInstance),
  // #221 Slice 4 — Entity present model required (no EntityVersion dual-read)
  currentEntity: entity.nullable(),
  onRowEdit: z.function().args(z.any()).returns(z.void()).optional(),
  onRowDelete: z.function().args(z.any()).returns(z.void()).optional(),
});
export type TableComponentEntityInstanceProps = z.infer<typeof tableComponentEntityInstancePropsSchema>;

export const TableComponentJsonArrayPropsSchema = extendCoreProps({
  type: z.literal(TableComponentTypeSchema.enum.JSON_ARRAY),
  rowData: z.array(z.any()),
});
export type TableComponentJsonArrayProps = z.infer<typeof TableComponentJsonArrayPropsSchema>;

// ##########################################################################################
export const TableComponentPropsSchema = z.union([
  tableComponentEntityInstancePropsSchema,
  TableComponentJsonArrayPropsSchema,
]);

export type TableComponentProps = z.infer<typeof TableComponentPropsSchema>;

export const tableComponentRowSchema = z.object({
  displayedValue: z.any(),
  deploymentUuid: z.string().uuid(),
  rawValue: entityInstance,
  mlSchema: z.record(jzodElement),
  foreignKeyObjects: z.record(entityInstancesUuidIndex)
})

export const tableComponentRowArraySchema = z.array(
  tableComponentRowSchema
)

// export const tableComponentRows = 
export type TableComponentRow = z.infer<typeof tableComponentRowSchema>;
export type TableComponentRowArraySchema = z.infer<typeof tableComponentRowArraySchema>;