import {
  CellClickedEvent,
  CellValueChangedEvent,
  GridApi
} from 'ag-grid-community';
import { AgGridReact } from 'ag-grid-react';
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from 'react-router-dom';

// import 'ag-grid-community/styles/ag-grid.css';
// import 'ag-grid-community/styles/ag-theme-alpine.css';

import {
  Domain2QueryReturnType,
  DomainElementSuccess,
  EntityInstance,
  EntityInstancesUuidIndex,
  JzodObject,
  LoggerInterface,
  MetaModel,
  MiroirLoggerFactory,
  ReduxDeploymentsState,
  SyncBoxedExtractorOrQueryRunnerMap,
  SyncQueryRunner,
  ViewParams,
  defaultViewParamsFromAdminStorageFetchQueryParams,
  getEntityPrimaryKeyAttributes,
  getInstancePrimaryKeyValue,
  findEntityFromUuid,
  type Entity,
} from "miroir-core";

import {
  JsonDisplayHelper,
  getMemoizedReduxDeploymentsStateSelectorMap,
  useMiroirContextInnerFormOutput,
  useMiroirContextService,
} from "miroir-react";
import { packageName } from '../../../../constants.js';
import { reportUrl } from '../../navigation.js';
import EntityEditor from '../../EntityEditor.js';
import { useCurrentModel, useReduxDeploymentsStateQuerySelectorForCleanedResult } from '../../ReduxHooks.js';
import { ToolsColumnDefinition } from '../../adaptiveColumnWidths.js';
import { cleanLevel } from '../../constants.js';
import { useMiroirTableTheme } from '../../contexts/MiroirThemeContext.js';
import { JsonObjectDeleteFormDialog } from '../JsonObjectDeleteFormDialog.js';
import {
  JsonObjectEditFormDialog,
  JsonObjectEditFormDialogInputs,
} from "../JsonObjectEditFormDialog.js";
import type { ValueObjectEditMode } from '../Reports/ReportSectionEntityInstance.js';
import { generateAgGridStyles, generateGlideTheme, getFilterToolbarStyles } from '../Themes/TableStyleGenerators.js';
import {
  TableComponentProps,
  TableComponentRow,
  TableComponentTypeSchema,
} from "./EntityInstanceGridInterface.js";
import { ToolsCellRenderer } from './GenderCellRenderer.js';
import { GlideDataGridComponent } from './GlideDataGridComponent.js';
import { GridSizingDebugProbe } from './GridSizingDebugProbe.js';
import {
  agGridModeProps,
  computeAgGridScrollHeight,
  paginateRows,
  resolveGridSizingMode,
} from './gridPagination.js';
import { defaultColDef } from './GridTools.js';
import { ValueObjectGrid } from "./ValueObjectGrid.js";
import type { AutoGeneratedColumnDef } from './ValueObjectGridInterface.js';

import { selfApplicationMiroir } from "miroir-test-app_deployment-miroir";
const _miroirLoggerName = MiroirLoggerFactory.getLoggerName(packageName, cleanLevel, "EntityInstanceGrid");
let log: LoggerInterface = MiroirLoggerFactory.getPreStartLogger(_miroirLoggerName);
MiroirLoggerFactory.registerLoggerToStart(_miroirLoggerName, "UI",
).then((logger: LoggerInterface) => {log = logger});

// ################################################################################################
// export const EntityInstanceGrid = (props: TableComponentProps & { theme?: DeepPartial<TableTheme> }) => {
export const EntityInstanceGrid = (props: TableComponentProps) => {
  log.info(":::::::::::::::::::::::::: EntityInstanceGrid refreshing with props",props);

  // #221 Slice 4 — Entity present model only (no EntityVersion dual-read)
  const presentModelSource: Entity | null | undefined =
    props.type === TableComponentTypeSchema.enum.EntityInstance ? props.currentEntity : undefined;
  
  // Get theme from context first, then allow prop overrides
  const contextTheme = useMiroirTableTheme();
  
  // Use the unified table theme with optional overrides
      // const tableTheme = useMemo(() => {
      //   // Start with context theme, then apply any prop overrides
      //   return contextTheme;
      // }, [contextTheme]);
  
  const filterToolbarStyles = useMemo(() => getFilterToolbarStyles(contextTheme), [contextTheme]);
  const agGridStyles = useMemo(() => generateAgGridStyles(contextTheme), [contextTheme]);
  const glideTheme = useMemo(() => generateGlideTheme(contextTheme), [contextTheme]);
  
  const navigate = useNavigate();
  const context = useMiroirContextService();
  const contextDeploymentUuid = context.deploymentUuid;
  const contextApplicationUuid = context.application;
  const gridApiRef = useRef<GridApi | null>(null);
  const gridReadyGenerationRef = useRef(0);

  const withLiveGridApi = useCallback((fn: (api: GridApi) => void) => {
    const api = gridApiRef.current;
    if (api != null && !api.isDestroyed()) {
      fn(api);
    }
  }, []);

  // Container width tracking for adaptive column sizing
  // const containerRef = useRef<HTMLDivElement>(null);

  const deploymentEntityStateSelectorMap: SyncBoxedExtractorOrQueryRunnerMap<ReduxDeploymentsState> =
  useMemo(() => getMemoizedReduxDeploymentsStateSelectorMap(), []);
    
  const defaultViewParamsFromAdminStorageFetchQueryResults: Record<string, EntityInstancesUuidIndex> =
    useReduxDeploymentsStateQuerySelectorForCleanedResult(
      deploymentEntityStateSelectorMap.runQuery as SyncQueryRunner<
        ReduxDeploymentsState,
        Domain2QueryReturnType<DomainElementSuccess>
      >,
      defaultViewParamsFromAdminStorageFetchQueryParams(deploymentEntityStateSelectorMap),
      props.applicationDeploymentMap,
    );
  
  const viewParams: ViewParams | undefined = defaultViewParamsFromAdminStorageFetchQueryResults?.[
    "viewParams"
  ] as any;

  // log.info("EntityInstanceGrid viewParams", viewParams, "defaultViewParamsFromAdminStorageFetchQueryResults", defaultViewParamsFromAdminStorageFetchQueryResults);
  const gridType = viewParams?.gridType || 'ag-grid';

  // ##############################################################################################
  const onGridReady = useCallback((params: any) => {
    gridApiRef.current = params.api;
    const generation = ++gridReadyGenerationRef.current;

    // Add custom filter icon click handler after grid is ready
    setTimeout(() => {
      if (generation !== gridReadyGenerationRef.current) {
        return;
      }

      // Function to update visibility of global clear icon and attach event listeners
      const updateFilterUI = () => {
        withLiveGridApi((api) => {
          const filterModel = api.getFilterModel();
          const hasAnyFilterActive = filterModel && Object.keys(filterModel).length > 0;

          // Update state to trigger re-render of global clear icon
          setHasAnyFilter(!!hasAnyFilterActive);
        });

        // Attach listeners to individual filter icons
        const filterIcons = document.querySelectorAll('#tata .ag-header-cell-filtered .ag-filter-icon, #tata .ag-header-cell-filtered .ag-icon-filter');
        filterIcons.forEach((icon) => {
          // Remove existing listeners to avoid duplicates
          const newIcon = icon.cloneNode(true);
          icon.parentNode?.replaceChild(newIcon, icon);

          // Add new click handler for individual column filter clear
          const clickHandler = (e: Event) => {
            e.preventDefault();
            e.stopPropagation();
            e.stopImmediatePropagation();

            const headerCell = (e.target as HTMLElement).closest('.ag-header-cell');
            if (headerCell) {
              const colId = headerCell.getAttribute('col-id');
              if (colId) {
                withLiveGridApi((api) => {
                  const currentFilterModel = api.getFilterModel();
                  if (currentFilterModel && currentFilterModel[colId]) {
                    delete currentFilterModel[colId];
                    api.setFilterModel(currentFilterModel);
                  }
                });
              }
            }
            return false;
          };
          newIcon.addEventListener('click', clickHandler, true);
        });

        // Attach listener to global clear icon
        const globalIconForListener = document.querySelector('#tata .global-clear-filters');
        if (globalIconForListener) {
          // Remove existing listeners
          const newGlobalIcon = globalIconForListener.cloneNode(true);
          globalIconForListener.parentNode?.replaceChild(newGlobalIcon, globalIconForListener);

          newGlobalIcon.addEventListener('click', (e: Event) => {
            e.preventDefault();
            e.stopPropagation();
            e.stopImmediatePropagation();
            withLiveGridApi((api) => {
              api.setFilterModel(null);
            });
            return false;
          }, true);
        }
      };

      // Initial update
      updateFilterUI();

      // Listen for filter changes to update UI
      withLiveGridApi((api) => {
        api.addEventListener('filterChanged', () => {
          setTimeout(updateFilterUI, 50);
        });
      });
    }, 100);
  }, [withLiveGridApi]);

  // ##############################################################################################
  const handleFilterIconClick = useCallback((event: MouseEvent) => {
    // Check if the clicked element is a filter icon or its parent/child elements
    const target = event.target as HTMLElement;
    
    // Only handle clicks on filter icons in filtered columns
    const isFilterIcon = target.classList.contains('ag-filter-icon') || 
                         target.closest('.ag-filter-icon') || 
                         target.querySelector('.ag-filter-icon') ||
                         target.classList.contains('ag-icon-filter') ||
                         target.closest('.ag-icon-filter');
    
    // Check if the column is currently filtered
    const headerCell = target.closest('.ag-header-cell');
    const isFiltered = headerCell?.classList.contains('ag-header-cell-filtered');
    
    // Check if this is the global clear all filters icon
    const isGlobalClearIcon = target.classList.contains('mtable-global-clear-filters') || 
                          target.closest('.mtable-global-clear-filters');
                          
    if (isGlobalClearIcon) {
      event.preventDefault();
      event.stopPropagation();
      event.stopImmediatePropagation();
      
      withLiveGridApi((api) => {
        api.setFilterModel(null);
        log.info('All filters cleared');
      });
      return false;
    } else if (isFilterIcon && isFiltered && headerCell) {
      event.preventDefault();
      event.stopPropagation();
      event.stopImmediatePropagation();

      // Clear filter for this specific column only
      const colId = headerCell.getAttribute('col-id');
      if (colId) {
        withLiveGridApi((api) => {
          const currentFilterModel = api.getFilterModel();
          if (currentFilterModel && currentFilterModel[colId]) {
            delete currentFilterModel[colId];
            api.setFilterModel(currentFilterModel);
            log.info(`Filter cleared for column: ${colId}`);
          }
        });
      }
      return false;
    }
  }, [withLiveGridApi]);

  // ##############################################################################################
  const handleGlobalClearAllFilters = useCallback(() => {
    withLiveGridApi((api) => {
      api.setFilterModel(null);
      log.info('All filters cleared');
    });
  }, [withLiveGridApi]);

  const handleGridPreDestroyed = useCallback(() => {
    gridReadyGenerationRef.current += 1;
    gridApiRef.current = null;
  }, []);

  // ##############################################################################################
  // Attach event listener for filter icon clicks
  useEffect(() => {
    const gridContainer = document.getElementById('tata');
    if (gridContainer) {
      // Use capture phase to intercept before other handlers
      gridContainer.addEventListener('click', handleFilterIconClick, true);
      gridContainer.addEventListener('mousedown', handleFilterIconClick, true);
      return () => {
        gridContainer.removeEventListener('click', handleFilterIconClick, true);
        gridContainer.removeEventListener('mousedown', handleFilterIconClick, true);
      };
    }
  }, [handleFilterIconClick]);

  // TODO: redundant?
  const [dialogOuterFormObject, setdialogOuterFormObject] = useMiroirContextInnerFormOutput();
  const [dialogFormObject, setdialogFormObject] = useState<undefined | any>(undefined);
  const [hasAnyFilter, setHasAnyFilter] = useState(false);

  // TODO: redundant?
  // const [addObjectdialogFormIsOpen, setAddObjectdialogFormIsOpen] = useState(false);
  // const [editDialogFormIsOpen, setEditDialogFormIsOpen] = useState(false);

  const [valueObjectEditMode, setValueObjectEditMode] = useState<ValueObjectEditMode>("update");
  const [deleteDialogFormIsOpen, setDeleteDialogFormIsOpen] = useState(false);
  
  // log.info("EntityInstanceGrid refreshing with dialogFormObject",dialogFormObject);

  const miroirMetaModel: MetaModel = useCurrentModel(selfApplicationMiroir.uuid, props.applicationDeploymentMap);
  // const currentModel: MetaModel = useCurrentModel(contextApplicationUuid, props.applicationDeploymentMap);
  const currentModel: MetaModel = useCurrentModel(props.application, props.applicationDeploymentMap);
  // log.info("EntityInstanceGrid currentModel", currentModel);

  // ##############################################################################################
  const tableComponentRows: { tableComponentRowUuidIndexSchema: TableComponentRow[] } = useMemo(
    // always use object, not array, to ensure correct refresh!
    () => ({
      tableComponentRowUuidIndexSchema: Object.values(props.instancesToDisplay ?? {})
        .filter(
          (i): i is EntityInstance => i != null && typeof i === "object" && !Array.isArray(i)
        )
        .sort((a: EntityInstance, b: EntityInstance) => // initial sort, to be enhanced! (issue #22)
          props.sortByAttribute
            ? (a as any)[props.sortByAttribute] > (b as any)[props.sortByAttribute]
              ? 1
              : (a as any)[props.sortByAttribute] < (b as any)[props.sortByAttribute]
              ? -1
              : 0
            : 0
        )
        .map((i: EntityInstance) => ({
          deploymentUuid: contextDeploymentUuid,
          rawValue: i,
          foreignKeyObjects: props.foreignKeyObjects,
          mlSchema:
            props.type == TableComponentTypeSchema.enum.EntityInstance
              ? presentModelSource?.mlSchema?.definition ?? {}
              : {},
          displayedValue: Object.fromEntries(
            Object.entries(i).map((e) => {
              const currentAttributeDefinition =
                props.type == TableComponentTypeSchema.enum.EntityInstance
                  ? Object.entries(presentModelSource?.mlSchema?.definition ?? {})?.find((a) => a[0] == e[0])
                  : undefined;
              return [
                e[0],
                Array.isArray(currentAttributeDefinition) &&
                currentAttributeDefinition.length > 1 &&
                (currentAttributeDefinition[1] as any).type == "object"
                  ? JSON.stringify(e[1])
                  : e[1],
              ];
            })
          ),
        })),
    }),
    [props.instancesToDisplay,props.sortByAttribute]
  );
  // log.info("EntityInstanceGrid tableComponentRows", tableComponentRows);

  // ##############################################################################################
  const onCellValueChanged = useCallback(async (event:CellValueChangedEvent) => {
    // event?.stopPropagation();
    log.warn("onCellValueChanged",event, 'contextDeploymentUuid',contextDeploymentUuid)
    // if (props.reportSection.definition.parentUuid == entityEntity.uuid) {
    //   const entity = e.data as MetaEntity;
    //   // sending ModelUpdates
    //   await domainController.handleDomainTransactionalInstanceAction(
    //     contextDeploymentUuid,
    //     {
    //       actionType: "DomainTransactionalInstanceAction",
    //       actionName: "modelActionUpdateEntity",
    //       update: {
    //         actionName:"WrappedTransactionalModelActionEntityUpdate",
    //         modelEntityUpdate:{
    //           actionType:"ModelActionEntityUpdate",
    //           actionName: "renameEntity",
    //           entityName: e.oldValue,
    //           entityUuid: entity.uuid,
    //           targetValue: e.newValue,
    //         },
    //       }
    //     },
    //     currentModel
    //   );
        
    // } else {
    //   log.info("onCellValueChanged on instance of entity",props.reportSection.definition.parentName, props.reportSection.definition.parentUuid,'updating object',e.data)
    //   // sending DataUpdates
    //   await domainController.handleActionFromUI(
    //     contextDeploymentUuid,
    //     {
    //       actionType: "DomainNonTransactionalInstanceAction",
    //       actionName: "update",
    //       objects: [
    //         {
    //           parentUuid: props.reportSection.definition.parentUuid,
    //           applicationSection:'data',
    //           instances:[
    //             // Object.assign({},e.data,{[e.column.getColId()]:e.data.value})
    //             e.data
    //           ]
    //         }
    //       ]
    //     },
    //     currentModel
    //   );
    // }
  },[props,currentModel,])

  // ##############################################################################################
  // TODO: looks like prop drilling... pass onRowEdit directly?
  const onEditDialogFormSubmit: (data:JsonObjectEditFormDialogInputs)=>void = useCallback(async (data) => {
    log.info('onEditDialogFormSubmit called with data',data);
    
    // if (props.type == 'EntityInstance' && props?.onRowEdit) {
    //   await props.onRowEdit(data);
    // } else {
    //   log.error('onEditDialogFormSubmit called for not EntityInstance');
    // }
    // handleEditDialogFormClose('');
  },[props])

  // ##############################################################################################
  const onDeleteDialogFormSubmit: (data:JsonObjectEditFormDialogInputs)=>void = useCallback(async (data) => {
    log.info('onEditDialogFormSubmit called with data',data);
    
    if (props.type == 'EntityInstance' && props?.onRowDelete) {
      await props.onRowDelete(data);
    } else {
      log.error('onEditDialogFormSubmit called for not EntityInstance');
    }
    handleEditDialogFormClose('');
  },[props])

  // ##############################################################################################
  const handleEditDialogFormOpen = useCallback((a?:TableComponentRow,event?:any) => {
    // event?.stopPropagation();
    // log.info('handleEditDialogFormOpen called with props',props);
    // log.info('handleEditDialogFormOpen called dialogFormObject',dialogFormObject, "event value", a);
    
    if (a) {
      setdialogFormObject(a.rawValue);
      setdialogOuterFormObject(a.rawValue)
      // log.info('handleEditDialogFormOpen parameter is defined dialogFormObject',dialogFormObject);
    } else {
      setdialogFormObject(undefined);
      // log.info('handleEditDialogFormOpen parameter is undefined, no value is passed to form. dialogFormObject',dialogFormObject);
    }
    // setEditDialogFormIsOpen(true);
    setValueObjectEditMode("update");
    props.setAddObjectdialogFormIsOpen(true);
  },[props.instancesToDisplay]);

  // ##############################################################################################
  const handleEditDialogFormClose = useCallback((value?: string, event?:any) => {
    // event?.stopPropagation();
    log.info('handleEditDialogFormClose',value);
    
    // setEditDialogFormIsOpen(false);
    props.setAddObjectdialogFormIsOpen(false);
  },[props.setAddObjectdialogFormIsOpen]);

  // ##############################################################################################
  const handleDeleteDialogFormOpen = useCallback((a?:TableComponentRow,event?:any) => {
    // event?.stopPropagation();
    // log.info('handleDeleteDialogFormOpen called with props',props);
    // log.info('handleDeleteDialogFormOpen called dialogFormObject',dialogFormObject, "event value", a);
    
    if (a) {
      setdialogFormObject(a.rawValue);
      setdialogOuterFormObject(a.rawValue)
      // log.info('handleDeleteDialogFormOpen parameter is defined dialogFormObject',dialogFormObject);
    } else {
      // setdialogFormObject(Object.assign({},dialogFormObject?dialogFormObject:{},{[label]:undefined}));
      setdialogFormObject(undefined);
      // log.info('handleDeleteDialogFormOpen parameter is undefined, no value is passed to form. dialogFormObject',dialogFormObject);
    }
    setDeleteDialogFormIsOpen(true);
  },[props.instancesToDisplay]);

  // ##############################################################################################
  const handleDuplicateDialogFormOpen = useCallback((a?:TableComponentRow,event?:any) => {
    // event?.stopPropagation();
    // log.info('handleDuplicateDialogFormOpen called with props',props);
    // log.info('handleDuplicateDialogFormOpen called dialogFormObject',dialogFormObject, "event value", a);
    
    if (a) {
      // Create a duplicate with a new random UUID
      const duplicatedObject = {
        ...a.rawValue,
        uuid: crypto.randomUUID()
      };
      setdialogFormObject(duplicatedObject);
      setdialogOuterFormObject(duplicatedObject);
      // log.info('handleDuplicateDialogFormOpen parameter is defined, created duplicate with new UUID',duplicatedObject);
    } else {
      setdialogFormObject(undefined);
      // log.info('handleDuplicateDialogFormOpen parameter is undefined, no value is passed to form. dialogFormObject',dialogFormObject);
    }
    // setEditDialogFormIsOpen(true);
    setValueObjectEditMode("create");
    props.setAddObjectdialogFormIsOpen(true);
  },[props.instancesToDisplay, props.setAddObjectdialogFormIsOpen]);
  

  

  // ##############################################################################################
  // Define tools column configuration once to ensure consistency across grid types
  const toolsColumnDefinition: ToolsColumnDefinition = useMemo(() => ({
    // type: "tools",
    field: "tools",
    headerName: "Actions", 
    // width: 120
    width: 100
  }), []);

    // ##############################################################################################
  const agGridDefaultColDef: Partial<AutoGeneratedColumnDef> = useMemo(()=>({
    ...defaultColDef,
    editable: true,
    floatingFilter: false,
    cellEditor: EntityEditor,
    // Customize header to handle filter icon clicks
    headerComponentParams: {
      onFilterClick: () => {
        withLiveGridApi((api) => {
          api.setFilterModel(null);
        });
      }
    }
  } as Partial<AutoGeneratedColumnDef>),[withLiveGridApi]);

  // ##############################################################################################
  // const columnDefs: (ColDef | ColGroupDef)[] = useMemo(() => {
  // TODO: used only by AgGrid !?!
  const agGridColumnDefs: AutoGeneratedColumnDef[] = useMemo(() => {
    // Start with the base column definitions using the shared tools column definition
    const baseColumnDefs: AutoGeneratedColumnDef[] = [
      {
        ...toolsColumnDefinition,
        cellRenderer: ToolsCellRenderer,
        editable: false,
        sortable: false,
        filter: false,
        resizable: false,
        cellRendererParams: {
          onClickEdit: handleEditDialogFormOpen,
          onClickDuplicate: handleDuplicateDialogFormOpen,
          onClickDelete: handleDeleteDialogFormOpen,
        },
      } as AutoGeneratedColumnDef,
      ...props.columnDefs.columnDefs.map((colDef: AutoGeneratedColumnDef) => ({
        ...colDef,
        // ...(colDef.field === "startDate"
        // ? { sort: "desc" as "asc" | "desc", sortIndex: 0 }
        // : {}),
        // Add value getter to access the correct data path. TODO: use the same function for all columns!
        valueGetter: (params: any) => {
          if (!params.data || !colDef.field) return "";

          // Check if this is a foreign key column
          const isFK = colDef.cellRendererParams?.isFK;
          const entityUuid = colDef.cellRendererParams?.entityUuid;

          if (isFK && entityUuid && params.data?.foreignKeyObjects?.[entityUuid]) {
            // For foreign key columns, return the name of the referenced entity
            const foreignKeyUuid = params.data.rawValue?.[colDef.field];
            if (foreignKeyUuid && params.data.foreignKeyObjects[entityUuid][foreignKeyUuid]) {
              return params.data.foreignKeyObjects[entityUuid][foreignKeyUuid].name || "";
            }
            return ""; // No foreign key object found
          }

          // For regular columns, use displayedValue or rawValue
          return (
            params.data.displayedValue?.[colDef.field] ?? params.data.rawValue?.[colDef.field] ?? ""
          );
        },
        // Add value setter for editable cells. TODO: use the same function for all columns!
        valueSetter: (params: any) => {
          if (!params.data || !colDef.field) return false;
          // Update both displayedValue and rawValue
          if (params.data.displayedValue) {
            params.data.displayedValue[colDef.field] = params.newValue;
          }
          if (params.data.rawValue) {
            params.data.rawValue[colDef.field] = params.newValue;
          }
          return true;
        },
        // Override filter value getter to ensure filtering works on the correct data. TODO: use the same function for all columns!
        filterValueGetter: (params: any) => {
          if (!params.data || !colDef.field) return "";

          // Check if this is a foreign key column
          const isFK = colDef.cellRendererParams?.isFK;
          const entityUuid = colDef.cellRendererParams?.entityUuid;

          if (isFK && entityUuid && params.data?.foreignKeyObjects?.[entityUuid]) {
            // For foreign key columns, return the name of the referenced entity
            const foreignKeyUuid = params.data.rawValue?.[colDef.field];
            if (foreignKeyUuid && params.data.foreignKeyObjects[entityUuid][foreignKeyUuid]) {
              return params.data.foreignKeyObjects[entityUuid][foreignKeyUuid].name || "";
            }
            return ""; // No foreign key object found
          }

          // For regular columns, use displayedValue or rawValue
          return (
            params.data.displayedValue?.[colDef.field] ?? params.data.rawValue?.[colDef.field] ?? ""
          );
        },
        // // Enable specific filter types based on data type
        // filter: true,
        // filterParams: {
        //   filterOptions: ["contains", "startsWith", "endsWith", "equals", "notEqual"],
        //   defaultOption: "contains",
        //   suppressAndOrCondition: false,
        // },
      }))
    ];

    return baseColumnDefs;
  }, [
    props.columnDefs,
    handleEditDialogFormOpen,
    handleDuplicateDialogFormOpen,
    handleDeleteDialogFormOpen,
    toolsColumnDefinition,
  ]);
  
  // log.info(
  //   "EntityInstanceGrid started count",
  //   count++,
  //   "with props",
  //   props,
  //   props === prevProps,
  //   "columnDefs",
  //   columnDefs,
  //   "rowData changed:",
  //   props?.instancesToDisplay === prevProps?.instancesToDisplay
  // );
  // prevProps = props;

  // ##############################################################################################
  // ##############################################################################################
  // ##############################################################################################
  // ##############################################################################################
  const onGlideGridCellClicked = useCallback(
    (cell: any, event: any) => {
      const [col, row] = cell;
      const rowData = tableComponentRows.tableComponentRowUuidIndexSchema[row];
      
      // Get the field name from the Glide grid column structure
      // Note: In GlideDataGridComponent, columns[0] is tools, columns[1+] are data columns
      let fieldName: string | undefined;
      if (col === 0) {
        fieldName = "tools";
      } else {
        // Find the data column by index (col - 1 because tools is at index 0)
        const dataColumnIndex = col - 1;
        const dataColumns = props.columnDefs.columnDefs.filter((cd: any) => cd.field && cd.field !== 'tools');
        if (dataColumnIndex >= 0 && dataColumnIndex < dataColumns.length) {
          fieldName = dataColumns[dataColumnIndex].field;
        }
      }
      
      // Early return for non-navigable clicks
      if (
        props.type !== "EntityInstance" ||
        !fieldName ||
        fieldName === "tools"
      ) {
        return;
      }

      log.warn("onGlideGridCellClicked fieldName", fieldName, "cell", cell, "event", event, "props", props);

      // Use setTimeout to defer navigation and prevent blocking the UI thread
      setTimeout(() => {
        // Determine which columns navigate to the current instance's detail view:
        // always "name", plus the PK attribute(s) of the entity
        const pkAttributes = getEntityPrimaryKeyAttributes(presentModelSource ?? {});

        const navigableColumns = ["name", ...pkAttributes];

        if (navigableColumns.includes(fieldName)) {
          // display current Entity Details for Entity Instance
          const applicationSection = ["MetaModel", "model"].includes(
            presentModelSource?.conceptLevel as any
          )
            ? "model"
            : context.applicationSection ?? "";

          const primaryKeyValue = getInstancePrimaryKeyValue(presentModelSource ?? {}, rowData.rawValue);
          navigate(
            reportUrl(
              props.application,
              contextDeploymentUuid ?? "",
              applicationSection,
              presentModelSource?.defaultInstanceDetailsReportUuid ?? "",
              String(primaryKeyValue),
            )
          );
        } else {
          // Cache schema definition lookup
          const schemaDefinition = presentModelSource?.mlSchema?.definition ?? {};
          const columnDefinitionAttribute = schemaDefinition[fieldName];

          if (
            columnDefinitionAttribute &&
            (columnDefinitionAttribute as any).type === "uuid" &&
            (columnDefinitionAttribute as any).tag?.value?.foreignKeyParams?.targetEntity
          ) {
            // Find the column definition to get the target entity UUID
            const columnDef = props.columnDefs.columnDefs.find((cd: any) => cd.field === fieldName);
            const targetEntityUuid = columnDef?.cellRenderer?.entityUuid;
            
            const targetPresentEntity = findEntityFromUuid(
              currentModel,
              targetEntityUuid,
            );

            const targetApplicationSection =
              (columnDefinitionAttribute as any)?.tag?.value?.foreignKeyParams?.targetEntityApplicationSection ||
              context.applicationSection;

            navigate(
              reportUrl(
                props.application,
                contextDeploymentUuid ?? "",
                targetApplicationSection,
                targetPresentEntity?.defaultInstanceDetailsReportUuid ?? "",
                String((rowData.rawValue as any)[fieldName]),
              )
            );
          } else {
            log.info(
              "onGlideGridCellClicked cell is not an Entity Instance uuid, no navigation occurs.",
              columnDefinitionAttribute
            );
          }
        }
      }, 0);
    },
    [
      props.type,
      presentModelSource,
      contextDeploymentUuid,
      context.applicationSection,
      currentModel.entityVersions,
      navigate,
      agGridColumnDefs,
      tableComponentRows,
      props.columnDefs,
    ]
  );

  // ##############################################################################################
  const onCellClicked = useCallback(
    (event: CellClickedEvent) => {
      // Early return for non-navigable clicks
      if (
        props.type !== "EntityInstance" ||
        !event.colDef.field ||
        event.colDef.field === "tools"
      ) {
        return;
      }

      const fieldName = event.colDef.field;
      log.info(
        "onCellClicked event.colDef.field",
        fieldName,
        "event",
        event,
        "props",
        props,
        "presentModelSource",
        presentModelSource
      );

      // Use setTimeout to defer navigation and prevent blocking the UI thread
      setTimeout(() => {
        // Determine which columns navigate to the current instance's detail view:
        // always "name", plus the PK attribute(s) of the entity
        const pkAttributes = getEntityPrimaryKeyAttributes(presentModelSource ?? {});

        const navigableColumns = ["name", ...pkAttributes];

        if (navigableColumns.includes(fieldName)) { // columns to navigate to current instance (the row object itself)
          // display current Entity Details for Entity Instance
          const applicationSection = ["MetaModel", "model"].includes(
            presentModelSource?.conceptLevel as any
          )
            ? "model"
            : context.applicationSection ?? "";

          const primaryKeyValue = getInstancePrimaryKeyValue(presentModelSource ?? {}, event.data.rawValue);
          navigate(
            reportUrl(
              props.application,
              contextDeploymentUuid ?? "",
              applicationSection,
              presentModelSource?.defaultInstanceDetailsReportUuid ?? "",
              String(primaryKeyValue),
            )
          );
        } else { // other columns
          // Cache schema definition lookup
          const schemaDefinition = presentModelSource?.mlSchema?.definition ?? {};
          const columnDefinitionAttribute = schemaDefinition[fieldName];

          log.info("onCellClicked foreign key navigation columnDefinitionAttribute", columnDefinitionAttribute);
          if (
            columnDefinitionAttribute &&
            (columnDefinitionAttribute as any).type === "uuid" &&
            (columnDefinitionAttribute as any).tag?.value?.foreignKeyParams?.targetEntity
          ) {
            const targetPresentEntity = findEntityFromUuid(
              currentModel,
              event.colDef.cellRendererParams.entityUuid,
            );

            const targetApplicationSection =
              (columnDefinitionAttribute as any)?.tag?.value?.targetEntityApplicationSection ||
              context.applicationSection;
            const navigateTo: string = reportUrl(
              props.application,
              contextDeploymentUuid ?? "",
              targetApplicationSection,
              targetPresentEntity?.defaultInstanceDetailsReportUuid ?? "",
              String(event.data.rawValue[fieldName]),
            );
            log.info("onCellClicked navigating to", navigateTo);
            navigate(navigateTo);
          } else {
            log.info(
              "onCellClicked cell is not an Entity Instance uuid, no navigation occurs.",
              columnDefinitionAttribute
            );
          }
        }
      }, 0);
    },
    [
      props.type,
      presentModelSource,
      contextDeploymentUuid,
      context.applicationSection,
      currentModel.entityVersions,
      navigate,
    ]
  );
  
  // Sizing mode (D2-d): paged (pageSize, default 50) XOR scroll (maxRows)
  const sizingMode = resolveGridSizingMode(props.pageSize, props.maxRows);
  const rowCount = tableComponentRows.tableComponentRowUuidIndexSchema.length;
  const agGridMode = agGridModeProps(sizingMode);
  // Paged mode: domLayout="autoHeight" — ag-grid sizes itself to the page's rows, no explicit height.
  const agGridContainerHeight =
    sizingMode.mode === "scroll"
      ? `${computeAgGridScrollHeight(rowCount, sizingMode.maxRows, contextTheme.components.table.maxHeight)}px`
      : undefined;

  const notifyDisplayedPageRowsChange = useCallback(
    (rows: TableComponentRow[]) => {
      if (!props.onDisplayedPageRowsChange) {
        return;
      }
      props.onDisplayedPageRowsChange(
        Object.fromEntries(
          rows
            .map((row) => row.rawValue)
            .filter(
              (instance): instance is EntityInstance =>
                instance != null && typeof instance === "object" && !Array.isArray(instance),
            )
            .map((instance) => [instance.uuid, instance]),
        ),
      );
    },
    [props.onDisplayedPageRowsChange],
  );

  const notifyAgGridDisplayedPageRowsChange = useCallback(() => {
    if (!props.onDisplayedPageRowsChange || sizingMode.mode !== "paged") {
      return;
    }
    withLiveGridApi((api) => {
      const pageIndex = api.paginationGetCurrentPage();
      const pageRows = paginateRows(
        tableComponentRows.tableComponentRowUuidIndexSchema,
        pageIndex,
        sizingMode.pageSize,
      ).pageRows;
      notifyDisplayedPageRowsChange(pageRows);
    });
  }, [
    notifyDisplayedPageRowsChange,
    props.onDisplayedPageRowsChange,
    sizingMode,
    tableComponentRows.tableComponentRowUuidIndexSchema,
    withLiveGridApi,
  ]);

  useEffect(() => {
    if (gridType !== "ag-grid") {
      return;
    }
    notifyAgGridDisplayedPageRowsChange();
  }, [
    gridType,
    notifyAgGridDisplayedPageRowsChange,
    props.pageSize,
    props.maxRows,
    tableComponentRows.tableComponentRowUuidIndexSchema.length,
  ]);

  return (
    <div 
      // ref={containerRef}
      style={{ 
        width: '100%', 
        maxWidth: '100%',
        display: 'flex', 
        flexDirection: 'column',
        flexGrow: 1,
        boxSizing: 'border-box',
        fontFamily: contextTheme.typography.fontFamily,
      }}
    >
      {/* Apply unified table styles */}
      <style>{agGridStyles}</style>
      {/* <span>EntityInstanceGrid containerHeight {containerHeight}</span> */}
      {/* <span>EntityInstanceGrid count {count}</span>
      <br /> */}
      {/* <span>{props.type}</span>
      <br /> */}
      {/* <span>rowData: {JSON.stringify(props.rowData.instancesWithStringifiedJsonAttributes)}</span> */}
      <JsonDisplayHelper debug={true}
        componentName="EntityInstanceGrid"
        elements={[
          {
            label: `props (deploymentUuid=${contextDeploymentUuid}, application=${props.application})`,
            data: props,
            copyButton: true,
            useCodeBlock: true,
          },
          {
            label: "instancesToDisplay",
            data: props.instancesToDisplay,
            copyButton: true,
            useCodeBlock: true,
          },
          {
            label: "contextTheme",
            data: { contextTheme },
            copyButton: true,
            useCodeBlock: true,
          },
          {
            label: "agGridColumnDefs",
            data: agGridColumnDefs,
            copyButton: true,
            useCodeBlock: true,
          },
          {
            label: "tableComponentRows",
            data: tableComponentRows,
            copyButton: true,
            useCodeBlock: true,
          },
          {
            label: "sizing (D2-d)",
            data: {
              props: { pageSize: props.pageSize ?? null, maxRows: props.maxRows ?? null },
              resolvedMode: sizingMode,
              rowCount,
              agGridContainerHeight: agGridContainerHeight ?? "auto (autoHeight)",
              agGridMode,
              themeTable: {
                maxHeight: contextTheme.components.table.maxHeight,
                minHeight: contextTheme.components.table.minHeight,
              },
            },
            copyButton: true,
            useCodeBlock: true,
          }
        ]}
      />
      {/* <GridSizingDebugProbe
        targets={[
          { label: "ag-grid container", selector: "#entity-instance-ag-grid" },
          { label: "ag-grid react div", selector: "#entity-instance-ag-grid > div" },
          { label: "ag-grid root-wrapper", selector: "#entity-instance-ag-grid .ag-root-wrapper" },
          { label: "ag-grid body-viewport", selector: "#entity-instance-ag-grid .ag-body-viewport" },
          { label: "ag-grid center-cols-viewport", selector: "#entity-instance-ag-grid .ag-center-cols-viewport" },
          { label: "ag-grid paging-panel", selector: "#entity-instance-ag-grid .ag-paging-panel" },
          { label: "glide container", selector: ".glide-data-grid-grid-container" },
          { label: "glide editor", selector: ".glide-data-grid-grid-container [data-testid='glide-data-grid']" },
          { label: "value-object ag-grid container", selector: "#valueObjectGrid" },
        ]}
      /> */}
      {props.type == "EntityInstance" ? (
        <div>
          {dialogFormObject ? (
            <>
              <JsonObjectEditFormDialog
                showButton={false}
                valueObjectEditMode={valueObjectEditMode}
                isAttributes={true}
                label={props.currentEntity?.name ?? "No Entity Found!"}
                defaultFormValuesObject={dialogFormObject ?? props.defaultFormValuesObject}
                entity={presentModelSource ?? {} as Entity}
                mlSchema={presentModelSource?.mlSchema as JzodObject}
                foreignKeyObjects={props.foreignKeyObjects}
                currentApplication={props.application}
                applicationDeploymentMap={props.applicationDeploymentMap}
                currentDeploymentUuid={contextDeploymentUuid}
                currentApplicationSection={context.applicationSection}
                currentAppModel={currentModel}
                currentMiroirModel={miroirMetaModel}
                onSubmit={onEditDialogFormSubmit}
                onClose={handleEditDialogFormClose}
                isOpen={props.addObjectdialogFormIsOpen} // redundant with addObjectdialogFormIsOpen?
                addObjectdialogFormIsOpen={props.addObjectdialogFormIsOpen}
                setAddObjectdialogFormIsOpen={props.setAddObjectdialogFormIsOpen}
              />
              <JsonObjectDeleteFormDialog
                showButton={false}
                currentApplication={props.application}
                currentApplicationDeploymentMap={props.applicationDeploymentMap}
                currentDeploymentUuid={contextDeploymentUuid}
                currentApplicationSection={context.applicationSection}
                currentAppModel={currentModel}
                currentMiroirModel={miroirMetaModel}
                defaultFormValuesObject={dialogFormObject ?? props.defaultFormValuesObject}
                deleteObjectdialogFormIsOpen={deleteDialogFormIsOpen}
                mlSchema={presentModelSource?.mlSchema as JzodObject}
                foreignKeyObjects={props.foreignKeyObjects}
                isOpen={deleteDialogFormIsOpen} // redundant with deleteObjectdialogFormIsOpen?
                isAttributes={true}
                label={props.currentEntity?.name ?? "No Entity Found!"}
                onDeleteFormObject={onDeleteDialogFormSubmit}
                onClose={handleEditDialogFormClose}
                setDeleteObjectdialogFormIsOpen={setDeleteDialogFormIsOpen}
              />
            </>
          ) : (
            <></>
          )}
          {gridType === "ag-grid" ? (
            <>
              {/* Global Clear All Filters Icon */}
              {hasAnyFilter && (
                <div style={filterToolbarStyles.container}>
                  <span
                    className="mtable-global-clear-filters"
                    onClick={handleGlobalClearAllFilters}
                    style={filterToolbarStyles.clearAllButton}
                    title="Clear all filters"
                  >
                    ▼ Clear All Filters
                  </span>
                </div>
              )}
              <div
                id="entity-instance-ag-grid"
                className="ag-theme-alpine"
                style={{
                  ...props.styles,
                  height: agGridContainerHeight,
                  width: '100%',
                  maxWidth: '100%',
                  overflow: 'auto', // Allow table to scroll when needed
                  boxSizing: 'border-box',
                  borderRadius: contextTheme.components.table.borderRadius,
                  border: contextTheme.components.table.border,
                }}
              >
                <AgGridReact
                  domLayout={agGridMode.domLayout}
                  pagination={agGridMode.pagination}
                  paginationPageSize={agGridMode.paginationPageSize}
                  paginationPageSizeSelector={agGridMode.paginationPageSizeSelector}
                  columnDefs={agGridColumnDefs}
                  rowData={tableComponentRows.tableComponentRowUuidIndexSchema}
                  getRowId={(params) => {
                    // Use the entity instance UUID for row identification
                    return params.data?.rawValue?.uuid
                      ? params.data?.rawValue?.uuid
                      : params.data?.rawValue?.id || Math.random().toString();
                  }}
                  defaultColDef={agGridDefaultColDef}
                  onCellClicked={onCellClicked}
                  onCellValueChanged={onCellValueChanged}
                  onGridReady={(params) => {
                    onGridReady(params);
                    notifyAgGridDisplayedPageRowsChange();
                  }}
                  onGridPreDestroyed={handleGridPreDestroyed}
                  onPaginationChanged={notifyAgGridDisplayedPageRowsChange}
                  // DO NOT Enable advanced filtering and sorting features, not free software
                  // enableRangeSelection={true}
                  enableCellTextSelection={true}
                  suppressRowClickSelection={true}
                  animateRows={true}
                  skipHeaderOnAutoSize={true}
                  suppressHorizontalScroll={false}
                ></AgGridReact>
              </div>
            </>
          ) : (
            <GlideDataGridComponent
              tableComponentRows={tableComponentRows}
              columnDefs={props.columnDefs}
              styles={{
                ...props.styles,
                // height: `${containerHeight}px`,
                fontFamily: contextTheme.typography.fontFamily,
                fontSize: contextTheme.typography.fontSize,
                borderRadius: contextTheme.components.table.borderRadius,
                border: contextTheme.components.table.border,
              }}
              type={props.type}
              toolsColumnDefinition={toolsColumnDefinition}
              maxRows={props.maxRows}
              pageSize={props.pageSize}
              theme={contextTheme}
              glideTheme={glideTheme}
              onCellClicked={onGlideGridCellClicked}
              onCellEdited={(cell, newValue) => {
                // Handle cell edit for Glide Data Grid
                log.info("Glide cell edited", cell, newValue);
                // You might want to implement similar logic to onCellValueChanged
              }}
              onRowEdit={handleEditDialogFormOpen}
              onRowDelete={handleDeleteDialogFormOpen}
              onRowDuplicate={handleDuplicateDialogFormOpen}
              onDisplayedPageRowsChange={notifyDisplayedPageRowsChange}
            />
          )}
        </div>
      ) : (
        // For non-EntityInstance types (JSON_ARRAY), use ValueObjectGrid
        <ValueObjectGrid
          valueObjects={(props as any).rowData || []}
          mlSchema={{
            type: "object",
            definition: Object.fromEntries(
              props.columnDefs.columnDefs.map((colDef: any) => [
                colDef.field,
                { type: "string" } // Default to string type for JSON array columns
              ])
            )
          }}
          columnDefs={props.columnDefs}
          styles={props.styles}
          theme={contextTheme}
          maxRows={props.maxRows}
          pageSize={props.pageSize}
          sortByAttribute={props.sortByAttribute}
          gridType={gridType}
          displayTools={false} // No editing for JSON arrays in EntityInstanceGrid context
        />
      )}
    </div>
  );
}