  // ##############################################################################################

import type { AutoGeneratedColumnDef } from "./ValueObjectGridInterface";

  // Default column definition
export const defaultColDef: Partial<AutoGeneratedColumnDef> = {
    editable: false, // Value objects are read-only
    sortable: true,
    filter: true,
    resizable: true,
    // floatingFilter: false,
    minWidth: 50,
    // filterParams: {
    //   filterOptions: ['contains', 'startsWith', 'endsWith', 'equals', 'notEqual'],
    //   defaultOption: 'contains',
    //   suppressAndOrCondition: false,
    //   trimInput: true,
    //   debounceMs: 300,
    // },
};
