name: Build Linux

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Set up Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: |
          npm ci
      - run: npx lerna run devBuild --scope=miroir-standalone-app
      - run: npm run dist-linux -w miroir-standalone-app-electron
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: linux-build
          path: packages/miroir-standalone-app-electron/release/