name: Build Linux

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: |
          npm ci
      - run: npx lerna run devBuild --scope=miroir-standalone-app
      - run: npm run dist-linux -w miroir-standalone-app-electron
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: packages/miroir-standalone-app-electron/release/